### ISSUE TITLE
Button Mapping - Split screen

### ISSUE THREAD

**Issue by africabloe** [crdroidandroid/issue_tracker#11]
### Issue type

Feature not working as intended

### Device

Xiaomi Redmi Note 4X (mido)

### crDroid version

crDroid 8

### Bug description

Split screen not works on button customization. It is not working for any Hardware button - neither for Navigation bar buttons.
Additionally, it's kind of weird to customize the Hardware buttons in the NAVIGATION menu and not in the menu they belong to - BUTTONS menu.
Split screen works only separately. Per application touch

### Steps to reproduce

System Settings > crDroid Settings > Navigation > Actions  > Back/Home/Recents > **Split screen**

### Relevant log (logcat/build log)

```shell
10-02 00:44:32.976  2116  2116 D b/223498680: BaseRecentsViewStateController setStateWithAnimation state=OverviewSplitSelect, config.skipOverview=false
10-02 00:44:32.977  2116  2116 D b/223498680: BaseRecentsViewStateController setStateWithAnimationInternal toState=OverviewSplitSelect, alpha=1.0
10-02 00:44:32.989  2116  2116 D b/223498680: LRV onStateTransitionStart setFreezeVisibility=true, toState=OverviewSplitSelect
10-02 00:44:33.262  2116  2116 D b/223498680: LRV onStateTransitionComplete setFreezeVisibility=false, finalState=OverviewSplitSelect
10-02 00:44:33.652  3092  3092 D GmsPhenotypeSvc: onBind: Intent { act=com.google.android.gms.phenotype.service.START pkg=com.google.android.gms }
10-02 00:44:33.657  3092  3461 D GmsPhenotypeSvc: bound by: GetServiceRequest{serviceId=PHENOTYPE, gmsVersion=222410000, packageName='com.google.android.apps.turbo', extras=Bundle[{}]}
10-02 00:44:33.666  3092 15376 D SafeParcel: Unknown field id 12 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
10-02 00:44:33.673  3092  3461 D GmsPhenotypeSvc: getConfigurationSnapshot(com.google.android.libraries.performance.primes#com.google.android.apps.turbo, , null)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: Unable to update local snapshot for com.google.android.libraries.performance.primes#com.google.android.apps.turbo, may result in stale flags.
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at cbl.s(PG:6)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at cbl.get(PG:4)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at byg.C(PG:2)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at bdw.d(PG:1)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at bdr.run(PG:3)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at java.lang.Thread.run(Thread.java:1013)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at apl.run(PG:6)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at cce.execute(PG:1)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at apm.a(PG:1)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at bop.b(PG:5)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at apy.k(PG:3)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at ahu.q(PG:1)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at ai.p(PG:2)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at aoz.a(PG:72)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at xj.onTransact(PG:3)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at android.os.Binder.execTransactInternal(Binder.java:1184)
10-02 00:44:33.683 16445 16491 W MobStoreFlagStore: 	at android.os.Binder.execTransact(Binder.java:1143)
10-02 00:44:33.979  8579 12511 E Adjust  : Adjust not initialized correctly
10-02 00:44:35.771   622   622 E QTI PowerHAL: Failed to acquire lock.
10-02 00:44:35.884  1476  2520 W InputManager-JNI: Input channel object 'c2a0e1c Toast (client)' was disposed without first being removed with the input manager!
10-02 00:44:35.891  1476  2520 W NotificationService: Toast already killed. pkg=com.android.launcher3 token=android.os.BinderProxy@477d67f
10-02 00:44:36.025   622   622 E QTI PowerHAL: Failed to acquire lock.
10-02 00:44:36.026  1476  2520 I NotificationService: cancelToast pkg=com.android.launcher3 token=android.os.BinderProxy@477d67f
10-02 00:44:36.027  1476  2520 W NotificationService: Toast already cancelled. pkg=com.android.launcher3 token=android.os.BinderProxy@477d67f
10-02 00:44:36.666 16445 16478 W GoogleApiManager: aqq could not execute call because it requires feature (usage_and_diagnostics_listener, 1).
10-02 00:44:37.329   622   622 E QTI PowerHAL: Failed to acquire lock.
10-02 00:44:37.582  1476  2520 I NotificationService: cancelToast pkg=com.android.launcher3 token=android.os.BinderProxy@477d67f
10-02 00:44:37.582  1476  2520 W NotificationService: Toast already cancelled. pkg=com.android.launcher3 token=android.os.BinderProxy@477d67f
10-02 00:44:37.583   622   622 E QTI PowerHAL: Failed to acquire lock.
10-02 00:44:38.641  1476  2520 W InputManager-JNI: Input channel object 'ebd5b9b Toast (client)' was disposed without first being removed with the input manager!
10-02 00:44:38.646   622   622 E QTI PowerHAL: Failed to acquire lock.
10-02 00:44:38.648  1476  2520 W NotificationService: Toast already killed. pkg=com.android.launcher3 token=android.os.BinderProxy@d2a6e02
10-02 00:44:38.970   622   622 E QTI PowerHAL: Failed to acquire lock.
10-02 00:44:38.972  1476  2520 I NotificationService: cancelToast pkg=com.android.launcher3 token=android.os.BinderProxy@477d67f
10-02 00:44:38.972  1476  2520 W NotificationService: Toast already cancelled. pkg=com.android.launcher3 token=android.os.BinderProxy@477d67f
10-02 00:44:39.282  1476  2520 W WindowManager: Cannot find window which accessibility connection is added to
10-02 00:44:39.302   622   622 I android.hardware.power-service-qti: Power setMode: 5 to: 1
10-02 00:44:39.302   622   622 E QTI PowerHAL: Failed to acquire lock.
10-02 00:44:39.302   622   622 E QTI PowerHAL: Failed to perform launch boost
10-02 00:44:39.330   622   622 I android.hardware.power-service-qti: Power setMode: 5 to: 1
10-02 00:44:39.330   622   622 E QTI PowerHAL: Failed to acquire lock.
10-02 00:44:39.330   622   622 E QTI PowerHAL: Failed to perform launch boost
10-02 00:44:39.360  1476  2520 W InputManager-JNI: Input channel object 'e41ecdd com.android.settings/com.android.settings.SubSettings (client)' was disposed without first being removed with the input manager!
10-02 00:44:39.362  1476  2523 W InputManager-JNI: Input channel object '462d2a7 com.android.documentsui/com.android.documentsui.files.FilesActivity (client)' was disposed without first being removed with the input manager!
10-02 00:44:39.374 13653 13653 D ActivityEmbeddingUtils: isFlagEnabled = true
10-02 00:44:39.374 13653 13653 D ActivityEmbeddingUtils: isSplitSupported = false
10-02 00:44:39.385 13653 13653 D ConstraintsHelper: construct key=pixel_nav_animation available=true
10-02 00:44:39.387 13653 13653 D ConstraintsHelper: construct key=navigation_bar_menu_arrow_keys available=true
10-02 00:44:39.390 13653 13653 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
10-02 00:44:39.391 13653 13653 D ConstraintsHelper: construct key=navbar_inverse_layout available=true
10-02 00:44:39.394 13653 13653 W InstrumentedPrefFrag: Screen title missing for fragment com.crdroid.settings.fragments.Navigation
10-02 00:44:39.395  1476  2520 W WindowManager: Attempted to add starting window to token but already cleaned
10-02 00:44:39.395  2527  2559 W StartingSurfaceDrawer: Failed to add snapshot starting window res=-5
10-02 00:44:39.396  1476  2014 W WindowManager: Attempted to add starting window to token but already cleaned
10-02 00:44:39.397  2527  2559 W StartingSurfaceDrawer: Failed to add snapshot starting window res=-5
10-02 00:44:39.408 13653 13653 D ConstraintsHelper: construct key=lockscreen_media_metadata available=true
10-02 00:44:39.409 13653 13653 D ConstraintsHelper: construct key=lockscreen_battery_info available=true
10-02 00:44:39.412 13653 13653 D ConstraintsHelper: construct key=double_tap_sleep_lockscreen available=true
10-02 00:44:39.413 13653 13653 D ConstraintsHelper: construct key=fp_success_vibrate available=true
10-02 00:44:39.415 13653 13653 D ConstraintsHelper: construct key=fp_error_vibrate available=true
10-02 00:44:39.417 13653 13653 D ConstraintsHelper: construct key=enable_ripple_effect available=true
10-02 00:44:39.419 13653 13653 D ConstraintsHelper: construct key=lockscreen_enable_power_menu available=true
10-02 00:44:39.421 13653 13653 W InstrumentedPrefFrag: Screen title missing for fragment com.crdroid.settings.fragments.LockScreen
10-02 00:44:39.427 13653 13653 D ConstraintsHelper: construct key=hardware_keys_disable available=true
10-02 00:44:39.427 13653 13653 D ConstraintsHelper: construct key=swap_capacitive_keys available=true
10-02 00:44:39.429 13653 13653 D ConstraintsHelper: construct key=additional_buttons available=false
10-02 00:44:39.430 13653 13653 D ConstraintsHelper: construct key=anbi_enabled available=true
10-02 00:44:39.432 13653 13653 D ConstraintsHelper: construct key=torch_long_press_power_gesture available=true
10-02 00:44:39.439 13653 13653 D ConstraintsHelper: construct key=home_wake_screen available=true
10-02 00:44:39.442 13653 13653 D ConstraintsHelper: construct key=back_wake_screen available=true
10-02 00:44:39.444 13653 13653 D ConstraintsHelper: construct key=menu_wake_screen available=true
10-02 00:44:39.446 13653 13653 D ConstraintsHelper: construct key=assist_wake_screen available=true
10-02 00:44:39.449 13653 13653 D ConstraintsHelper: construct key=app_switch_wake_screen available=true
10-02 00:44:39.451 13653 13653 D ConstraintsHelper: construct key=camera_wake_screen available=true
10-02 00:44:39.453 13653 13653 D ConstraintsHelper: construct key=camera_sleep_on_release available=true
10-02 00:44:39.455 13653 13653 D ConstraintsHelper: construct key=camera_launch available=true
10-02 00:44:39.457 13653 13653 D ConstraintsHelper: construct key=volume_wake_screen available=true
10-02 00:44:39.459 13653 13653 D ConstraintsHelper: construct key=volume_answer_call available=true
10-02 00:44:39.461 13653 13653 D ConstraintsHelper: construct key=volbtn_music_controls available=true
10-02 00:44:39.463 13653 13653 W InstrumentedPrefFrag: Screen title missing for fragment com.crdroid.settings.fragments.Buttons
10-02 00:44:39.478 13653 13653 D ConstraintsHelper: construct key=status_bar_clock available=true
10-02 00:44:39.480 13653 13653 W ListPreference: Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
10-02 00:44:39.481 13653 13653 D ConstraintsHelper: construct key=use_old_mobiletype available=true
10-02 00:44:39.482 13653 13653 D ConstraintsHelper: construct key=data_disabled_icon available=true
10-02 00:44:39.484 13653 13653 D ConstraintsHelper: construct key=show_fourg_icon available=true
10-02 00:44:39.487 13653 13653 D ConstraintsHelper: construct key=roaming_indicator_icon available=true
10-02 00:44:39.489 13653 13653 D ConstraintsHelper: construct key=combined_status_bar_signal_icons available=true
10-02 00:44:39.490 13653 13653 D ConstraintsHelper: construct key=bluetooth_show_battery available=true
10-02 00:44:39.497 13653 13653 D ConstraintsHelper: construct key=volte_vowifi_override available=true
10-02 00:44:39.498 13653 13653 D ConstraintsHelper: construct key=enable_camera_privacy_indicator available=true
10-02 00:44:39.500 13653 13653 D ConstraintsHelper: construct key=enable_location_privacy_indicator available=true
10-02 00:44:39.503 13653 13653 D ConstraintsHelper: construct key=statusbar_colored_icons available=true
10-02 00:44:39.505 13653 13653 D ConstraintsHelper: construct key=statusbar_notif_count available=true
10-02 00:44:39.508 13653 13653 D ConstraintsHelper: construct key=status_bar_battery_text_charging available=true
10-02 00:44:39.509 13657 13657 W SelectionTracker: Setting gestureTooltypes is likely to result in unexpected behavior.
10-02 00:44:39.509 13653 13653 D ConstraintsHelper: construct key=double_tap_sleep_gesture available=true
10-02 00:44:39.511 13653 13653 D ConstraintsHelper: construct key=status_bar_brightness_control available=true
10-02 00:44:39.513 13653 13653 D ConstraintsHelper: construct key=qs_quick_pulldown available=true
10-02 00:44:39.515 13653 13653 W InstrumentedPrefFrag: Screen title missing for fragment com.crdroid.settings.fragments.StatusBar
10-02 00:44:39.520 13653 13653 D ConstraintsHelper: construct key=show_qs_clock available=true
10-02 00:44:39.525 13653 13653 D ConstraintsHelper: construct key=show_qs_date available=true
10-02 00:44:39.528 13653 13653 D ConstraintsHelper: construct key=qs_show_battery_estimate available=true
10-02 00:44:39.529 13653 13653 D ConstraintsHelper: construct key=qs_show_brightness_slider available=true
10-02 00:44:39.530 13653 13653 D ConstraintsHelper: construct key=qs_brightness_slider_position available=true
10-02 00:44:39.531 13653 13653 D ConstraintsHelper: construct key=qs_show_auto_brightness available=true
10-02 00:44:39.531 13653 13653 D ConstraintsHelper: construct key=secure_lockscreen_qs_disabled available=true
10-02 00:44:39.536 13653 13653 D ConstraintsHelper: construct key=qs_tile_label_hide available=true
10-02 00:44:39.541 13653 13653 D ConstraintsHelper: construct key=qs_tile_vertical_layout available=true
10-02 00:44:39.550 13653 13653 D ConstraintsHelper: construct key=qs_footer_data_usage available=true
10-02 00:44:39.552 13653 13653 D ConstraintsHelper: construct key=qs_footer_warnings available=true
10-02 00:44:39.554 13653 13653 D ConstraintsHelper: construct key=qs_footer_show_user available=true
10-02 00:44:39.556 13653 13653 D ConstraintsHelper: construct key=qs_footer_show_edit available=true
10-02 00:44:39.558 13653 13653 D ConstraintsHelper: construct key=qs_footer_show_power_menu available=true
10-02 00:44:39.560 13653 13653 D ConstraintsHelper: construct key=qs_footer_show_services available=true
10-02 00:44:39.561 13653 13653 D ConstraintsHelper: construct key=qs_footer_show_settings available=true
10-02 00:44:39.564 13653 13653 D ConstraintsHelper: construct key=notification_material_dismiss available=true
10-02 00:44:39.566 13657 13657 W RecyclerView: No adapter attached; skipping layout
10-02 00:44:39.571 13653 13653 W InstrumentedPrefFrag: Screen title missing for fragment com.crdroid.settings.fragments.QuickSettings
10-02 00:44:39.588 13653 13653 D SettingsActivity: Starting onCreate
10-02 00:44:39.601 13653 13653 D SettingsActivity: Starting to set activity title
10-02 00:44:39.601 13653 13653 D SettingsActivity: Done setting title
10-02 00:44:39.661 13653 16075 D SettingsActivity: No enabled state changed, skipping updateCategory call
10-02 00:44:39.662  6348  6402 W GServicesProxy: No permission to query Gservice flags, exiting!
10-02 00:44:39.666  6348  6402 W GServicesProxy: No permission to query Gservice flags, exiting!
10-02 00:44:39.670  6348  6402 W GServicesProxy: No permission to query Gservice flags, exiting!
10-02 00:44:39.674  6348  6402 W GServicesProxy: No permission to query Gservice flags, exiting!
10-02 00:44:39.680 13653 16075 W TileUtils: Found com.android.settings.Settings$crDroidSettingsLayoutActivity for intent Intent { act=com.android.settings.action.SETTINGS pkg=com.android.settings } missing metadata com.android.settings.category
10-02 00:44:39.689 13657 13657 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
10-02 00:44:39.791  1476  2520 I WindowManager: finishDrawing of relaunch: Window{b98c37b u0 com.android.settings/com.android.settings.SubSettings} 477ms
10-02 00:44:39.826  1476  2523 I WindowManager: finishDrawing of relaunch: Window{be3ed14 u0 com.android.documentsui/com.android.documentsui.files.FilesActivity} 494ms
10-02 00:44:39.827  1476  2523 E LayerState: Unmerged SurfaceComposer Transaction properties. LayerState::merge needs updating? other.what=0x5540573619200 what=0x4441061991432
10-02 00:44:39.848   622   622 I android.hardware.power-service-qti: Power setMode: 5 to: 0
10-02 00:44:39.895  1476  2520 W WindowManager: Cannot find window which accessibility connection is added to
10-02 00:44:39.949  1476  2520 W WindowManager: Cannot find window which accessibility connection is added to
10-02 00:44:39.958  6727  6727 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3280 
10-02 00:44:39.959  6727  6727 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2169 repeatCheckTimes = 0, unlocked = true
10-02 00:44:39.960  6727  6727 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1960 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.android.documentsui fieldId=-1 fieldName=null extras=null}, false)
10-02 00:44:39.960  6727  6727 I GoogleInputMethodService: GoogleInputMethodService.shouldHideHeaderOnInitialState():4081 ShouldHideHeaderOnInitialState = false
10-02 00:44:39.961  6727  6727 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2169 repeatCheckTimes = 2, unlocked = true
10-02 00:44:40.265  2116  2116 D b/223498680: LRV onStateTransitionStart setFreezeVisibility=true, toState=Normal
10-02 00:44:40.266  2116  2116 D b/223498680: BaseRecentsViewStateController setState state=Normal, alpha=0.0
10-02 00:44:40.267  2116  2116 D b/195430732: currentRunningTaskViewId: -1 requestedTaskViewId: -1
10-02 00:44:40.267  2116  2116 D b/223498680: LRV onStateTransitionComplete setFreezeVisibility=false, finalState=Normal
10-02 00:44:41.694  3092 15376 D UsageReportingService: bound by: GetServiceRequest{serviceId=USAGE_REPORTING, gmsVersion=222410000, packageName='com.google.android.apps.turbo', extras=Bundle[{}]}
10-02 00:44:41.696 16445 16478 W GoogleApiManager: aqq could not execute call because it requires feature (usage_and_diagnostics_listener, 1).
10-02 00:44:43.035   622   622 E QTI PowerHAL: Failed to acquire lock.
10-02 00:44:43.188  2116  2116 D b/195430732: currentRunningTaskViewId: -1 requestedTaskViewId: 51
10-02 00:44:43.190  2116  2116 D b/195430732: currentRunningTaskViewId: 51 requestedTaskViewId: 51
10-02 00:44:43.197  2527  2527 V ShadeControllerImpl: NotificationShadeWindow: com.android.systemui.statusbar.phone.NotificationShadeWindowView{bfa7183 I.E...... ......ID 0,0-1080,1920} canPanelBeCollapsed(): false
10-02 00:44:43.199   622   622 I android.hardware.power-service-qti: Power setMode: 5 to: 1
10-02 00:44:43.203   622   622 E QTI PowerHAL: Failed to acquire lock.
10-02 00:44:43.203   622   622 E QTI PowerHAL: Failed to perform launch boost
10-02 00:44:43.218  2116  2116 D b/223498680: LRV onStateTransitionStart setFreezeVisibility=true, toState=Background
10-02 00:44:43.219  2116  2116 D b/223498680: BaseRecentsViewStateController setState state=Background, alpha=1.0
10-02 00:44:43.220  2116  2116 D b/223498680: LRV onStateTransitionComplete setFreezeVisibility=false, finalState=Background
10-02 00:44:43.243  2527  2527 V ShadeControllerImpl: NotificationShadeWindow: com.android.systemui.statusbar.phone.NotificationShadeWindowView{bfa7183 I.E...... ......ID 0,0-1080,1920} canPanelBeCollapsed(): false
10-02 00:44:43.247  2116  2116 I LatencyTracker: ACTION_TOGGLE_RECENTS latency=-1711687
10-02 00:44:43.265  1476  1624 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
10-02 00:44:43.345  1476  2521 I ActivityManager: Process com.customqs.lonshot (pid 11910) has died: cch+75 CEM 
10-02 00:44:43.357  1476  2405 I ActivityManager: Process com.android.providers.calendar (pid 5150) has died: cch+75 CEM 
10-02 00:44:43.357   545   545 I Zygote  : Process 11910 exited due to signal 9 (Killed)
10-02 00:44:43.361   545   545 I Zygote  : Process 5150 exited due to signal 9 (Killed)
10-02 00:44:43.363  1476  1651 I libprocessgroup: Successfully killed process cgroup uid 10254 pid 11910 in 18ms
10-02 00:44:43.364  1476  1651 I libprocessgroup: Successfully killed process cgroup uid 10254 pid 11910 in 0ms
10-02 00:44:43.364  1476  1651 I libprocessgroup: Successfully killed process cgroup uid 10175 pid 5150 in 0ms
10-02 00:44:43.364  1476  1651 I libprocessgroup: Successfully killed process cgroup uid 10175 pid 5150 in 0ms
10-02 00:44:43.564  1476  1645 I LatencyTracker: ACTION_START_RECENTS_ANIMATION latency=63
10-02 00:44:43.637   622   622 I android.hardware.power-service-qti: Power setMode: 5 to: 0
10-02 00:44:43.668  1476  2523 W WindowManager: Cannot find window which accessibility connection is added to
10-02 00:44:43.685  2116  2116 D b/223498680: LRV onStateTransitionStart setFreezeVisibility=true, toState=Overview
10-02 00:44:43.686  2116  2116 D b/223498680: BaseRecentsViewStateController setState state=Overview, alpha=1.0
10-02 00:44:43.688  2116  2116 D b/223498680: LRV onStateTransitionComplete setFreezeVisibility=false, finalState=Overview
10-02 00:44:43.696  1476  2517 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:10235?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
10-02 00:44:43.696  2116  2430 D QuickstepModelDelegate: notifyAppTargetEvent action=1 launchLocation=
10-02 00:44:43.710  6727  6727 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3280 
10-02 00:44:43.712  6727  6727 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2169 repeatCheckTimes = 0, unlocked = true
10-02 00:44:43.712  6727  6727 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1960 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.android.launcher3 fieldId=-1 fieldName=null extras=null}, false)
10-02 00:44:43.712  6727  6727 I GoogleInputMethodService: GoogleInputMethodService.shouldHideHeaderOnInitialState():4081 ShouldHideHeaderOnInitialState = false
10-02 00:44:43.713  6727  6727 I GoogleInputMethodService: GoogleInputMethodService.updateDeviceLockedStatus():2169 repeatCheckTimes = 2, unlocked = true
10-02 00:44:43.733  1476  2521 W WindowManager: Failed looking up window session=Session{66817ef 2527:u0a10237} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5779 com.android.server.wm.WindowManagerService.removeWindow:2051 com.android.server.wm.Session.remove:218 
10-02 00:44:43.733  1476  2521 W InputManager-JNI: Input channel object 'EmbeddedWindow{ u0 Internal} (client)' was disposed without first being removed with the input manager!
10-02 00:44:43.738  1476  2523 W WindowManager: Cannot find window which accessibility connection is added to
10-02 00:44:43.792  1476  2523 W WindowManager: Failed looking up window session=Session{66817ef 2527:u0a10237} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5779 com.android.server.wm.WindowManagerService.removeWindow:2051 com.android.server.wm.Session.remove:218 
10-02 00:44:43.792  1476  2523 W InputManager-JNI: Input channel object 'EmbeddedWindow{ u0 Internal} (client)' was disposed without first being removed with the input manager!
10-02 00:44:43.795  1476  2521 W WindowManager: Cannot find window which accessibility connection is added to
10-02 00:44:43.841  1476  2523 W WindowManager: Failed looking up window session=Session{66817ef 2527:u0a10237} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5779 com.android.server.wm.WindowManagerService.removeWindow:2051 com.android.server.wm.Session.remove:218 
10-02 00:44:43.841  1476  2523 W InputManager-JNI: Input channel object 'EmbeddedWindow{ u0 Internal} (client)' was disposed without first being removed with the input manager!
10-02 00:44:43.846  1476  2523 I WindowOrganizerController: reparentChildrenTasksHierarchyOp currentParent=Task{3bdf4e2 #8 type=standard ?? U=0 visible=false visibleRequested=false mode=multi-window translucent=true sz=1} newParent=DefaultTaskDisplayArea@71001609 hop={ChildrenTasksReparent: from=RemoteToken{56e3b5e Task{3bdf4e2 #8 type=standard ?? U=0 visible=false visibleRequested=false mode=multi-window translucent=true sz=1}} to=null mToTop=false mReparentTopOnly=false mWindowingMode=[1, 0, 6] mActivityType=[1]}
10-02 00:44:43.846  1476  2523 I WindowOrganizerController:  Processing task=Task{ef866e7 #34 type=standard A=10166:com.android.documentsui U=0 rootTaskId=8 visible=false visibleRequested=false mode=multi-window translucent=true sz=1}
10-02 00:44:43.846  1476  2523 I WindowOrganizerController:  Processing task=Task{3bdf4e2 #8 type=standard ?? U=0 visible=false visibleRequested=false mode=multi-window translucent=true sz=1}
10-02 00:44:43.851  1476  2523 I WindowOrganizerController: reparentChildrenTasksHierarchyOp currentParent=Task{986b9ad #7 type=standard ?? U=0 visible=false visibleRequested=false mode=multi-window translucent=true sz=1} newParent=DefaultTaskDisplayArea@71001609 hop={ChildrenTasksReparent: from=RemoteToken{c625c99 Task{986b9ad #7 type=standard ?? U=0 visible=false visibleRequested=false mode=multi-window translucent=true sz=1}} to=null mToTop=false mReparentTopOnly=false mWindowingMode=[1, 0, 6] mActivityType=[1]}
10-02 00:44:43.851  1476  2523 I WindowOrganizerController:  Processing task=Task{4b6e44 #32 type=standard A=1000:com.android.settings.root U=0 rootTaskId=7 visible=false visibleRequested=false mode=multi-window translucent=true sz=2}
10-02 00:44:43.851  1476  2523 I WindowOrganizerController:  Processing task=Task{986b9ad #7 type=standard ?? U=0 visible=false visibleRequested=false mode=multi-window translucent=true sz=1}
10-02 00:44:43.851  1476  2521 W InputDispatcher: EmbeddedWindow{ u0 Internal} has FLAG_SLIPPERY. Please report this in b/157929241
10-02 00:44:43.860  2527  2548 I StageCoordinator: applyExitSplitScreen, reason = RETURN_HOME
10-02 00:44:43.976  1476  1526 I system_server: NativeAlloc concurrent copying GC freed 520533(24MB) AllocSpace objects, 24(1992KB) LOS objects, 66% free, 22MB/66MB, paused 256us,230us total 369.493ms
```

### Screenshots or videos

![Screenshot_20221002-002232_Settings](https://user-images.githubusercontent.com/67532153/193429009-28a5957d-6e52-449f-a2df-afd893b21d14.png)
![Screenshot_20221002-002242_Settings](https://user-images.githubusercontent.com/67532153/193429012-00e28d81-1a55-4eca-9d11-167af7bc7743.png)
![Screenshot_20221002-002357_Settings](https://user-images.githubusercontent.com/67532153/193429014-176f897d-3d06-4f7a-a7ca-e81de330b0f3.png)
![Screenshot_20221002-002706_crDroid Home](https://user-images.githubusercontent.com/67532153/193429022-7812dc6c-ae85-4fc1-b774-4619e271c5fa.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
can't reproduce here
unfortunately mido is also retired device with last update 7.15 and no official crDroid 8
https://crdroid.net/mido/7
