### ISSUE TITLE
bug: SystemUI crash when tapping the internet tile in QS

### ISSUE THREAD

**Issue by yonatan8070** [crdroidandroid/issue_tracker#122]
### Issue type

Source code related

### Device

Alioth

### crDroid version

crDroid 9.1

### Exact version / Build date

Android 13, crDroid 9.1/2023-02-04

### Bug description

Sometimes tapping the Internet QS tile causes SystemUI to crash and show the lock screen once it starts back up.
Unfortunately I can't reproduce it on-demand so I don't have a screen capture of it.

### Steps to reproduce

1. Pull down Notification panel or QS panel
2. Tap the Internet tile

### Relevant log (logcat/build log)

```shell
02-07 16:14:22.601  2326  2326 E AndroidRuntime: FATAL EXCEPTION: main
02-07 16:14:22.601  2326  2326 E AndroidRuntime: Process: com.android.systemui, PID: 2326
02-07 16:14:22.601  2326  2326 E AndroidRuntime: android.net.ConnectivityManager$TooManyRequestsException
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4008)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4197)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4726)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4693)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4667)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at com.android.systemui.qs.tiles.dialog.InternetDialog.onStart(InternetDialog.java:145)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:333)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at com.android.systemui.animation.DialogLaunchAnimator.showFromView(DialogLaunchAnimator.kt:509)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at com.android.systemui.qs.tiles.dialog.InternetDialogFactory.create(InternetDialogFactory.kt:53)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at com.android.systemui.tuner.NavBarTuner$$ExternalSyntheticLambda6.run(R8$$SyntheticClass:146)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-07 16:14:22.601  2326  2326 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
do you also have network traffic enabled?

**Comment by yonatan8070** [comment]
Yes, I have the network traffic icon + text enabled on both the status bar and QS

**Comment by zhmars** [comment]
Same issue on my device (lavender / crDroid 9.1 / 2023-02-10).

> do you also have network traffic enabled?

No.

```
02-18 15:24:15.352 W/OnBackInvokedCallback(2306): OnBackInvokedCallback is not enabled for the application.
02-18 15:24:15.352 W/OnBackInvokedCallback(2306): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
02-18 15:24:15.352 D/CentralSurfaces(2306): Received new disable state: enaihbcrso.qingr (unchanged)
02-18 15:24:15.372 E/OpenGLRenderer(2306): Unable to match the desired swap behavior.
02-18 15:24:15.555 E/TARE-IRS(1638): Don't have packages for uid 90029
02-18 15:24:15.567 D/CentralSurfaces(2306): Received new disable state: enaihbcrso.qingr (unchanged)
02-18 15:24:15.603 W/View    (2306): requestLayout() improperly called by StatusBarIconView(slot='mobile alpha=1.0 icon=null iconColor=#0 notification=null) during layout: running second layout pass
02-18 15:24:15.603 W/View    (2306): requestLayout() improperly called by StatusBarIconView(slot='mobile alpha=1.0 icon=null iconColor=#0 notification=null) during layout: running second layout pass
02-18 15:24:16.588 D/AndroidRuntime(2306): Shutting down VM
02-18 15:24:16.589 E/AndroidRuntime(2306): FATAL EXCEPTION: main
02-18 15:24:16.589 E/AndroidRuntime(2306): Process: com.android.systemui, PID: 2306
02-18 15:24:16.589 E/AndroidRuntime(2306): android.net.ConnectivityManager$TooManyRequestsException
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:4008)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4197)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4726)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4693)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4667)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at com.android.systemui.qs.tiles.dialog.InternetDialog.onStart(InternetDialog.java:145)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.app.Dialog.show(Dialog.java:333)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at com.android.systemui.animation.DialogLaunchAnimator.showFromView(DialogLaunchAnimator.kt:509)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at com.android.systemui.qs.tiles.dialog.InternetDialogFactory.create(InternetDialogFactory.kt:53)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at com.android.systemui.tuner.NavBarTuner$$ExternalSyntheticLambda6.run(R8$$SyntheticClass:146)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.os.Handler.handleCallback(Handler.java:942)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.os.Looper.loopOnce(Looper.java:201)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.os.Looper.loop(Looper.java:288)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at java.lang.reflect.Method.invoke(Native Method)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-18 15:24:16.589 E/AndroidRuntime(2306): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
02-18 15:24:16.590 I/BufferEulogizer(2306): Performing emergency dump of log buffers
```

**Comment by ShevT** [comment]
https://github.com/crdroidandroid/android_frameworks_base/commit/4e8d719587b7121048f98d3d58c9fecf1fc3a5dd
