### ISSUE TITLE
System Freeze & Black Screen Stuck

### ISSUE THREAD

**Issue by Avnesh007** [crdroidandroid/issue_tracker#131]
### Issue type

User interface

### Device

Beryllium

### crDroid version

crDroid 9

### Exact version / Build date

9.1/20230211

### Bug description

I were just deleting some media & images in stock gallery, device stucked & black screen appearing. Faced again issue related to system ui & this is not normal bcz suddenly device got unusable. I captured log of this issue & attaching here. Plz look it if u have free time.

### Steps to reproduce

just connect with pc & take log because device was stucked.

### Relevant log (logcat/build log)

```shell
02-12 15:31:16.883  2193  5089 E AndroidRuntime: FATAL EXCEPTION: thread-event-receiver
02-12 15:31:16.883  2193  5089 E AndroidRuntime: Process: com.msf.kbank.mobile, PID: 2193
02-12 15:31:16.883  2193  5089 E AndroidRuntime: java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
02-12 15:31:16.883  2193  5089 E AndroidRuntime: 	at androidx.work.impl.j.p(SourceFile:9)
02-12 15:31:16.883  2193  5089 E AndroidRuntime: 	at androidx.work.s.h(SourceFile:1)
02-12 15:31:16.883  2193  5089 E AndroidRuntime: 	at xxxxx.m1.<init>(SourceFile:2)
02-12 15:31:16.883  2193  5089 E AndroidRuntime: 	at xxxxx.g1.<init>(SourceFile:2)
02-12 15:31:16.883  2193  5089 E AndroidRuntime: 	at xxxxx.h3.invoke(SourceFile:3)
02-12 15:31:16.883  2193  5089 E AndroidRuntime: 	at xxxxx.k2.a(SourceFile:2)
02-12 15:31:16.883  2193  5089 E AndroidRuntime: 	at xxxxx.u0$a.a(SourceFile:1)
02-12 15:31:16.883  2193  5089 E AndroidRuntime: 	at com.cv.sdk.receiver.EventReceiver$a.invoke(SourceFile:2)
02-12 15:31:16.883  2193  5089 E AndroidRuntime: 	at kotlin.concurrent.a$a.run(SourceFile:1)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: FATAL EXCEPTION: main
02-12 15:31:46.769  6437  6437 E AndroidRuntime: Process: com.fss.iob6, PID: 6437
02-12 15:31:46.769  6437  6437 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.cowbell.cordova.geofence.BootReceiver: java.lang.IllegalArgumentException: com.fss.iob6: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
02-12 15:31:46.769  6437  6437 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4315)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: com.fss.iob6: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
02-12 15:31:46.769  6437  6437 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:750)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.app.PendingIntent.getService(PendingIntent.java:712)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at com.cowbell.cordova.geofence.GeoNotificationManager.getTransitionPendingIntent(GeoNotificationManager.java:113)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at com.cowbell.cordova.geofence.GeoNotificationManager.<init>(GeoNotificationManager.java:31)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at com.cowbell.cordova.geofence.BootReceiver.onReceive(BootReceiver.java:12)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4306)
02-12 15:31:46.769  6437  6437 E AndroidRuntime: 	... 9 more
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this should be fixed with latest 9.2 release from 2023-02-26
can confirm?
