### ISSUE TITLE
bug: App overview from Pixel Launcher missbehaving

### ISSUE THREAD

**Issue by SirLouen** [crdroidandroid/issue_tracker#158]
### Issue type

User interface

### Device

Pocophone F1 (Beryllium)

### crDroid version

crDroid 9

### Exact version / Build date

9.3 2022-04-01

### Bug description

When I want to switch an app through App Overview gesture, it doesn't stick and if I open the App Overview (slide up from bottom) nothing appears (despite multiple apps running already).
Sometimes, not always, an error appear, I attach the log of such error

### Steps to reproduce

Slide up from the bottom of the screen with gestures, or pressing the app overview soft button

### Relevant log (logcat/build log)

```shell
ime: 1680514433686
msg: java.lang.UnsupportedOperationException: Can't convert value at index 0 to color: type=0x1, theme={InheritanceMap=[id=0x7f140014com.google.android.apps.nexuslauncher:style/AppTheme.Dark.DarkMainColor, id=0x7f140146com.google.android.apps.nexuslauncher:style/LauncherTheme.Dark.DarkMainColor, id=0x7f140145com.google.android.apps.nexuslauncher:style/LauncherTheme.Dark, id=0x7f140144com.google.android.apps.nexuslauncher:style/LauncherTheme, id=0x7f140126com.google.android.apps.nexuslauncher:style/BaseLauncherTheme, id=0x10302e3android:style/Theme.DeviceDefault.DayNight, id=0x1030128android:style/Theme.DeviceDefault, id=0x1030403android:style/Theme.DeviceDefaultBase, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[com.google.android.apps.nexuslauncher:style/AppTheme.Dark.DarkMainColor, forced, com.google.android.apps.nexuslauncher:style/AppTheme, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
stacktrace: java.lang.UnsupportedOperationException: Can't convert value at index 0 to color: type=0x1, theme={InheritanceMap=[id=0x7f140014com.google.android.apps.nexuslauncher:style/AppTheme.Dark.DarkMainColor, id=0x7f140146com.google.android.apps.nexuslauncher:style/LauncherTheme.Dark.DarkMainColor, id=0x7f140145com.google.android.apps.nexuslauncher:style/LauncherTheme.Dark, id=0x7f140144com.google.android.apps.nexuslauncher:style/LauncherTheme, id=0x7f140126com.google.android.apps.nexuslauncher:style/BaseLauncherTheme, id=0x10302e3android:style/Theme.DeviceDefault.DayNight, id=0x1030128android:style/Theme.DeviceDefault, id=0x1030403android:style/Theme.DeviceDefaultBase, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[com.google.android.apps.nexuslauncher:style/AppTheme.Dark.DarkMainColor, forced, com.google.android.apps.nexuslauncher:style/AppTheme, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.content.res.TypedArray.getColor(TypedArray.java:535)
	at com.android.launcher3.icons.GraphicsUtils.getAttrColor(Unknown Source:10)
	at com.android.launcher3.util.Themes.getAttrColor(Unknown Source:0)
	at J1.A.W(Unknown Source:61)
	at J1.A.initOverlay(Unknown Source:346)
	at com.android.quickstep.views.TaskThumbnailView.refreshOverlay(Unknown Source:24)
	at com.android.quickstep.views.TaskThumbnailView.setOverlayEnabled(Unknown Source:6)
	at com.android.quickstep.views.TaskView.setOverlayEnabled(Unknown Source:2)
	at com.android.quickstep.views.RecentsView.updateEnabledOverlays(Unknown Source:25)
	at com.android.quickstep.views.RecentsView.setOverlayEnabled(Unknown Source:6)
	at com.android.quickstep.views.LauncherRecentsView.onStateTransitionComplete(SourceFile:5)
	at com.android.quickstep.views.LauncherRecentsView.onStateTransitionComplete(SourceFile:1)
	at com.android.launcher3.statemanager.StateManager.onStateTransitionEnd(Unknown Source:43)
	at com.android.launcher3.statemanager.StateManager.goToState(SourceFile:18)
	at com.android.launcher3.statemanager.StateManager.goToState(SourceFile:2)
	at com.android.quickstep.BaseActivityInterface$DefaultAnimationFactory.lambda$createActivityInterface$0(Unknown Source:29)
	at com.android.quickstep.BaseActivityInterface$DefaultAnimationFactory.a(Unknown Source:0)
	at com.android.quickstep.n0.run(Unknown Source:4)
	at com.android.launcher3.anim.AnimatorPlaybackController$OnAnimationEndDispatcher.onAnimationSuccess(Unknown Source:23)
	at com.android.launcher3.anim.AnimationSuccessListener.onAnimationEnd(Unknown Source:4)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1333)
	at android.animation.ValueAnimator.end(ValueAnimator.java:1235)
	at com.android.quickstep.AbsSwipeUpHandler.endLauncherTransitionController(Unknown Source:29)
	at com.android.quickstep.AbsSwipeUpHandler.setupLauncherUiAfterSwipeUpToRecentsAnimation(Unknown Source:11)
	at com.android.quickstep.AbsSwipeUpHandler.m(Unknown Source:0)
	at com.android.quickstep.i.run(Unknown Source:2)
	at com.android.quickstep.MultiStateCallback.setState(Unknown Source:56)
	at com.android.quickstep.MultiStateCallback.setStateOnUiThread(Unknown Source:10)
	at com.android.quickstep.AbsSwipeUpHandler.finishCurrentTransitionToRecents(Unknown Source:13)
	at com.android.quickstep.AbsSwipeUpHandler.L(Unknown Source:0)
	at com.android.quickstep.x.run(Unknown Source:2)
	at com.android.quickstep.MultiStateCallback.setState(Unknown Source:56)
	at com.android.quickstep.MultiStateCallback.setStateOnUiThread(Unknown Source:10)
	at com.android.quickstep.AbsSwipeUpHandler.setScreenshotCapturedState(Unknown Source:13)
	at com.android.quickstep.AbsSwipeUpHandler.lambda$switchToScreenshot$21(Unknown Source:8)
	at com.android.quickstep.AbsSwipeUpHandler.g(Unknown Source:0)
	at com.android.quickstep.F.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
```

### Screenshots or videos

https://i.imgur.com/try0YxD.mp4

### Additional context

On crDroid 9.2 it worked fine, it started with crDroid 9.3

Using latest NikGApps

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by SirLouen** [comment]
I've found that when I click on the Wallapaper and style also throws an error

```
time: 1680515262151
msg: java.lang.UnsupportedOperationException: Can't convert value at index 0 to color: type=0x1, theme={InheritanceMap=[id=0x7f130123com.google.android.apps.wallpaper:style/CustomizationTheme.NoActionBar, id=0x7f130122com.google.android.apps.wallpaper:style/CustomizationTheme, id=0x1030223android:style/Theme.DeviceDefault.Settings, id=0x1030128android:style/Theme.DeviceDefault, id=0x1030403android:style/Theme.DeviceDefaultBase, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[com.google.android.apps.wallpaper:style/CustomizationTheme.NoActionBar, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.apps.wallpaper/com.android.wallpaper.picker.CustomizationPickerActivity}: android.view.InflateException: Binary XML file line #29 in com.google.android.apps.wallpaper:layout/activity_customization_picker: Binary XML file line #16 in com.google.android.apps.wallpaper:layout/bottom_action_bar: Error inflating class com.android.wallpaper.widget.BottomActionBar
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3641)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
Caused by: android.view.InflateException: Binary XML file line #29 in com.google.android.apps.wallpaper:layout/activity_customization_picker: Binary XML file line #16 in com.google.android.apps.wallpaper:layout/bottom_action_bar: Error inflating class com.android.wallpaper.widget.BottomActionBar
Caused by: android.view.InflateException: Binary XML file line #16 in com.google.android.apps.wallpaper:layout/bottom_action_bar: Error inflating class com.android.wallpaper.widget.BottomActionBar
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:863)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1245)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:470)
	at android.app.Activity.setContentView(Activity.java:3610)
	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:2)
	at com.android.wallpaper.picker.CustomizationPickerActivity.onCreate(CustomizationPickerActivity.java:84)
	at android.app.Activity.performCreate(Activity.java:8359)
	at android.app.Activity.performCreate(Activity.java:8338)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
Caused by: android.content.res.Resources$NotFoundException: File res/color/bottom_action_button_color_tint.xml from ComplexColor resource ID #0x7f060024
	at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1174)
	at android.content.res.ResourcesImpl.loadComplexColorFromName(ResourcesImpl.java:1000)
	at android.content.res.ResourcesImpl.loadColorStateList(ResourcesImpl.java:1079)
	at android.content.res.Resources.getColorStateList(Resources.java:1145)
	at android.content.Context.getColorStateList(Context.java:827)
	at com.android.wallpaper.widget.BottomActionBar.setColor(BottomActionBar.java:61)
	at com.android.wallpaper.widget.BottomActionBar.<init>(BottomActionBar.java:215)
	... 30 more
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 0 to color: type=0x1, theme={InheritanceMap=[id=0x7f130123com.google.android.apps.wallpaper:style/CustomizationTheme.NoActionBar, id=0x7f130122com.google.android.apps.wallpaper:style/CustomizationTheme, id=0x1030223android:style/Theme.DeviceDefault.Settings, id=0x1030128android:style/Theme.DeviceDefault, id=0x1030403android:style/Theme.DeviceDefaultBase, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[com.google.android.apps.wallpaper:style/CustomizationTheme.NoActionBar, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.content.res.TypedArray.getColor(TypedArray.java:535)
	at android.content.res.ColorStateList.inflate(ColorStateList.java:368)
	at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:298)
	at android.content.res.ResourcesImpl.loadComplexColorForCookie(ResourcesImpl.java:1167)
	... 36 more
```

**Comment by SirLouen** [comment]
I've done a clean install. I've heard that Pixel Launcher is not a good friend of  crDroid, so I've decided to reinstall from scratch without Pixel Launcher by default from NikkGApps. 

Closing this bug.
