### ISSUE TITLE
bug: Can't take home as well with taskbar

### ISSUE THREAD

**Issue by Myst-arch** [crdroidandroid/issue_tracker#173]
### Issue type

User interface

### Device

Redmi Note 8 Pro (Begonia)

### crDroid version

crDroid 9

### Exact version / Build date

9.3/2023-04-08

### Bug description

When i want to hide the taskbar or go home it will be stuck a second and gone and back appear again and poping up a bug report

### Steps to reproduce

Basically, just hold tap the taskbar to hide it or swipe up to go home

### Relevant log (logcat/build log)

```shell
time: 1681719146829
msg: java.lang.NullPointerException: Attempt to write to field 'boolean com.android.launcher3.DropTarget$DragObject.deferDragViewCleanupPostAnimation' on a null object reference in method 'void com.android.launcher3.taskbar.TaskbarDragController.endDrag()'
stacktrace: java.lang.NullPointerException: Attempt to write to field 'boolean com.android.launcher3.DropTarget$DragObject.deferDragViewCleanupPostAnimation' on a null object reference in method 'void com.android.launcher3.taskbar.TaskbarDragController.endDrag()'
	at com.android.launcher3.taskbar.TaskbarDragController.endDrag(TaskbarDragController.java:468)
	at com.android.launcher3.dragndrop.DragController.cancelDrag(DragController.java:274)
	at com.android.launcher3.dragndrop.DragController.onControllerInterceptTouchEvent(DragController.java:411)
	at com.android.launcher3.views.BaseDragLayer.findControllerToHandleTouch(BaseDragLayer.java:182)
	at com.android.launcher3.views.BaseDragLayer.findActiveController(BaseDragLayer.java:192)
	at com.android.launcher3.views.BaseDragLayer.onInterceptTouchEvent(BaseDragLayer.java:162)
	at com.android.launcher3.taskbar.TaskbarDragLayer.onInterceptTouchEvent(TaskbarDragLayer.java:123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2653)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:299)
	at com.android.launcher3.taskbar.TaskbarDragLayer.dispatchTouchEvent(TaskbarDragLayer.java:189)
	at android.view.View.dispatchPointerEvent(View.java:15269)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6762)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6562)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6013)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6070)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6036)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6201)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6044)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6258)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6017)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6070)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6036)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6044)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6017)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9115)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9066)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9035)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9238)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7896)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
```

### Screenshots or videos

https://user-images.githubusercontent.com/51075953/232436531-3570cea8-7353-4c41-9181-6e47300910dc.mp4

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@DarkJoker360 do check please
