### ISSUE TITLE
bug: Wallpapers & Styles app crashes when setting live wallpaper

### ISSUE THREAD

**Issue by fitz1117** [crdroidandroid/issue_tracker#174]
### Issue type

User interface

### Device

Xiaomi MI9 (cepheus)

### crDroid version

crDroid 9

### Exact version / Build date

9.4/2023-04-19（The previous Crd9.x version also had this problem）

### Bug description

Set the live wallpaper through the Wallpapers & Styles app, and the app crashes when you click on a certain live wallpaper

### Steps to reproduce

step 1. Go to settings
step 2. Go to Wallpapers & Styles
step 3. Choose change wallpaper
Step 4. Choose live wallpaper
Choose any live wallpaper and it will crash

### Relevant log (logcat/build log)

```shell
time: 1681840292135
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
	at com.android.wallpaper.picker.PreviewFragment.onCreate(PreviewFragment.java:156)
	at com.android.wallpaper.picker.LivePreviewFragment.onCreate(LivePreviewFragment.java:128)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3009)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1780)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2919)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2832)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:417)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:247)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1549)
	at android.app.Activity.performStart(Activity.java:8384)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3676)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7896)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
```

### Screenshots or videos

https://user-images.githubusercontent.com/128229300/232864144-b1cd20f0-a41c-4a1b-84a3-f1aec7b806e3.mp4

### Solution

I downloaded the wallpaper app (https://play.google.com/store/apps/details?id=com.google.android.apps.wallpaper) through Google play, this wallpaper app can set live wallpaper

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by way2harshraj090** [comment]
I am facing same issue.
Device- veux

**Comment by gwolf2u** [comment]
this was fixed
