### ISSUE TITLE
bug: updater crashes when trying to update

### ISSUE THREAD

**Issue by Minionflo** [crdroidandroid/issue_tracker#197]
### Issue type

Feature not working as intended

### Device

veux

### crDroid version

crDroid 9

### Exact version / Build date

9.4/2023-4-24

### Bug description

When trying to update with "Prioritise update process" the updater crashes with the error "android.os.ServiceSpecificException: Could not change profiles"

### Steps to reproduce

1. Open Settings -> System -> Updater
2. Click on the three point in the upper right corner
3. Turn on "Prioritise update process"
4. Try to update

### Relevant log (logcat/build log)

```shell
time: 1686656453238
msg: android.os.ServiceSpecificException: Could not change profiles
stacktrace: java.lang.RuntimeException: Unable to start service com.crdroid.updater.controller.UpdaterService@8d99a91 with Intent { act=action_install_update cmp=com.crdroid.updater/.controller.UpdaterService (has extras) }: android.os.ServiceSpecificException: Could not change profiles (code 1)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4682)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7896)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: android.os.ServiceSpecificException: Could not change profiles (code 1)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3042)
	at android.os.Parcel.createException(Parcel.java:3012)
	at android.os.Parcel.readException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2937)
	at android.os.IUpdateEngine$Stub$Proxy.setPerformanceMode(IUpdateEngine.java:617)
	at android.os.UpdateEngine.setPerformanceMode(UpdateEngine.java:469)
	at com.crdroid.updater.controller.ABUpdateInstaller.install(ABUpdateInstaller.java:212)
	at com.crdroid.updater.controller.ABUpdateInstaller.install(ABUpdateInstaller.java:162)
	at com.crdroid.updater.controller.UpdaterService.onStartCommand(UpdaterService.java:205)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4664)
	... 9 more
```

### Solution

Turn off "Prioritise update process"

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is fixed
