### ISSUE TITLE
bug: system ui crashed

### ISSUE THREAD

**Issue by kanishk-upadhyay** [crdroidandroid/issue_tracker#231]
### Issue type

Source code related

### Device

Realme x7 max (rmx3031)

### crDroid version

crDroid 9

### Exact version / Build date

9.8/2023-08-17

### Bug description

system ui crashed

### Steps to reproduce

came across randomly

### Relevant log (logcat/build log)

```shell
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: realme
[Device Model]: Realme X7 Max 5G
[Display]: TQ3A.230805.001 release-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_IN
[Process ID]: 2026
[CPU ABI]: none
[Package Name]: com.android.systemui
[Version Name]: 13
[Version Code]: 33
[Error Type]: JVM
[Crash Time]: 2023-08-28T01:11:43.101
[Stack Trace]:
java.lang.NoSuchMethodError: com.android.systemui.statusbar.policy.Clock#updateClock()
	at de.robv.android.xposed.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at de.robv.android.xposed.XposedHelpers.f(Unknown Source:0)
	at de.robv.android.xposed.d.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(Unknown Source:30)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(Unknown Source:4)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:4)
	at sh.siava.AOSPMods.modpacks.systemui.StatusbarMods.lambda$updateClock$0$sh-siava-AOSPMods-modpacks-systemui-StatusbarMods(StatusbarMods.java:475)
	at sh.siava.AOSPMods.modpacks.systemui.StatusbarMods$$ExternalSyntheticLambda4.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7936)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DarkJoker360** [comment]
This crash is coming from the mods you have installed: Xposed/LSPosed and AOSPMods.
