### ISSUE TITLE
bug: system ui crash

### ISSUE THREAD

**Issue by kanishk-upadhyay** [crdroidandroid/issue_tracker#235]
### Issue type

Source code related

### Device

Realme x7 max (rmx3031)

### crDroid version

crDroid 9

### Exact version / Build date

9.8/2023-08-17

### Bug description

system ui crashed

### Steps to reproduce

happened suddenly 

### Relevant log (logcat/build log)

```shell
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: realme
[Device Model]: Realme X7 Max 5G
[Display]: TQ3A.230805.001 release-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_IN
[Process ID]: 1947
[CPU ABI]: none
[Package Name]: com.android.systemui
[Version Name]: 13
[Version Code]: 33
[Error Type]: JVM
[Crash Time]: 2023-08-29T19:03:21.783
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.server.wm.ActivityRecord com.android.server.wm.WindowContainer.getTopMostActivity()' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3034)
	at android.os.Parcel.createException(Parcel.java:3012)
	at android.os.Parcel.readException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2937)
	at android.window.IBackNaviAnimationController$Stub$Proxy.finish(IBackNaviAnimationController.java:126)
	at com.android.wm.shell.back.BackAnimationController.finishAnimation(BackAnimationController.java:120)
	at com.android.wm.shell.back.BackAnimationController.onGestureFinished(BackAnimationController.java:156)
	at com.android.wm.shell.back.BackAnimationController$BackAnimationImpl$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:256)
	at com.android.wm.shell.common.HandlerExecutor.execute(HandlerExecutor.java:12)
	at com.android.wm.shell.back.BackAnimationController$BackAnimationImpl.onBackMotion(BackAnimationController.java:15)
	at com.android.systemui.navigationbar.gestural.EdgeBackGestureHandler.dispatchToBackAnimation(EdgeBackGestureHandler.java:20)
	at com.android.systemui.navigationbar.gestural.EdgeBackGestureHandler$$ExternalSyntheticLambda3.onInputEvent(R8$$SyntheticClass:733)
	at com.android.systemui.shared.system.InputChannelCompat$InputEventReceiver$1.onInputEvent(InputChannelCompat.java:2)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7936)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.TaskSnapshotController.getSnapshotMode(TaskSnapshotController.java:558)
	at com.android.server.wm.TaskSnapshotController.captureTaskSnapshot(TaskSnapshotController.java:212)
	at com.android.server.wm.TaskSnapshotController.recordTaskSnapshot(TaskSnapshotController.java:231)
	at com.android.server.wm.BackNaviAnimationController$1.lambda$finish$0(BackNaviAnimationController.java:99)
	at com.android.server.wm.BackNaviAnimationController$1.$r8$lambda$AlgTn3H_08u0NRKJVHEVnJdP1os(Unknown Source:0)
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
duplicate https://github.com/crdroidandroid/issue_tracker/issues/237
