### ISSUE TITLE
bug: can't turn off Launcher random messages

### ISSUE THREAD

**Issue by PycmShoma** [crdroidandroid/issue_tracker#256]
### Issue type

User Interface 

### Device

Xiaomi Mi 9 (Cepheus)

### crDroid version

crDroid 9.9

### Exact version / Build date

crDroid 9.9 Fri Sep 29 11:31:53 CEST 2023

### Bug description

When you turn off the function to show random messages on the At Glance widget, they continue to be displayed

### Steps to reproduce

Go to crDroid Home Settings > Home Screen > Quickspace > Random messages > Turn off

### Relevant log (logcat/build log)

```shell
Process: com.android.launcher3
PID: 11356
UID: 10261
Frozen: false
Flags: 0x34cbbe45
Package: com.android.launcher3 v33 (13)
Foreground: Yes
Process-Runtime: 1986063
Build: Xiaomi/cepheus/cepheus:13/TQ3A.230901.001/1695980001:user/release-keys
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
	at com.android.launcher3.quickspace.QuickSpaceView.loadDoubleLine(QuickSpaceView.java:103)
	at com.android.launcher3.quickspace.QuickSpaceView.onDataUpdated(QuickSpaceView.java:96)
	at com.android.launcher3.quickspace.QuickspaceController$2.run(QuickspaceController.java:237)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7936)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
```

### Screenshots or videos

![Screenshot_20231005-001919_crDroid Home](https://github.com/crdroidandroid/issue_tracker/assets/6963578/fd0c62f5-550a-4f67-bd87-6a8757e140e8)
![Screenshot_20231005-001928_crDroid Home](https://github.com/crdroidandroid/issue_tracker/assets/6963578/2d0b8342-c5ec-49de-9f93-3f58fae45b62)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by PycmShoma** [comment]
R

**Comment by PycmShoma** [comment]
Solve description

**Comment by neobuddy89** [comment]
Please check on 9,12 or 10.0 and report .
