### ISSUE TITLE
bug: App Drawer Search Tab Force Close on Searches

### ISSUE THREAD

**Issue by MellwCrushn** [crdroidandroid/issue_tracker#281]
### Issue type

Feature not working as intended

### Device

Hotdogg
aka OP7TPro McLaren 
T-Mobile variant

### crDroid version

crDroid 9

### Exact version / Build date

November 15, 2023
Android 13
CrDroid 9.11

### Bug description

Used the search tab on the app drawer pull down feature and tried searching for a different items in the settings menu by typing in the word. When I went to click on anything that was listed under "from my apps"  the pull down drawer would force close every time. 

### Steps to reproduce

Step 1: swipe up from the bottom of the phone bringing up the app drawer.

Step 2: type update or gesture or any settings related word into the search bar. 

Step 3: select an option that shows up under the "From Your Apps" section.

Step 4: The force close happens. 

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/gZwOMr

Sorry it pasted weird despite a straight C&P. I've included the link above in case the details below don't suffice. 

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
time: 1701842065356
msg: java.lang.SecurityException: Search result intents must be called with from an allowlisted package.
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.search.SearchResultTrampoline}: java.lang.SecurityException: Search result intents must be called with from an allowlisted package.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3655)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: java.lang.SecurityException: Search result intents must be called with from an allowlisted package.
	at com.android.settings.search.SearchFeatureProviderImpl.verifyLaunchSearchResultPageCaller(SearchFeatureProviderImpl.java:53)
	at com.android.settings.search.SearchResultTrampoline.onCreate(SearchResultTrampoline.java:58)
	at android.app.Activity.performCreate(Activity.java:8360)
	at android.app.Activity.performCreate(Activity.java:8339)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3636)
	... 12 more
```

### Screenshots or videos

![Screenshot_20231205-235446_Pixel Launcher](https://github.com/crdroidandroid/issue_tracker/assets/96168519/bfb757e7-953e-40da-94fc-39f9c69580af)

### Solution

No solution yet

### Additional context

I tried to search for the issue but I could not find the same or similar issue on the GitHub page. 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DarkJoker360** [comment]
Hello, can u please check and report if the problem persists on [latest build](https://sourceforge.net/projects/crdroid/files/hotdogg/9.x/crDroidAndroid-13.0-20231213-hotdogg-v9.12.zip/download)?

**Comment by gwolf2u** [comment]
hotdogg support has been dropped in crDroid 9
