### ISSUE TITLE
Crdroid Launcher crash when using gapps stubs

### ISSUE THREAD

**Issue by guigitignore** [crdroidandroid/issue_tracker#286]
### Issue type

Feature not working as intended

### Device

sweet

### crDroid version

crDroid 10

### Exact version / Build date

10.0

### Bug description

When I am using fake google search bar to use android auto, the launcher restart itself automatically and crash until I disable the fake google search bar.

### Steps to reproduce

-install this module and activate gapps search bar stub: https://github.com/sn-00-x/aa4mg
-restart device

### Relevant log (logcat/build log)

```shell
time: 1702293202463
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.addFlags(int)' on a null object reference
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}: android.view.InflateException: Binary XML file line #48 in com.android.launcher3:layout/launcher: Binary XML file line #16 in com.android.launcher3:layout/hotseat: Error inflating class com.android.launcher3.Hotseat
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8173)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.view.InflateException: Binary XML file line #48 in com.android.launcher3:layout/launcher: Binary XML file line #16 in com.android.launcher3:layout/hotseat: Error inflating class com.android.launcher3.Hotseat
Caused by: android.view.InflateException: Binary XML file line #16 in com.android.launcher3:layout/hotseat: Error inflating class com.android.launcher3.Hotseat
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:871)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1253)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1139)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1104)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1146)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1104)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(StatefulActivity.java:85)
	at com.android.launcher3.Launcher.setupViews(Launcher.java:1350)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:268)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:529)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:624)
	at android.app.Activity.performCreate(Activity.java:8613)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1462)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8173)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.view.InflateException: Binary XML file line #2 in com.android.launcher3:layout/search_container_hotseat: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.addFlags(int)' on a null object reference
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.addFlags(int)' on a null object reference
	at com.android.launcher3.qsb.QsbLayout.setupGIcon(QsbLayout.java:121)
	at com.android.launcher3.qsb.QsbLayout.onFinishInflate(QsbLayout.java:65)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1156)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1104)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.android.launcher3.Hotseat.<init>(Hotseat.java:57)
	at com.android.launcher3.Hotseat.<init>(Hotseat.java:50)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:871)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1253)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1139)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1104)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1146)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1104)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(StatefulActivity.java:85)
	at com.android.launcher3.Launcher.setupViews(Launcher.java:1350)
	at com.android.launcher3.uioverrides.QuickstepLauncher.setupViews(QuickstepLauncher.java:268)
	at com.android.launcher3.Launcher.onCreate(Launcher.java:529)
	at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:624)
	at android.app.Activity.performCreate(Activity.java:8613)
	at android.app.Activity.performCreate(Activity.java:8591)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1462)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8173)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

### Solution

-install real google search bar from play store
-disable google search bar in launcher
-uninstall search bar
-install android auto 4 microg magisk module
-reboot

### Additional context

You can download fake search bar from this repository to test it: https://github.com/sn-00-x/aa4mg/tree/master/system/product/priv-app/Velvet

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
didn't list build date
launcher code changes a lot (lately) so can't pin point issue

**Comment by neobuddy89** [comment]
@guigitignore which gapps?
