### ISSUE TITLE
crashe after turning screen off and back on

### ISSUE THREAD

**Issue by swyam7980** [crdroidandroid/issue_tracker#296]
### Issue type

User interface

### Device

ahannah(moto e5 plus)

### crDroid version

crDroid 8

### Exact version / Build date

8.9/2022-09-15

### Bug description

the build works fine and only crashes after u turn off the screen you can turn on using power button only once after that if you try the second time u turn off the screen and turn it back on it just crashes and start booting the phone 

### Steps to reproduce

step1: turn on the phone 
step2:turn the screen off by using power button 
step3:turn the screen on by using power button
step4:repeat step 2 and 3 a few times
step5:if the screen does not turn back on (it means it has crashed) hold power to turn phone back on

### Relevant log (logcat/build log)

```shell
01-06 22:43:16.254  2982  4303 W SystemUpdate: [Execution,ExecutionManager] Unable to create the action. Restart the execution from the scratch.
01-06 22:43:16.254  2982  4303 W SystemUpdate: java.lang.IllegalStateException
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at ajmn.l(:com.google.android.gms@234914038@23.49.14 (190400-590296185):6)
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at dawn.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):324)
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):122)
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):2)
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at agxh.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):10)
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at nxx.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):70)
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at nxw.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):152)
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at dyxb.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):13)
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-06 22:43:16.254  2982  4303 W SystemUpdate: 	at java.lang.Thread.run(Thread.java:1013)
01-06 22:43:16.284  1702  1879 I PowerManagerService: Powering on display group fromAsleep (groupId=0, uid=1000, reason=WAKE_REASON_POWER_BUTTON, details=android.policy:POWER)...
01-06 22:43:16.284  1702  1879 I PowerManagerService: Waking up from Asleep (uid=1000, reason=WAKE_REASON_POWER_BUTTON, details=android.policy:POWER)...
01-06 22:43:16.285  2982  4303 I SystemUpdate: [Execution,ExecutionManager] Action pending executed for 0.03 seconds.
01-06 22:43:16.288  1702  1702 E ActivityManager: Cancel pending or running compactions as system is awake
01-06 22:43:16.296  2982  4303 I SystemUpdate: [Execution,ExecutionManager] Action pre-download-validate executed for 0.00 seconds.
01-06 22:43:16.300  1702  1822 I DisplayPowerController[0]: Blocking screen on until initial contents have been drawn.
01-06 22:43:16.301  2982  4303 W SystemUpdate: [Execution,ExecutionManager] Unable to create the action. Restart the execution from the scratch.
01-06 22:43:16.301  2982  4303 W SystemUpdate: java.lang.IllegalStateException
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at ajmn.l(:com.google.android.gms@234914038@23.49.14 (190400-590296185):6)
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at dawn.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):324)
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):122)
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):2)
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at agxh.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):10)
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at nxx.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):70)
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at nxw.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):152)
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at dyxb.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):13)
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-06 22:43:16.301  2982  4303 W SystemUpdate: 	at java.lang.Thread.run(Thread.java:1013)
01-06 22:43:16.312  3351  3541 I AiAiEcho: Predicting[0]: 
01-06 22:43:16.312  3351  3541 I AiAiEcho: EchoTargets: 
01-06 22:43:16.312  3351  3541 I AiAiEcho: Filtered by AiAi flag check: 
01-06 22:43:16.312  3351  3541 I AiAiEcho: Ranked targets strategy: SORT, count: 0, ranking metadata: 
01-06 22:43:16.313  6435  6435 W ecovery_proces: Entry not found
01-06 22:43:16.314  6435  6435 W ecovery_proces: Entry not found
01-06 22:43:16.315  3351  3541 I AiAiEcho: #postPredictionTargets: Sending updates to UISurface lockscreen with targets# 0 (types=[])
01-06 22:43:16.315  6435  6435 W ecovery_proces: Entry not found
01-06 22:43:16.321  1702  1822 V DisplayPowerController[0]: Brightness [0.23969081] reason changing to: 'manual', previous reason: 'screen_off'.
01-06 22:43:16.323  6435  6435 W ecovery_proces: JIT profile information will not be recorded: profile file does not exist.
01-06 22:43:16.323  6435  6435 W ecovery_proces: JIT profile information will not be recorded: profile file does not exist.
01-06 22:43:16.323  6435  6435 W ecovery_proces: JIT profile information will not be recorded: profile file does not exist.
01-06 22:43:16.324   878   878 I android.hardware.power-service-qti: Power setMode: 7 to: 1
01-06 22:43:16.325   562   562 D SurfaceFlinger: Setting power mode 2 on display 0
01-06 22:43:16.325   604   619 I SDM     : DisplayBase::SetDisplayState: Set state = 1, display 0
01-06 22:43:16.329  1702  1802 I InputManager-JNI: Viewport [0] to add: local:0, isActive: true
01-06 22:43:16.341  2120  2120 E BcSmartspaceCard: No tap action can be set up
01-06 22:43:16.344  1702  1817 E system_server: Cannot read thread CPU times for PID 1702
01-06 22:43:16.345  1702  1795 D Fingerprint21: Daemon was null, reconnecting, current operation: null
01-06 22:43:16.347   506   506 I hwservicemanager: Since android.hardware.biometrics.fingerprint@2.1::IBiometricsFingerprint/default is not registered, trying to start it as a lazy HAL.
01-06 22:43:16.348  1702  1795 W Fingerprint21: NoSuchElementException
01-06 22:43:16.348  1702  1795 W Fingerprint21: java.util.NoSuchElementException
01-06 22:43:16.348  1702  1795 W Fingerprint21: 	at android.os.HwBinder.getService(Native Method)
01-06 22:43:16.348  1702  1795 W Fingerprint21: 	at android.os.HwBinder.getService(HwBinder.java:81)
01-06 22:43:16.348  1702  1795 W Fingerprint21: 	at android.hardware.biometrics.fingerprint.V2_1.IBiometricsFingerprint.getService(IBiometricsFingerprint.java:74)
01-06 22:43:16.348  1702  1795 W Fingerprint21: 	at android.hardware.biometrics.fingerprint.V2_1.IBiometricsFingerprint.getService(IBiometricsFingerprint.java:84)
01-06 22:43:16.348  1702  1795 W Fingerprint21: 	at com.android.server.biometrics.sensors.fingerprint.hidl.Fingerprint21.getDaemon(Fingerprint21.java:419)
01-06 22:43:16.348  1702  1795 W Fingerprint21: 	at com.android.server.biometrics.sensors.fingerprint.hidl.Fingerprint21.isHardwareDetected(Fingerprint21.java:733)
01-06 22:43:16.348  1702  1795 W Fingerprint21: 	at com.android.server.biometrics.sensors.fingerprint.FingerprintService$FingerprintServiceWrapper.isHardwareDetectedDeprecated(FingerprintService.java:662)
01-06 22:43:16.348  1702  1795 W Fingerprint21: 	at android.hardware.fingerprint.IFingerprintService$Stub.onTransact(IFingerprintService.java:676)
01-06 22:43:16.348  1702  1795 W Fingerprint21: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
01-06 22:43:16.348  1702  1795 W Fingerprint21: 	at android.os.Binder.execTransact(Binder.java:1143)
01-06 22:43:16.348  1702  1795 W Fingerprint21: Fingerprint HAL not available
01-06 22:43:16.348  2982  4303 I SystemUpdate: [Execution,ExecutionManager] Action pending executed for 0.05 seconds.
01-06 22:43:16.351  1702  1879 I InputReader: Reconfiguring input devices, changes=DISPLAY_INFO | 
01-06 22:43:16.351  1702  1879 I InputReader: Device reconfigured: id=4, name='NVTCapacitiveTouchScreen', size 720x1440, orientation 0, mode 1, display id 0
01-06 22:43:16.355  2982  4303 I SystemUpdate: [Execution,ExecutionManager] Action pre-download-validate executed for 0.00 seconds.
01-06 22:43:16.359  2120  2120 D StatusBar: Received new disable state. Old: enaihbcRso.Qingr | New: enaihbcRso.qingr (.q) | New after local modification: enaihbcRso.Qingr (.Q)
01-06 22:43:16.359  2120  2120 D StatusBar: Received new disable state. Old: enaihbcRso.Qingr | New: enaihbcRso.qingr (.q) | New after local modification: enaihbcRso.Qingr (.Q)
01-06 22:43:16.360  2982  4303 W SystemUpdate: [Execution,ExecutionManager] Unable to create the action. Restart the execution from the scratch.
01-06 22:43:16.360  2982  4303 W SystemUpdate: java.lang.IllegalStateException
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at ajmn.l(:com.google.android.gms@234914038@23.49.14 (190400-590296185):6)
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at dawn.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):324)
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):122)
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):2)
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at agxh.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):10)
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at nxx.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):70)
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at nxw.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):152)
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at dyxb.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):13)
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-06 22:43:16.360  2982  4303 W SystemUpdate: 	at java.lang.Thread.run(Thread.java:1013)
01-06 22:43:16.364   506  6460 W libc    : Unable to set property "ctl.interface_start" to "android.hardware.biometrics.fingerprint@2.1::IBiometricsFingerprint/default": error code: 0x20
01-06 22:43:16.364  6435  6435 V GraphicsEnvironment: ANGLE Developer option for 'com.google.android.apps.maps' set to: 'default'
01-06 22:43:16.364   506  6460 I hwservicemanager: Tried to start android.hardware.biometrics.fingerprint@2.1::IBiometricsFingerprint/default as a lazy service, but was unable to. Usually this happens when a service is not installed, but if the service is intended to be used as a lazy service, then it may be configured incorrectly.
01-06 22:43:16.365  6435  6435 V GraphicsEnvironment: ANGLE GameManagerService for com.google.android.apps.maps: false
01-06 22:43:16.366  6435  6435 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
01-06 22:43:16.371  6435  6435 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-06 22:43:16.372  6435  6435 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-06 22:43:16.377   861   861 D audio_hw_primary: adev_set_parameters: enter: screen_state=on
01-06 22:43:16.377   861   861 D audio_hw_extn: audio_extn_set_anc_parameters: anc_enabled:0
01-06 22:43:16.392  3351  3541 I AiAiEcho: Predicting[0]: 
01-06 22:43:16.392  3351  3541 I AiAiEcho: EchoTargets: 
01-06 22:43:16.392  3351  3541 I AiAiEcho: Filtered by AiAi flag check: 
01-06 22:43:16.392  3351  3541 I AiAiEcho: Ranked targets strategy: SORT, count: 0, ranking metadata: 
01-06 22:43:16.393  2982  4303 I SystemUpdate: [Execution,ExecutionManager] Action pending executed for 0.03 seconds.
01-06 22:43:16.395  3351  3541 I AiAiEcho: #postPredictionTargets: Sending updates to UISurface lockscreen with targets# 0 (types=[])
01-06 22:43:16.401  2982  4303 I SystemUpdate: [Execution,ExecutionManager] Action pre-download-validate executed for 0.00 seconds.
01-06 22:43:16.408  2982  4303 W SystemUpdate: [Execution,ExecutionManager] Unable to create the action. Restart the execution from the scratch.
01-06 22:43:16.408  2982  4303 W SystemUpdate: java.lang.IllegalStateException
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at ajmn.l(:com.google.android.gms@234914038@23.49.14 (190400-590296185):6)
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at dawn.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):324)
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):122)
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):2)
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at agxh.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):10)
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at nxx.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):70)
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at nxw.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):152)
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at dyxb.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):13)
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-06 22:43:16.408  2982  4303 W SystemUpdate: 	at java.lang.Thread.run(Thread.java:1013)
01-06 22:43:16.421  4081  4242 I HeterodyneSyncScheduler: (REDACTED) Scheduling adaptive one off task with window [%d, %d] in seconds
01-06 22:43:16.426  6435  6435 I ecovery_proces: System.exit called, status: 0
01-06 22:43:16.427  6435  6435 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
01-06 22:43:16.435  2120  2120 E BcSmartspaceCard: No tap action can be set up
01-06 22:43:16.441  2982  4303 I SystemUpdate: [Execution,ExecutionManager] Action pending executed for 0.03 seconds.
01-06 22:43:16.441   859  1276 W qti_sensors_hal: reportSingleEvent: NearBy 0, pData 876,  highThd 1325
01-06 22:43:16.448  2982  4303 I SystemUpdate: [Execution,ExecutionManager] Action pre-download-validate executed for 0.00 seconds.
01-06 22:43:16.454  1702  1822 I DisplayPowerController[0]: Unblocked screen on after 154 ms
01-06 22:43:16.457  2982  4303 W SystemUpdate: [Execution,ExecutionManager] Unable to create the action. Restart the execution from the scratch.
01-06 22:43:16.457  2982  4303 W SystemUpdate: java.lang.IllegalStateException
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at ajmn.l(:com.google.android.gms@234914038@23.49.14 (190400-590296185):6)
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at dawn.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):324)
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):122)
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):2)
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at agxh.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):10)
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at nxx.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):70)
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at nxw.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):152)
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at dyxb.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):13)
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-06 22:43:16.457  2982  4303 W SystemUpdate: 	at java.lang.Thread.run(Thread.java:1013)
01-06 22:43:16.479  1702  1702 D WindowManager: powerPress: eventTime=324645 interactive=true count=0 beganFromNonInteractive=true mShortPressOnPowerBehavior=1
01-06 22:43:16.486  2292  3032 D QCNEJ/WlanStaInfoRelay: Received action: android.net.wifi.RSSI_CHANGED
01-06 22:43:16.486  2292  3032 I QCNEJ/NativeHalConnector: -> SND notifyWlanStaStatusChanged([WlanStaInfo]: wifiSwitchState = 1 rssi = -50 ssid = Sanjay bssid = bc:62:d2:97:22:18 dnsInfo = 2406:8800:9000:1::10;2406:8800:9000:1::2;192.168.1.1;0.0.0.0; freqBand = _2GHz countryCode = in[RatInfo]: networkType = 1 subType = 101 networkState = CONNECTED netHdl = 437197393933 ipAddrV4 = 192.168.1.5 ipAddrV6 = 2406:8800:9014:4679:101b:163a:a6b6:f7b4 ifNameV4 = wlan0 ifNameV6 = wlan0 slotIdx = 0 isAndroidValidated = true) timeStamp = 2024-01-06 22:43:16.486
01-06 22:43:16.490  2982  4303 I SystemUpdate: [Execution,ExecutionManager] Action pending executed for 0.04 seconds.
01-06 22:43:16.497  2982  4303 I SystemUpdate: [Execution,ExecutionManager] Action pre-download-validate executed for 0.00 seconds.
01-06 22:43:16.505  1702  1822 V DisplayPowerController[0]: Brightness [0.24821731] reason changing to: 'automatic', previous reason: 'manual'.
01-06 22:43:16.506  2982  4303 W SystemUpdate: [Execution,ExecutionManager] Unable to create the action. Restart the execution from the scratch.
01-06 22:43:16.506  2982  4303 W SystemUpdate: java.lang.IllegalStateException
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at ajmn.l(:com.google.android.gms@234914038@23.49.14 (190400-590296185):6)
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at dawn.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):324)
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):122)
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):2)
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at agxh.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):10)
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at nxx.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):70)
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at nxw.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):152)
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at dyxb.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):13)
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-06 22:43:16.506  2982  4303 W SystemUpdate: 	at java.lang.Thread.run(Thread.java:1013)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: Update for unknown DeviceConfig package com.google.android.gms.gcm [CONTEXT service_id=204 ]
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: cnns: No package exists for config package: com.google.android.gms.gcm
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at cnnt.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):70)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at com.google.android.gms.platformconfigurator.PhenotypeConfigurationUpdateListener.b(:com.google.android.gms@234914038@23.49.14 (190400-590296185):6)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at com.google.android.gms.platformconfigurator.PhenotypeConfigurationUpdateListener.a(:com.google.android.gms@234914038@23.49.14 (190400-590296185):151)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at com.google.android.gms.platformconfigurator.PhenotypeConfigurationUpdateListener.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):299)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):2)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at agxh.onHandleIntent(:com.google.android.gms@234914038@23.49.14 (190400-590296185):10)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at nxx.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):70)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at nxw.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):152)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at dyxb.run(:com.google.android.gms@234914038@23.49.14 (190400-590296185):13)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-06 22:43:16.514  4081  6324 W PhenotypeConfigurationU: 	at java.lang.Thread.run(Thread.java:1013)
01-06 22:43:16.524  1702  5085 I ActivityManager: Process com.google.android.apps.maps:server_recovery_process (pid 6435) has died: fg  RCVR
01-06 22:43:16.525   746   746 I Zygote  : Process 6435 exited cleanly (0)
01-06 22:43:16.525  1702  1812 I libprocessgroup: Successfully killed process cgroup uid 10260 pid 6435 in 0ms
01-06 22:43:16.526  1702  1812 I libprocessgroup: Successfully killed process cgroup uid 10260 pid 6435 in 0ms
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/63731896/276f7fc6-7241-4b94-9de1-60b571d9386e

### Additional context

[error.txt](https://github.com/crdroidandroid/issue_tracker/files/13850633/error.txt)
[LogNote__20240106.txt](https://github.com/crdroidandroid/issue_tracker/files/13850634/LogNote__20240106.txt)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unofficial devices can't get official support since we have no way of telling what changes are there in source and also no way to contact maintainer
