### ISSUE TITLE
Crdroid launcher crashing after installing magisk/kernelsu/supersu

### ISSUE THREAD

**Issue by MatrixXD** [crdroidandroid/issue_tracker#307]
### Issue type

User interface

### Device

I use ported version Crdroid 10 for Samsung galaxy m11 (m11q) 
Crom builder i use: https://github.com/smiley9000/Custom-Rom-Builder-For-Samsung-Galaxy-A11-M11

### crDroid version

crDroid 7

### Exact version / Build date

[crDroid-10.0 v2023.12.23](https://github.com/naz664/crDroid_gsi/releases/tag/v2023.12.23)

### Bug description

Crdroid launcher keep crashing after installing Magisk/kernelsu/supersu and process system crashing too

### Steps to reproduce

Then I log in to my phone, after 10 seconds crdroid launcher

### Relevant log (logcat/build log)

```shell
time: 1705602853509
msg: java.lang.SecurityException: Remote stack trace:
	at com.android.server.appprediction.AppPredictionManagerService$PredictionManagerServiceStub.runForUserLocked(AppPredictionManagerService.java:191)
	at com.android.server.appprediction.AppPredictionManagerService$PredictionManagerServiceStub.createPredictionSession(AppPredictionManagerService.java:114)
	at android.app.prediction.IPredictionManager$Stub.onTransact(IPredictionManager.java:140)
	at android.os.Binder.execTransactInternal(Binder.java:1332)
	at android.os.Binder.execTransact(Binder.java:1278)

stacktrace: java.lang.SecurityException: Permission Denial: createPredictionSession from pid=5348, uid=10160 expected caller to hold PACKAGE_USAGE_STATS permission
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3045)
	at android.os.Parcel.readException(Parcel.java:3028)
	at android.os.Parcel.readException(Parcel.java:2970)
	at android.app.prediction.IPredictionManager$Stub$Proxy.createPredictionSession(IPredictionManager.java:253)
	at android.app.prediction.AppPredictor.<init>(AppPredictor.java:102)
	at android.app.prediction.AppPredictionManager.createAppPredictionSession(AppPredictionManager.java:47)
	at com.android.launcher3.model.QuickstepModelDelegate.recreatePredictors(QuickstepModelDelegate.java:352)
	at com.android.launcher3.model.QuickstepModelDelegate.workspaceLoadComplete(QuickstepModelDelegate.java:206)
	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:224)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appprediction.AppPredictionManagerService$PredictionManagerServiceStub.runForUserLocked(AppPredictionManagerService.java:191)
	at com.android.server.appprediction.AppPredictionManagerService$PredictionManagerServiceStub.createPredictionSession(AppPredictionManagerService.java:114)
	at android.app.prediction.IPredictionManager$Stub.onTransact(IPredictionManager.java:140)
	at android.os.Binder.execTransactInternal(Binder.java:1332)
	at android.os.Binder.execTransact(Binder.java:1278)
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unofficial devices can't get official support since we have no way of telling what changes are there in source and also no way to contact maintainer
