### ISSUE TITLE
bug: Random apps will force close at startup on fresh installation

### ISSUE THREAD

**Issue by snappyapple632** [crdroidandroid/issue_tracker#32]
### Issue type

Source code related

### Device

OnePlus 7 Pro (guacamole)

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

Certain apps will force close on startup. This tends to occur on freshly installed apps or by doing certain actions which trigger an irreversible startup crash.

### Steps to reproduce

1. Install an app like Steam.
2. Open the app.
3. App crash should occur. If it doesn't, try another app.

### Relevant log (logcat/build log)

```shell
11-03 01:20:19.017 I/ActivityTaskManager(1866): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.valvesoftware.android.steam.community/.MainActivity bnds=[1135,1715][1412,2104]} from uid 10247
11-03 01:20:19.043 D/CoreBackPreview(1866): Window{c601530 u0 Splash Screen com.valvesoftware.android.steam.community}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@c63a72e, mPriority=0}
11-03 01:20:19.075 I/ActivityManager(1866): Start proc 1283:com.valvesoftware.android.steam.community/u0a399 for next-top-activity {com.valvesoftware.android.steam.community/com.valvesoftware.android.steam.community.MainActivity}
11-03 01:20:19.102 E/steam.community(1283): Not starting debugger since process cannot load the jdwp agent.
11-03 01:20:19.146 D/SoLoader(1283): adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/~~LSHHdkVr1c01ZIqlAlYA8w==/com.valvesoftware.android.steam.community-T6TPAchyo9UqRdtrjdYTRg==/lib/arm64 flags = 0]
11-03 01:20:19.146 D/SoLoader(1283): adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.valvesoftware.android.steam.community/lib-main flags = 1]
11-03 01:20:19.147 D/SoLoader(1283): Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/~~LSHHdkVr1c01ZIqlAlYA8w==/com.valvesoftware.android.steam.community-T6TPAchyo9UqRdtrjdYTRg==/lib/arm64 flags = 0]
11-03 01:20:19.147 D/SoLoader(1283): Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.valvesoftware.android.steam.community/lib-main flags = 1]
11-03 01:20:19.148 I/fb-UnpackingSoSource(1283): dso store is up-to-date: /data/user/0/com.valvesoftware.android.steam.community/lib-main
11-03 01:20:19.160 D/SoLoader(1283): libjscexecutor.so not found on /data/data/com.valvesoftware.android.steam.community/lib-main
11-03 01:20:19.160 D/SoLoader(1283): libjscexecutor.so found on /data/app/~~LSHHdkVr1c01ZIqlAlYA8w==/com.valvesoftware.android.steam.community-T6TPAchyo9UqRdtrjdYTRg==/lib/arm64
11-03 01:20:19.190 D/SoLoader(1283): libreactnativejni.so not found on /data/data/com.valvesoftware.android.steam.community/lib-main
11-03 01:20:19.190 D/SoLoader(1283): libreactnativejni.so found on /data/app/~~LSHHdkVr1c01ZIqlAlYA8w==/com.valvesoftware.android.steam.community-T6TPAchyo9UqRdtrjdYTRg==/lib/arm64
11-03 01:20:19.192 D/SoLoader(1283): libfbjni.so not found on /data/data/com.valvesoftware.android.steam.community/lib-main
11-03 01:20:19.192 D/SoLoader(1283): libfbjni.so found on /data/app/~~LSHHdkVr1c01ZIqlAlYA8w==/com.valvesoftware.android.steam.community-T6TPAchyo9UqRdtrjdYTRg==/lib/arm64
11-03 01:20:19.206 D/CoreBackPreview(1866): Window{3ae6cab u0 com.valvesoftware.android.steam.community/com.valvesoftware.android.steam.community.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@dfb86a1, mPriority=0}
11-03 01:20:19.274 I/ActivityTaskManager(1866): Displayed com.valvesoftware.android.steam.community/.MainActivity: +247ms
11-03 01:20:19.327 D/SoLoader(1283): libyoga.so not found on /data/data/com.valvesoftware.android.steam.community/lib-main
11-03 01:20:19.327 D/SoLoader(1283): libyoga.so found on /data/app/~~LSHHdkVr1c01ZIqlAlYA8w==/com.valvesoftware.android.steam.community-T6TPAchyo9UqRdtrjdYTRg==/lib/arm64
11-03 01:20:19.339 D/ConnectivityService(1866): requestNetwork for uid/pid:10399/1283 activeRequest: null callbackRequest: 500 [NetworkRequest [ REQUEST id=501, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
11-03 01:20:19.342 D/PhoneSwitcherNetworkRequstListener(2923): got request NetworkRequest [ REQUEST id=501, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]
11-03 01:20:19.343 D/UntrustedWifiNetworkFactory(1866): got request NetworkRequest [ REQUEST id=501, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]
11-03 01:20:19.343 D/OemPaidWifiNetworkFactory(1866): got request NetworkRequest [ REQUEST id=501, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]
11-03 01:20:19.344 D/MultiInternetWifiNetworkFactory(1866): got request NetworkRequest [ REQUEST id=501, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]
11-03 01:20:19.632 D/CoreBackPreview(1866): Window{c601530 u0 Splash Screen com.valvesoftware.android.steam.community EXITING}: Setting back callback null
11-03 01:20:19.633 W/InputManager-JNI(1866): Input channel object 'c601530 Splash Screen com.valvesoftware.android.steam.community (client)' was disposed without first being removed with the input manager!
11-03 01:20:19.782 D/SoLoader(1283): libreactnativeblob.so not found on /data/data/com.valvesoftware.android.steam.community/lib-main
11-03 01:20:19.782 D/SoLoader(1283): libreactnativeblob.so found on /data/app/~~LSHHdkVr1c01ZIqlAlYA8w==/com.valvesoftware.android.steam.community-T6TPAchyo9UqRdtrjdYTRg==/lib/arm64
11-03 01:20:20.219 E/FileSystemModule(1283): /data/user/0/com.valvesoftware.android.steam.community/files/current.txt: open failed: ENOENT (No such file or directory)
11-03 01:20:20.497 I/ActivityManager(1866): Start proc 1878:com.android.webview:sandboxed_process0:org.chromium.content.app.SandboxedProcessService0:0/u0i5 for  {com.valvesoftware.android.steam.community/org.chromium.content.app.SandboxedProcessService0:0}
11-03 01:20:20.550 D/ConnectivityService(1866): requestNetwork for uid/pid:10399/1283 activeRequest: null callbackRequest: 504 [NetworkRequest [ REQUEST id=505, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
11-03 01:20:20.553 D/PhoneSwitcherNetworkRequstListener(2923): got request NetworkRequest [ REQUEST id=505, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]
11-03 01:20:20.557 D/UntrustedWifiNetworkFactory(1866): got request NetworkRequest [ REQUEST id=505, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]
11-03 01:20:20.557 D/OemPaidWifiNetworkFactory(1866): got request NetworkRequest [ REQUEST id=505, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]
11-03 01:20:20.557 D/MultiInternetWifiNetworkFactory(1866): got request NetworkRequest [ REQUEST id=505, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]
11-03 01:20:20.940 D/SoLoader(1283): libimagepipeline.so not found on /data/data/com.valvesoftware.android.steam.community/lib-main
11-03 01:20:20.940 D/SoLoader(1283): libimagepipeline.so found on /data/app/~~LSHHdkVr1c01ZIqlAlYA8w==/com.valvesoftware.android.steam.community-T6TPAchyo9UqRdtrjdYTRg==/lib/arm64
11-03 01:20:20.947 D/SoLoader(1283): libnative-imagetranscoder.so not found on /data/data/com.valvesoftware.android.steam.community/lib-main
11-03 01:20:20.947 D/SoLoader(1283): libnative-imagetranscoder.so found on /data/app/~~LSHHdkVr1c01ZIqlAlYA8w==/com.valvesoftware.android.steam.community-T6TPAchyo9UqRdtrjdYTRg==/lib/arm64
11-03 01:20:21.076 I/ActivityManager(1866): Killing 1283:com.valvesoftware.android.steam.community/u0a399 (adj 0): depends on provider com.google.android.gms/.fonts.provider.FontsProvider in dying proc com.google.android.gms.persistent (adj -10000)
11-03 01:20:21.145 D/ConnectivityService(1866): ConnectivityService NetworkRequestInfo binderDied(uid/pid:10399/1283, [NetworkRequest [ REQUEST id=501, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]], android.os.BinderProxy@4c8cc22)
11-03 01:20:21.146 I/WindowManager(1866): WIN DEATH: Window{3ae6cab u0 com.valvesoftware.android.steam.community/com.valvesoftware.android.steam.community.MainActivity}
11-03 01:20:21.146 D/ConnectivityService(1866): releasing NetworkRequest [ REQUEST id=501, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ] (release request)
11-03 01:20:21.146 D/ConnectivityService(1866): ConnectivityService NetworkRequestInfo binderDied(uid/pid:10399/1283, [NetworkRequest [ REQUEST id=505, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]], android.os.BinderProxy@bfd76b3)
11-03 01:20:21.147 W/InputManager-JNI(1866): Input channel object '3ae6cab com.valvesoftware.android.steam.community/com.valvesoftware.android.steam.community.MainActivity (client)' was disposed without first being removed with the input manager!
11-03 01:20:21.147 D/ConnectivityService(1866): releasing NetworkRequest [ REQUEST id=505, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ] (release request)
11-03 01:20:21.147 W/ActivityManager(1866): Exception when unbinding service com.valvesoftware.android.steam.community/org.chromium.content.app.SandboxedProcessService0:0
11-03 01:20:21.152 D/ConnectivityService(1866): ConnectivityService NetworkRequestInfo binderDied(uid/pid:10399/1283, [NetworkRequest [ LISTEN id=506, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND&NOT_VCN_MANAGED Uid: 10399 RequestorUid: 10399 RequestorPkg: com.valvesoftware.android.steam.community UnderlyingNetworks: Null] ]], android.os.BinderProxy@6884470)
11-03 01:20:21.160 W/ActivityTaskManager(1866): Force removing ActivityRecord{1d892f5 u0 com.valvesoftware.android.steam.community/.MainActivity} t639}: app died, no saved state
```

### Solution

Factory reset the device.

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by snappyapple632** [comment]
Here's another logcat from YouTube for the same issue:
```
11-03 11:36:30.070 D/CoreBackPreview(1866): Window{5520f46 u0 com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@fb96159, mPriority=0}
11-03 11:36:31.556 E/YouTube (9803): Error while fetching account list response
11-03 11:36:31.556 E/YouTube (9803): java.util.concurrent.ExecutionException: cse: Please check your network connection
11-03 11:36:31.556 E/YouTube (9803): 	at aezs.o(PG:6)
11-03 11:36:31.556 E/YouTube (9803): 	at aezs.get(PG:13)
11-03 11:36:31.556 E/YouTube (9803): 	at qsn.run(PG:31)
11-03 11:36:31.556 E/YouTube (9803): 	at nrq.run(PG:5)
11-03 11:36:31.556 E/YouTube (9803): 	at nru.run(PG:23)
11-03 11:36:31.556 E/YouTube (9803): 	at mwd.run(PG:6)
11-03 11:36:31.556 E/YouTube (9803): 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.p.run(PG:5)
11-03 11:36:31.556 E/YouTube (9803): 	at java.lang.Thread.run(Thread.java:1012)
11-03 11:36:31.556 E/YouTube (9803): Caused by: cse: Please check your network connection
11-03 11:36:31.556 E/YouTube (9803): 	at ywb.b(PG:10)
11-03 11:36:31.556 E/YouTube (9803): 	at utp.f(PG:7)
11-03 11:36:31.556 E/YouTube (9803): 	at swk.a(PG:14)
11-03 11:36:31.556 E/YouTube (9803): 	at swk.a(PG:49)
11-03 11:36:31.556 E/YouTube (9803): 	at swk.run(PG:21)
11-03 11:36:31.556 E/YouTube (9803): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
11-03 11:36:31.556 E/YouTube (9803): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
11-03 11:36:31.556 E/YouTube (9803): 	at sci.run(PG:55)
11-03 11:36:31.556 E/YouTube (9803): 	... 1 more
11-03 11:36:31.556 E/YouTube (9803): Caused by: java.io.IOException: Error on service connection.
11-03 11:36:31.556 E/YouTube (9803): 	at lwk.l(PG:12)
11-03 11:36:31.556 E/YouTube (9803): 	at lwk.b(PG:18)
11-03 11:36:31.556 E/YouTube (9803): 	at qsq.d(PG:5)
11-03 11:36:31.556 E/YouTube (9803): 	at qso.i(PG:1)
11-03 11:36:31.556 E/YouTube (9803): 	at qsq.g(PG:7)
11-03 11:36:31.556 E/YouTube (9803): 	at qsq.b(PG:1)
11-03 11:36:31.556 E/YouTube (9803): 	at ywb.b(PG:4)
11-03 11:36:31.556 E/YouTube (9803): 	... 8 more
11-03 11:36:31.556 E/YouTube (9803): Caused by: android.os.DeadObjectException
11-03 11:36:31.556 E/YouTube (9803): 	at android.os.BinderProxy.transactNative(Native Method)
11-03 11:36:31.556 E/YouTube (9803): 	at android.os.BinderProxy.transact(BinderProxy.java:584)
11-03 11:36:31.556 E/YouTube (9803): 	at efc.qK(PG:2)
11-03 11:36:31.556 E/YouTube (9803): 	at lwf.a(PG:4)
11-03 11:36:31.556 E/YouTube (9803): 	at lwk.l(PG:11)
11-03 11:36:31.556 E/YouTube (9803): 	... 14 more
11-03 11:36:36.783 E/YouTube (9803): Error while fetching account list response
11-03 11:36:36.783 E/YouTube (9803): java.util.concurrent.ExecutionException: cse: Please check your network connection
11-03 11:36:36.783 E/YouTube (9803): 	at aezs.o(PG:6)
11-03 11:36:36.783 E/YouTube (9803): 	at aezs.get(PG:13)
11-03 11:36:36.783 E/YouTube (9803): 	at qsn.run(PG:31)
11-03 11:36:36.783 E/YouTube (9803): 	at nrq.run(PG:5)
11-03 11:36:36.783 E/YouTube (9803): 	at nru.run(PG:23)
11-03 11:36:36.783 E/YouTube (9803): 	at mwd.run(PG:6)
11-03 11:36:36.783 E/YouTube (9803): 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.p.run(PG:5)
11-03 11:36:36.783 E/YouTube (9803): 	at java.lang.Thread.run(Thread.java:1012)
11-03 11:36:36.783 E/YouTube (9803): Caused by: cse: Please check your network connection
11-03 11:36:36.783 E/YouTube (9803): 	at ywb.b(PG:10)
11-03 11:36:36.783 E/YouTube (9803): 	at utp.f(PG:7)
11-03 11:36:36.783 E/YouTube (9803): 	at swk.a(PG:14)
11-03 11:36:36.783 E/YouTube (9803): 	at swk.a(PG:49)
11-03 11:36:36.783 E/YouTube (9803): 	at swk.run(PG:21)
11-03 11:36:36.783 E/YouTube (9803): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
11-03 11:36:36.783 E/YouTube (9803): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
11-03 11:36:36.783 E/YouTube (9803): 	at sci.run(PG:55)
11-03 11:36:36.783 E/YouTube (9803): 	... 1 more
11-03 11:36:36.783 E/YouTube (9803): Caused by: java.io.IOException: Error on service connection.
11-03 11:36:36.783 E/YouTube (9803): 	at lwk.l(PG:12)
11-03 11:36:36.783 E/YouTube (9803): 	at lwk.b(PG:18)
11-03 11:36:36.783 E/YouTube (9803): 	at qsq.d(PG:5)
11-03 11:36:36.783 E/YouTube (9803): 	at qso.i(PG:1)
11-03 11:36:36.783 E/YouTube (9803): 	at qsq.g(PG:7)
11-03 11:36:36.783 E/YouTube (9803): 	at qsq.b(PG:1)
11-03 11:36:36.783 E/YouTube (9803): 	at ywb.b(PG:4)
11-03 11:36:36.783 E/YouTube (9803): 	... 8 more
11-03 11:36:36.783 E/YouTube (9803): Caused by: android.os.DeadObjectException
11-03 11:36:36.783 E/YouTube (9803): 	at android.os.BinderProxy.transactNative(Native Method)
11-03 11:36:36.783 E/YouTube (9803): 	at android.os.BinderProxy.transact(BinderProxy.java:584)
11-03 11:36:36.783 E/YouTube (9803): 	at efc.qK(PG:2)
11-03 11:36:36.783 E/YouTube (9803): 	at lwf.a(PG:4)
11-03 11:36:36.783 E/YouTube (9803): 	at lwk.l(PG:11)
11-03 11:36:36.783 E/YouTube (9803): 	... 14 more
11-03 11:36:41.328 D/CoreBackPreview(1866): Window{5520f46 u0 com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: Setting back callback null
11-03 11:36:41.333 W/InputManager-JNI(1866): Input channel object '5520f46 com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity (client)' was disposed without first being removed with the input manager!
11-03 11:36:42.264 D/MediaProvider(4043): Deleted 0 Android/media items belonging to com.google.android.youtube on /data/user/0/com.android.providers.media.module/databases/external.db
11-03 11:36:42.668 I/Icing   (9872): doRemovePackageData com.google.android.youtube
11-03 11:36:42.672 I/Icing   (9872): Removing corpus key com.google.android.youtube-internal.3p:VideoObject for package com.google.android.youtube
11-03 11:36:42.712 D/CoreBackPreview(1866): Window{9cb7f13 u0 com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@9e25303, mPriority=0}
11-03 11:36:42.762 I/Icing   (9872): Removing corpus key com.google.android.youtube-.implicit: for package com.google.android.youtube
11-03 11:36:44.057 D/CoreBackPreview(1866): Window{9cb7f13 u0 com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: Setting back callback null
11-03 11:36:44.058 W/InputManager-JNI(1866): Input channel object '9cb7f13 com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity (client)' was disposed without first being removed with the input manager!
11-03 11:36:44.093 D/CoreBackPreview(1866): Window{b8949e0 u0 com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@af34036, mPriority=0}
11-03 11:36:46.052 E/YouTube (9803): Error while fetching account list response
11-03 11:36:46.052 E/YouTube (9803): java.util.concurrent.ExecutionException: cse: Please check your network connection
11-03 11:36:46.052 E/YouTube (9803): 	at aezs.o(PG:6)
11-03 11:36:46.052 E/YouTube (9803): 	at aezs.get(PG:13)
11-03 11:36:46.052 E/YouTube (9803): 	at qsn.run(PG:31)
11-03 11:36:46.052 E/YouTube (9803): 	at nrq.run(PG:5)
11-03 11:36:46.052 E/YouTube (9803): 	at nru.run(PG:23)
11-03 11:36:46.052 E/YouTube (9803): 	at mwd.run(PG:6)
11-03 11:36:46.052 E/YouTube (9803): 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.p.run(PG:5)
11-03 11:36:46.052 E/YouTube (9803): 	at java.lang.Thread.run(Thread.java:1012)
11-03 11:36:46.052 E/YouTube (9803): Caused by: cse: Please check your network connection
11-03 11:36:46.052 E/YouTube (9803): 	at ywb.b(PG:10)
11-03 11:36:46.052 E/YouTube (9803): 	at utp.f(PG:7)
11-03 11:36:46.052 E/YouTube (9803): 	at swk.a(PG:14)
11-03 11:36:46.052 E/YouTube (9803): 	at swk.a(PG:49)
11-03 11:36:46.052 E/YouTube (9803): 	at swk.run(PG:21)
11-03 11:36:46.052 E/YouTube (9803): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
11-03 11:36:46.052 E/YouTube (9803): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
11-03 11:36:46.052 E/YouTube (9803): 	at sci.run(PG:55)
11-03 11:36:46.052 E/YouTube (9803): 	... 1 more
11-03 11:36:46.052 E/YouTube (9803): Caused by: java.io.IOException: Error on service connection.
11-03 11:36:46.052 E/YouTube (9803): 	at lwk.l(PG:12)
11-03 11:36:46.052 E/YouTube (9803): 	at lwk.b(PG:18)
11-03 11:36:46.052 E/YouTube (9803): 	at qsq.d(PG:5)
11-03 11:36:46.052 E/YouTube (9803): 	at qso.i(PG:1)
11-03 11:36:46.052 E/YouTube (9803): 	at qsq.g(PG:7)
11-03 11:36:46.052 E/YouTube (9803): 	at qsq.b(PG:1)
11-03 11:36:46.052 E/YouTube (9803): 	at ywb.b(PG:4)
11-03 11:36:46.052 E/YouTube (9803): 	... 8 more
11-03 11:36:46.052 E/YouTube (9803): Caused by: android.os.DeadObjectException
11-03 11:36:46.052 E/YouTube (9803): 	at android.os.BinderProxy.transactNative(Native Method)
11-03 11:36:46.052 E/YouTube (9803): 	at android.os.BinderProxy.transact(BinderProxy.java:584)
11-03 11:36:46.052 E/YouTube (9803): 	at efc.qK(PG:2)
11-03 11:36:46.052 E/YouTube (9803): 	at lwf.a(PG:4)
11-03 11:36:46.052 E/YouTube (9803): 	at lwk.l(PG:11)
11-03 11:36:46.052 E/YouTube (9803): 	... 14 more
11-03 11:36:48.922 I/InputDispatcher(1866): Channel [Gesture Monitor] swipe-up (server) is stealing touch from [b8949e0 com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity (server), [Gesture Monitor] edge-swipe (server)]
11-03 11:36:49.418 I/AppLocaleUtil(8966): Can display preference - [com.google.android.youtube] : isDisallowedPackage : false / isSignedWithPlatformKey : false / hasLauncherEntry : true / canDisplay : true
11-03 11:36:49.421 W/PackageConfigPersister(1866): App-specific configuration not found for packageName: com.google.android.youtube and userId: 0
11-03 11:36:49.490 W/PackageConfigPersister(1866): App-specific configuration not found for packageName: com.google.android.youtube and userId: 0
11-03 11:36:49.549 W/PackageConfigPersister(1866): App-specific configuration not found for packageName: com.google.android.youtube and userId: 0
```

**Comment by gwolf2u** [comment]
can't confirm
what gapps you used?

**Comment by snappyapple632** [comment]
NikGapps Basic, Sept. 8th release.

**Comment by gwolf2u** [comment]
yes, use proper gapps please
