### ISSUE TITLE
Search settings keyboard disappears

### ISSUE THREAD

**Issue by tgex0** [crdroidandroid/issue_tracker#328]
### Issue type

User interface

### Device

Xiaomi MI 8 (dipper)

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-02-16

### Bug description

After tapping on Settings -> Search Settings, the keyboard (the default crDroid keyboard) appears but then disappears after approximately two seconds (whether you start typing or not).

### Steps to reproduce

1. Settings
2. Tap Search settings
3. Keyboard appears but then disappears after approximately two seconds (whether you start typing or not)
4. After trying this multiple times (sometimes as few as two times), the error message shown in the screenshot appears

### Relevant log (logcat/build log)

```shell
time: 1708136646872
msg: java.lang.IllegalStateException: SearchResult missing title argument
stacktrace: java.lang.RuntimeException: An error occurred while executing doInBackground()
	at androidx.loader.content.ModernAsyncTask$2.done(ModernAsyncTask.java:119)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: SearchResult missing title argument
	at com.android.settings.intelligence.search.SearchResult$Builder.build(SearchResult.java:176)
	at com.android.settings.intelligence.search.savedqueries.SavedQueryLoader.convertCursorToResult(SavedQueryLoader.java:77)
	at com.android.settings.intelligence.search.savedqueries.SavedQueryLoader.loadInBackground(SavedQueryLoader.java:64)
	at com.android.settings.intelligence.search.savedqueries.SavedQueryLoader.loadInBackground(SavedQueryLoader.java:35)
	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:289)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
	at androidx.loader.content.ModernAsyncTask$1.call(ModernAsyncTask.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

### Screenshots or videos

![Screenshot_20240217-151908_Settings](https://github.com/crdroidandroid/issue_tracker/assets/160293965/cb6c6282-c43c-4425-a932-be39efec100c)

### Solution

Unsure.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
what gapps you have installed?

**Comment by tgex0** [comment]
NikGapps-crdroid-official-arm64-14-20240210-signed.zip (recommended on crDroid download page for my device).

**Comment by gwolf2u** [comment]
no issue here on latest 10.4
suggest clean flash

**Comment by alealeks** [comment]
I have this issue on crDroid 10.4 with NikGapps-Gapps-arm64-14-20240509-unofficial.zip (recommended on crDroid download page for my device). Redmi Note 8 Pro (begonia).
