### ISSUE TITLE
Changing font a few times crashes UI

### ISSUE THREAD

**Issue by tgex0** [crdroidandroid/issue_tracker#329]
### Issue type

User interface

### Device

Xiaomi MI 8 (dipper)

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-02-16

### Bug description

Settings -> crDroid Settings -> User Interface -> Font style

Change font a few times and UI crashes (launcher restarts).

### Steps to reproduce

1. Settings
2. crDroid Settings
3. User Interface
4. Font style
5. Change font
6. Repeat step 5 a few times and UI will crash, restarting the launcher

Note that I'm not changing fonts quickly but I am changing them one after the other (without going anywhere else within the settings in between).
Sometimes the crash happens after selecting only two fonts. Other times, I might have to select five or six fonts before the crash happens.

### Relevant log (logcat/build log)

```shell
time: 1708138385655
msg: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
stacktrace: android.view.InflateException: Binary XML file line #44 in com.android.systemui:layout/qs_tile_label: Binary XML file line #44 in com.android.systemui:layout/qs_tile_label: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #44 in com.android.systemui:layout/qs_tile_label: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:871)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:981)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1143)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1104)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.android.systemui.qs.tileimpl.QSTileViewImpl.createAndAddLabels(QSTileViewImpl.kt:378)
	at com.android.systemui.qs.tileimpl.QSTileViewImpl.<init>(QSTileViewImpl.kt:268)
	at com.android.systemui.qs.tileimpl.QSFactoryImpl.createTileView(QSFactoryImpl.java:103)
	at com.android.systemui.qs.QSTileHost.createTileView(QSTileHost.java:521)
	at com.android.systemui.qs.QSHostAdapter.createTileView(QSHostAdapter.kt:184)
	at com.android.systemui.qs.QSPanelControllerBase.addTile(QSPanelControllerBase.java:288)
	at com.android.systemui.qs.QSPanelControllerBase.setTiles(QSPanelControllerBase.java:270)
	at com.android.systemui.qs.QSPanelControllerBase.setTiles(QSPanelControllerBase.java:253)
	at com.android.systemui.qs.QSPanelControllerBase.onTuningChanged(QSPanelControllerBase.java:530)
	at com.android.systemui.tuner.TunerServiceImpl.addTunable(TunerServiceImpl.java:348)
	at com.android.systemui.tuner.TunerServiceImpl.addTunable(TunerServiceImpl.java:314)
	at com.android.systemui.qs.QSPanelControllerBase.onViewAttached(QSPanelControllerBase.java:223)
	at com.android.systemui.qs.QSPanelController.onViewAttached(QSPanelController.java:111)
	at com.android.systemui.util.ViewController$1.onViewAttachedToWindow(ViewController.java:52)
	at com.android.systemui.util.ViewController.init(ViewController.java:80)
	at com.android.systemui.qs.QSFragment.onViewCreated(QSFragment.java:236)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1313)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3009)
	at android.app.FragmentController.dispatchStart(FragmentController.java:196)
	at com.android.systemui.fragments.FragmentHostManager.createFragmentHost(FragmentHostManager.java:115)
	at com.android.systemui.fragments.FragmentHostManager.reloadFragments(FragmentHostManager.java:235)
	at com.android.systemui.fragments.FragmentHostManager.onConfigurationChanged(FragmentHostManager.java:185)
	at com.android.systemui.fragments.FragmentService$FragmentHostState.handleSendConfigurationChange(FragmentService.java:143)
	at com.android.systemui.fragments.FragmentService$FragmentHostState.lambda$sendConfigurationChange$0(FragmentService.java:135)
	at com.android.systemui.fragments.FragmentService$FragmentHostState.$r8$lambda$AZ0EF23ef2-V712c03TU2hWU4pA(FragmentService.java:0)
	at com.android.systemui.fragments.FragmentService$FragmentHostState$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at android.content.res.StringBlock.getSequence(StringBlock.java:107)
	at android.content.res.ApkAssets.getStringFromPool(ApkAssets.java:353)
	at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:876)
	at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1400)
	at android.content.res.TypedArray.getValueAt(TypedArray.java:1385)
	at android.content.res.TypedArray.getFont(TypedArray.java:1042)
	at android.widget.TextView.readTextAppearance(TextView.java:4292)
	at android.widget.TextView.<init>(TextView.java:1205)
	at com.android.systemui.util.SafeMarqueeTextView.<init>(SafeMarqueeTextView.kt:18)
	at com.android.systemui.util.DelayableMarqueeTextView.<init>(DelayableMarqueeTextView.kt:28)
	at com.android.systemui.util.DelayableMarqueeTextView.<init>(DelayableMarqueeTextView.kt:23)
	at com.android.systemui.util.DelayableMarqueeTextView.<init>(DelayableMarqueeTextView.kt:0)
	... 46 more

02-17 15:53:05.472  1169  7298 D audioserver: logFgsApiBegin: FGS Logger Transaction failed, -129
02-17 15:53:05.589  1904  2077 I ActivityTaskManager: Config changes=80000000 {1.0 ?mcc0mnc [en_GB] ldltr sw393dp w393dp h737dp 440dpi nrml long widecg port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2248) mAppBounds=Rect(0, 88 - 1080, 2116) mMaxBounds=Rect(0, 0 - 1080, 2248) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.134 s.11745 fontWeightAdjustment=0}
02-17 15:53:05.615  8795  8795 I TouchInteractionService: preloadOverview: forSUWAllSet=false, isHomeAndOverviewSame=true
02-17 15:53:05.622  1904  2077 I WindowManager: Override config changes=80000000 {1.0 ?mcc0mnc [en_GB] ldltr sw393dp w393dp h737dp 440dpi nrml long widecg port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2248) mAppBounds=Rect(0, 88 - 1080, 2116) mMaxBounds=Rect(0, 0 - 1080, 2248) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.134 s.11745 fontWeightAdjustment=0} for displayId=0
02-17 15:53:05.623 14350 14366 V WindowManagerShell: Transition requested: android.os.BinderProxy@a5d45ad TransitionRequestInfo { type = 6, triggerTask = null, remoteTransition = null, displayChange = null, flags = 0 }
02-17 15:53:05.628  1169  1637 D audioserver: logFgsApiEnd: FGS Logger Transaction failed, -129
02-17 15:53:05.636  8795  8795 D b/254119092: TaskbarManager#mComponentCallbacks.onConfigurationChanged: {1.0 ?mcc0mnc [en_GB] ldltr sw393dp w393dp h737dp 440dpi nrml long widecg port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2248) mAppBounds=Rect(0, 88 - 1080, 2116) mMaxBounds=Rect(0, 0 - 1080, 2248) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.134 s.11745 fontWeightAdjustment=0}
02-17 15:53:05.636  8795  8795 D b/254119092: mActivity and mContext agree taskbarIsPresent=false
02-17 15:53:05.636  8795  8795 D b/254119092: ComponentCallbacks#onConfigurationChanged() configDiff={CONFIG_ASSETS_PATHS}
02-17 15:53:05.636  8795  8795 D b/254119092: mActivity and mContext agree taskbarIsPresent=false
02-17 15:53:05.636  8795  8795 D b/254119092: destroyExistingTaskbar: null
02-17 15:53:05.636  8795  8795 D b/254119092: mActivity and mContext agree taskbarIsPresent=false
02-17 15:53:05.636  8795  8795 D b/254119092: recreateTaskbar: isTaskbarEnabled=false [dp != null (i.e. mUserUnlocked)]=true FLAG_HIDE_NAVBAR_WINDOW=false dp.isTaskbarPresent=false
02-17 15:53:05.636  8795  8795 D b/254119092: mActivity and mContext agree taskbarIsPresent=false
02-17 15:53:05.637  8795  8795 D b/254119092: DisplayController#onConfigurationChanged: {1.0 ?mcc0mnc [en_GB] ldltr sw393dp w393dp h737dp 440dpi nrml long widecg port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2248) mAppBounds=Rect(0, 88 - 1080, 2116) mMaxBounds=Rect(0, 0 - 1080, 2248) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.134 s.11745 fontWeightAdjustment=0}
02-17 15:53:05.643  1904  1904 W Looper  : Slow dispatch took 114ms main h=com.android.providers.settings.SettingsProvider$SettingsRegistry$MyHandler c=null m=1
02-17 15:53:05.643  3431  4039 I AiAiEcho: Settings changed for uri: content://settings/secure/theme_customization_overlay_packages
02-17 15:53:05.645  1904  2077 W Looper  : Slow dispatch took 121ms android.fg h=android.os.Handler c=com.android.server.om.OverlayManagerService$$ExternalSyntheticLambda0@19b16ff m=0
02-17 15:53:05.647 14350 14350 D AndroidRuntime: Shutting down VM
02-17 15:53:05.648 14350 14350 E AndroidRuntime: FATAL EXCEPTION: main
02-17 15:53:05.648 14350 14350 E AndroidRuntime: Process: com.android.systemui, PID: 14350
02-17 15:53:05.648 14350 14350 E AndroidRuntime: android.view.InflateException: Binary XML file line #44 in com.android.systemui:layout/qs_tile_label: Binary XML file line #44 in com.android.systemui:layout/qs_tile_label: Error inflating class <unknown>
02-17 15:53:05.648 14350 14350 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #44 in com.android.systemui:layout/qs_tile_label: Error inflating class <unknown>
02-17 15:53:05.648 14350 14350 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:871)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:981)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1143)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1104)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.tileimpl.QSTileViewImpl.createAndAddLabels(QSTileViewImpl.kt:378)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.tileimpl.QSTileViewImpl.<init>(QSTileViewImpl.kt:268)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.tileimpl.QSFactoryImpl.createTileView(QSFactoryImpl.java:103)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.QSTileHost.createTileView(QSTileHost.java:521)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.QSHostAdapter.createTileView(QSHostAdapter.kt:184)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.QSPanelControllerBase.addTile(QSPanelControllerBase.java:288)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.QSPanelControllerBase.setTiles(QSPanelControllerBase.java:270)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.QSPanelControllerBase.setTiles(QSPanelControllerBase.java:253)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.QSPanelControllerBase.onTuningChanged(QSPanelControllerBase.java:530)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.tuner.TunerServiceImpl.addTunable(TunerServiceImpl.java:348)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.tuner.TunerServiceImpl.addTunable(TunerServiceImpl.java:314)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.QSPanelControllerBase.onViewAttached(QSPanelControllerBase.java:223)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.QSPanelController.onViewAttached(QSPanelController.java:111)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.util.ViewController$1.onViewAttachedToWindow(ViewController.java:52)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.util.ViewController.init(ViewController.java:80)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.qs.QSFragment.onViewCreated(QSFragment.java:236)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1313)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3009)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.app.FragmentController.dispatchStart(FragmentController.java:196)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.fragments.FragmentHostManager.createFragmentHost(FragmentHostManager.java:115)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.fragments.FragmentHostManager.reloadFragments(FragmentHostManager.java:235)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.fragments.FragmentHostManager.onConfigurationChanged(FragmentHostManager.java:185)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.fragments.FragmentService$FragmentHostState.handleSendConfigurationChange(FragmentService.java:143)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.fragments.FragmentService$FragmentHostState.lambda$sendConfigurationChange$0(FragmentService.java:135)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.fragments.FragmentService$FragmentHostState.$r8$lambda$AZ0EF23ef2-V712c03TU2hWU4pA(FragmentService.java:0)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.fragments.FragmentService$FragmentHostState$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8244)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.content.res.StringBlock.getSequence(StringBlock.java:107)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.content.res.ApkAssets.getStringFromPool(ApkAssets.java:353)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:876)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1400)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.content.res.TypedArray.getValueAt(TypedArray.java:1385)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.content.res.TypedArray.getFont(TypedArray.java:1042)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.widget.TextView.readTextAppearance(TextView.java:4292)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:1205)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.util.SafeMarqueeTextView.<init>(SafeMarqueeTextView.kt:18)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.util.DelayableMarqueeTextView.<init>(DelayableMarqueeTextView.kt:28)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.util.DelayableMarqueeTextView.<init>(DelayableMarqueeTextView.kt:23)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	at com.android.systemui.util.DelayableMarqueeTextView.<init>(DelayableMarqueeTextView.kt:0)
02-17 15:53:05.648 14350 14350 E AndroidRuntime: 	... 46 more
02-17 15:53:05.649 14350 14350 I BufferEulogizer: Performing emergency dump of log buffers
02-17 15:53:05.649  2843  2843 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.app.Activity$$ExternalSyntheticLambda0@e1349b6
02-17 15:53:05.649 14350 14350 W BufferEulogizer: Cannot dump logs, last write was only 298649 ms ago
02-17 15:53:05.650  1904  8787 D CoreBackPreview: Window{8efe07c u0 com.android.settings/com.android.settings.SubSettings}: Setting back callback null
02-17 15:53:05.651  1904  3975 W InputManager-JNI: Input channel object '8efe07c com.android.settings/com.android.settings.SubSettings (client)' was disposed without first being removed with the input manager!
02-17 15:53:05.656  1904 14644 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
02-17 15:53:05.657  1904  2078 I ActivityManager: Showing crash dialog for package com.android.systemui u0
02-17 15:53:05.657 14350 14374 D ThemeOverlayController: Overlay changed for user: 0
02-17 15:53:05.660  8795  8795 D b/254119092: unregistering activity lifecycle callbacks from onActivityDestroyed.
02-17 15:53:05.660  8795  8795 D b/254119092: clearActivity
02-17 15:53:05.660  8795  8795 D b/254119092: mActivity and mContext agree taskbarIsPresent=false
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: Failed to parse THEME_CUSTOMIZATION_OVERLAY_PACKAGES.
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: org.json.JSONException: No value for android.theme.customization.theme_style
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at org.json.JSONObject.get(JSONObject.java:398)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at org.json.JSONObject.getString(JSONObject.java:559)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at com.android.systemui.theme.ThemeOverlayController.fetchThemeStyleFromSetting(ThemeOverlayController.java:1005)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at com.android.systemui.theme.ThemeOverlayController.reevaluateSystemTheme(ThemeOverlayController.java:724)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at com.android.systemui.theme.ThemeOverlayController.-$$Nest$mreevaluateSystemTheme(ThemeOverlayController.java:0)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at com.android.systemui.theme.ThemeOverlayController$6.onChange(ThemeOverlayController.java:490)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at android.database.ContentObserver.lambda$dispatchChange$0(ContentObserver.java:304)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at android.database.ContentObserver.$r8$lambda$ZTAX5Dz0QB2gJk_nBFGhENlKHoI(Unknown Source:0)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at android.database.ContentObserver$$ExternalSyntheticLambda0.run(Unknown Source:10)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at android.os.Handler.handleCallback(Handler.java:958)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at android.os.Looper.loopOnce(Looper.java:205)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at android.os.Looper.loop(Looper.java:294)
02-17 15:53:05.662 14350 14374 I ThemeOverlayController: 	at android.os.HandlerThread.run(HandlerThread.java:67)
02-17 15:53:05.665 14350 14374 D ThemeOverlayController: fetched overlays. accent: android.content.om.FabricatedOverlay@945b2bc neutral: android.content.om.FabricatedOverlay@88a9245 dynamic: android.content.om.FabricatedOverlay@1ef7d9a
02-17 15:53:05.665 14350 14374 D ThemeOverlayController: updateThemeOverlays. Setting: {"android.theme.customization.font":"com.android.theme.font.bariol"}
02-17 15:53:05.666 14350 14374 D ThemeOverlayController: Applying overlays: android.theme.customization.system_palette -> com.android.system.theme.black, android.theme.customization.dynamic_color -> com.android.systemui:dynamic, android.theme.customization.font -> com.android.theme.font.bariol, android.theme.customization.accent_color -> com.android.systemui:accent
02-17 15:53:05.669  2843  2843 D ActivityEmbeddingUtils: isSettingsSplitSupported = false
02-17 15:53:05.669  3026  3227 I PermissionControllerServiceImpl: Updating user sensitive for uid 1000
02-17 15:53:05.671  1904  2309 I InputReader: Reconfiguring input devices, changes=KEYBOARD_LAYOUTS
02-17 15:53:05.673  1904  2088 W WindowMagnificationMgr: requestConnection duplicated request: connect=false, mConnectionState=DISCONNECTED
02-17 15:53:05.674  8795  8818 D IconPackManager: Received intent action android.intent.action.PACKAGE_CHANGED for android
02-17 15:53:05.676  1904  2102 W libprocessgroup: SetCgroup::ExecuteForProcess: failed to open /dev/blkio/background/cgroup.procs: No such file or directory
02-17 15:53:05.677  8795  8795 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@aaa6807
02-17 15:53:05.677 14350 14366 V ShellDragAndDrop: Display changed: 0
02-17 15:53:05.678  1904  7341 D CoreBackPreview: Window{bd581ee u0 com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}: Setting back callback null
02-17 15:53:05.679  2843  2843 D SettingsActivity: Starting onCreate
02-17 15:53:05.680 11817 11817 I Finsky  : [2] xhw.g(1): xhw - Received: android.intent.action.PACKAGE_CHANGED, [9g7VapyCdYlAIv5aehYlwzvbVbcpu044lir00WE-2iU]
02-17 15:53:05.681  1904  2080 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
02-17 15:53:05.682 14586 14586 W idmap2d : failed to parse idmap header of '/data/resource-cache/data@resource-cache@com.android.systemui-accent-8QCK.frro@idmap'
02-17 15:53:05.685  2843  2843 D SettingsActivity: Starting to set activity title
02-17 15:53:05.685  2843  2843 D SettingsActivity: Done setting title
02-17 15:53:05.686  2843  2843 D SettingsActivity: MetricsCategory is 4000
02-17 15:53:05.691 14586 14586 W idmap2d : failed to parse idmap header of '/data/resource-cache/data@resource-cache@com.android.systemui-neutral-wZR2.frro@idmap'
02-17 15:53:05.693  1904  3377 W InputManager-JNI: Input channel object 'bd581ee com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher (client)' was disposed without first being removed with the input manager!
02-17 15:53:05.694  2843  2843 D CategoryMixin: Skip categories update
02-17 15:53:05.699 14586 14586 W idmap2d : failed to parse idmap header of '/data/resource-cache/data@resource-cache@com.android.systemui-dynamic-xypw.frro@idmap'
02-17 15:53:05.700  1904  3377 D CoreBackPreview: Window{8dd6bbb u0 com.android.settings/com.android.settings.SubSettings}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@fda716, mPriority=-1, mIsAnimationCallback=false}
02-17 15:53:05.705  2843 13044 D SettingsActivity: No enabled state changed, skipping updateCategory call
02-17 15:53:05.706  1904  2102 W libprocessgroup: SetCgroup::ExecuteForProcess: failed to open /dev/blkio/background/cgroup.procs: No such file or directory
02-17 15:53:05.707  3058 14632 I Fitness : (REDACTED) OnPackageChangedOperation got intent: %s
02-17 15:53:05.707 11817 11817 I Finsky  : [2] kgq.f(9): AIM: AppInfoCacheUpdater -> invalidating apps: [android]
02-17 15:53:05.708 11817 11817 I Finsky  : [2] khf.g(21): AIM: AppInfoManager-Perf > getApps > called for 1 apps
02-17 15:53:05.708  3487  3487 D RegisteredNfcFServicesCache: Service unchanged, not updating
02-17 15:53:05.708  2804  2841 D SecureElementService: getReaders() for com.android.nfc
02-17 15:53:05.710 11817 11879 I Finsky  : [76] kik.a(55): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=0, cacheMissCount=1. Missed  in cache (limit 10) : [android]
02-17 15:53:05.711 11817 11879 I Finsky  : [76] kgi.apply(1129): AIM: Got app ownership map. App counts: . Unique apps: 0
02-17 15:53:05.711 11817 11879 I Finsky  : [76] kik.a(55): AIM: AppInfoManager-Perf > OnDeviceAppInfo > cacheHitCount=1, cacheMissCount=0. Missed  in cache (limit 10) : []
02-17 15:53:05.712  2838  2838 D CarrierSvcBindHelper: onPackageModified: android
02-17 15:53:05.712 11817 11879 I Finsky  : [76] kgi.apply(1129): AIM: Got app ownership map. App counts: . Unique apps: 0
02-17 15:53:05.712  1904  2102 W libprocessgroup: SetCgroup::ExecuteForProcess: failed to open /dev/blkio/background/cgroup.procs: No such file or directory
02-17 15:53:05.715  2838  2838 D CarrierSvcBindHelper: No carrier app for: 0
02-17 15:53:05.715  2838  2838 D CarrierSvcBindHelper: No carrier app for: 1
02-17 15:53:05.723  1904  2102 W libprocessgroup: SetCgroup::ExecuteForProcess: failed to open /dev/blkio/background/cgroup.procs: No such file or directory
02-17 15:53:05.724  3058 14600 I Fitness : (REDACTED) FitCleanupIntentOperation received Intent %s
02-17 15:53:05.734 11817 14598 I Finsky  : [143] onj.accept(139): Wrote row to frosting DB: 1028
02-17 15:53:05.734  1904  2078 D CoreBackPreview: Window{2b1ba1 u0 Application Error: com.android.systemui}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@b0316ba, mPriority=0, mIsAnimationCallback=false}
02-17 15:53:05.734  1904  2102 W libprocessgroup: SetCgroup::ExecuteForProcess: failed to open /dev/blkio/background/cgroup.procs: No such file or directory
02-17 15:53:05.735  3058 14632 I Fitness : (REDACTED) OnPackageChangedOperation got intent: %s
02-17 15:53:05.746  1904  5703 E OpenGLRenderer: Unable to match the desired swap behavior.
02-17 15:53:05.749 11817 14598 I Finsky  : [143] onj.accept(139): Wrote row to frosting DB: 1029
```

### Solution

Unsure.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is kinda expected as UI didn't had time to update all elements until font is changed again
it was the same even in old revisions

**Comment by neobuddy89** [comment]
No fixes currently.
