### ISSUE TITLE
bug: banking app crashes

### ISSUE THREAD

**Issue by tacticalninj4** [crdroidandroid/issue_tracker#345]
### Issue type

Other

### Device

Redmi Note 10 Pro (sweet)

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-03-16

### Bug description

Banking App Crashes when open with the exception of 
`
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.UserManager.isUserUnlocked()' on a null object reference
`

### Steps to reproduce

Step 1: Download and install [BizChannel@CIMB](https://play.google.com/store/apps/details?id=com.cimb.rtbmobile&hl=en&gl=US) from Play Store.
Step 2: Launch the app.

### Relevant log (logcat/build log)

```shell
03-24 11:39:58.388  5324  5324 E AndroidRuntime: FATAL EXCEPTION: main
03-24 11:39:58.388  5324  5324 E AndroidRuntime: Process: com.cimb.rtbmobile:com.aprisma.product.primemobile.service.CoreService, PID: 5324
03-24 11:39:58.388  5324  5324 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.cimbrtbmobile.MainApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.UserManager.isUserUnlocked()' on a null object reference
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7065)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8246)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.UserManager.isUserUnlocked()' on a null object reference
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at androidx.core.b.g.a(UserManagerCompat.java:42)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.3.0:558)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:304)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at com.cimbrtbmobile.MainApplication.onCreate(Native Method)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1322)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7060)
03-24 11:39:58.388  5324  5324 E AndroidRuntime: 	... 9 more
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
please update to latest revision 10.4 and check
