### ISSUE TITLE
bug: ExoPlayer crashes when rotating phone from landscape (fullscreen) to portrait in NewPipe

### ISSUE THREAD

**Issue by Melarok** [crdroidandroid/issue_tracker#35]
### Issue type

Source code related

### Device

Poco F3 (alioth)

### crDroid version

crDroid 9

### Exact version

9.0 build from 05.11.22

### Bug description

Since switching to A13 NewPipe crashes when rotating the screen from landscape to portrait during playback. This didn't happen on A12L.
I already reported the bug to the NewPipe team, but they sent me here on the suspicion that it's a source bug.

Link to the NewPipe issue:
TeamNewPipe/NewPipe#9254

### Steps to reproduce

1. Open NewPipe
2. Watch any video in fullscreen
3. Rotate phone to portrait during playback
4. Observe crash

### Relevant log (logcat/build log)

```shell
The full log is too long for GitHub, so I'm going to only attach the short version, adding the long one in a comment below.




11-10 09:27:41.484 D/SurfaceUtils(11609): connecting to surface 0x73ef65b960, reason connectToSurface
11-10 09:27:41.484 E/BufferQueueProducer(11609): [SurfaceTexture-1-11609-8](id:2d5900000043,api:3,p:11609,c:11609) connect: already connected (cur=3 req=3)
11-10 09:27:41.484 E/SurfaceUtils(11609): Failed to connect to surface 0x73ef65b960, err -22
11-10 09:27:41.484 E/MediaCodec(11609): nativeWindowConnect returned an error: Invalid argument (-22)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609): Playback error
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):   com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at android.os.Handler.dispatchMessage(Handler.java:102)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at android.os.Looper.loopOnce(Looper.java:201)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at android.os.Looper.loop(Looper.java:288)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at android.os.HandlerThread.run(HandlerThread.java:67)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):   Caused by: java.lang.IllegalArgumentException
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at android.media.MediaCodec.native_setSurface(Native Method)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2233)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.setOutputSurface(AsynchronousMediaCodecAdapter.java:262)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
11-10 09:27:41.484 E/ExoPlayerImplInternal(11609):       ... 4 more

11-10 09:27:41.664 E/Player  (11609): ExoPlayer - onPlayerError() called with:
11-10 09:27:41.664 E/Player  (11609): com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
11-10 09:27:41.664 E/Player  (11609): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
11-10 09:27:41.664 E/Player  (11609): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-10 09:27:41.664 E/Player  (11609): 	at android.os.Looper.loopOnce(Looper.java:201)
11-10 09:27:41.664 E/Player  (11609): 	at android.os.Looper.loop(Looper.java:288)
11-10 09:27:41.664 E/Player  (11609): 	at android.os.HandlerThread.run(HandlerThread.java:67)
11-10 09:27:41.664 E/Player  (11609): Caused by: java.lang.IllegalArgumentException
11-10 09:27:41.664 E/Player  (11609): 	at android.media.MediaCodec.native_setSurface(Native Method)
11-10 09:27:41.664 E/Player  (11609): 	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2233)
11-10 09:27:41.664 E/Player  (11609): 	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
11-10 09:27:41.664 E/Player  (11609): 	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.setOutputSurface(AsynchronousMediaCodecAdapter.java:262)
11-10 09:27:41.664 E/Player  (11609): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)
11-10 09:27:41.664 E/Player  (11609): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)
11-10 09:27:41.664 E/Player  (11609): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)
11-10 09:27:41.664 E/Player  (11609): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)
11-10 09:27:41.664 E/Player  (11609): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)
11-10 09:27:41.664 E/Player  (11609): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)
11-10 09:27:41.664 E/Player  (11609): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
11-10 09:27:41.664 E/Player  (11609): 	... 4 more
```

### Additional context

I tried to only include the relevant part of the log (as in, I truncated the start to where NewPipe is opened).
If you need anything else, I'm happy to supply additional info :)

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Melarok** [comment]
Full log here:
[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/9979333/logcat.txt)

**Comment by raystef66** [comment]
To rule out issues make sure you're on the latest 10.11.2022 build.
https://forum.xda-developers.com/t/rom-13-0-official-alioth-aliothin-crdroid-v9-0-10-11-2022.4512033/post-87705819

**Comment by Melarok** [comment]
It's still crashing on the 10.11.22 build with the same error.

**Comment by raystef66** [comment]
Will review this in coming days.

**Comment by neobuddy89** [comment]
APK link? @Melarok

**Comment by gwolf2u** [comment]
> APK link? @Melarok 
https://f-droid.org/repo/org.schabi.newpipe_991.apk

**Comment by Melarok** [comment]
@neobuddy89 Here you go: https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.24.1

BTW: It also crashes on build 12.10.22

**Comment by raystef66** [comment]
Tested on F3 and F2 Pro and crashes on both using landscape to portrait.
Tried on Ricedroid same. Bliss working though, so source issue afaik.

**Comment by gwolf2u** [comment]
still happening?

**Comment by raystef66** [comment]
On 17.12 build still there unfortunately, will check later today on latest source.

**Comment by raystef66** [comment]
Still crashing. Same log as above.
26.12 build

**Comment by LuckyLukas98** [comment]
I can report the same Issue on Xiaomi Redmi Note 8 Pro (begonia) with crDroid-Version 9.0 (16.12.2022), Build-Version TQ1A.221205.011.

**Comment by AlessandroG200** [comment]
I am also experiencing this issue on Poco X3 Pro (vayu), crDroid version 9.2 (build id: TQ1A.230205.002, build date Mon Feb 20 00:01:30 IST 2023), latest NewPipe (0.25.0). Maybe an issue specific to Xiaomi devices?

**Comment by Terminator-J** [comment]
Can confirm on enchilada & fajita, all of my Android 13 builds since 9.0 Nov ASB.

**Comment by ShevT** [comment]
https://github.com/google/ExoPlayer/issues/8696

**Comment by Terminator-J** [comment]
> [google/ExoPlayer#8696](https://github.com/google/ExoPlayer/issues/8696)

But if you look in external/exoplayer/, those changes are already present in the newer trees.
Is there something else going on?

**Comment by Terminator-J** [comment]
Definitely something else going on. I got busy testing, since the last few official LineageOS builds for my devices work correctly.
Got some actionable logs and am playing with things.

Failing attempts look like this:
```
03-08 17:08:42.020  9693  9827 D SurfaceUtils: connecting to surface 0x789c5bc960, reason connectToSurface
03-08 17:08:42.020  9693  9827 E BufferQueueProducer: [SurfaceTexture-1-9693-0](id:25dd00000002,api:3,p:9693,c:9693) connect: already connected (cur=3 req=3)
03-08 17:08:42.020  9693  9827 E SurfaceUtils: Failed to connect to surface 0x789c5bc960, err -22
```

Successful attempts look like this:
```
03-09 09:42:45.183 10266 11411 D SurfaceUtils: connecting to surface 0x76434f9740, reason connectToSurface
03-09 09:42:45.183 10266 11411 I MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 10512401
03-09 09:42:45.183 10266 11411 D SurfaceUtils: disconnecting from surface 0x76434f9740, reason connectToSurface(reconnect)
```

SurfaceUtils & BufferQueueProducer are in frameworks/native and MediaCodec is in frameworks/av, so I tried various tests with reverting one or both of those projects back to match lineage-20.0 branch of LineageOS.

Tests & results:
- roll back only frameworks/native to match lineage-20.0: bug still present
- roll back both frameworks/native and frameworks/av to match lineage-20.0: bug gone
- roll back only frameworks/av to match lineage-20.0: bug gone

Now I'm working my way through a `git bisect` of frameworks/av (with clean build each time, bleah) to find the culprit to revert.

**Comment by gwolf2u** [comment]
fixed in https://github.com/crdroidandroid/android_frameworks_av/commit/49440e69b979ebf2c1e37264d7d09cf28a8924bc
