### ISSUE TITLE
BUG: Call recording crashes dialer on playback

### ISSUE THREAD

**Issue by Avrution** [crdroidandroid/issue_tracker#366]
### Issue type

Feature not working as intended

### Device

Oneplus 7T (hotdogb)

### crDroid version

crDroid 10

### Exact version / Build date

10.4 - [crDroidAndroid-14.0-20240407-hotdogb-v10.4.zip](https://sourceforge.net/projects/crdroid/files/hotdogb/10.x/crDroidAndroid-14.0-20240407-hotdogb-v10.4.zip/download)

### Bug description

Playback of recorded calls crashes dialer app

### Steps to reproduce

Make or receive phone call
Call is recorded
Try and playback recorded call
Dialer crashes

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/3Fy9rW


3455 characters, 46 lines
12345678910111213141516171819202122232425262728293031323334353637383940414243444546
time: 1712943820447
msg: java.lang.SecurityException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1279)
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:649)
	at com.android.server.uri.UriGrantsManagerService.-$$Nest$mcheckGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:0)
	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1504)
	at com.android.server.wm.ActivityStarter$Request.resolveActivity(ActivityStarter.java:591)

stacktrace: java.lang.SecurityException: UID 10374 does not have permission to content://media/external/audio/media/1000031328 [user 0]
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3186)
	at android.os.Parcel.createException(Parcel.java:3170)
	at android.os.Parcel.readException(Parcel.java:3153)
	at android.os.Parcel.readException(Parcel.java:3095)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2098)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1950)
	at android.app.Activity.startActivityForResult(Activity.java:5761)
	at androidx.activity.ComponentActivity.startActivityForResult(PG:695)
	at android.app.Activity.startActivityForResult(Activity.java:5719)
	at androidx.activity.ComponentActivity.startActivityForResult(PG:674)
	at android.app.Activity.startActivity(Activity.java:6217)
	at android.app.Activity.startActivity(Activity.java:6184)
	at com.android.dialer.calldetails.CallDetailsEntryViewHolder.playRecording(PG:200)
	at com.android.dialer.calldetails.CallDetailsEntryViewHolder.handleRecordingClick(PG:170)
	at com.android.dialer.calldetails.CallDetailsEntryViewHolder.lambda$setCallDetails$0(PG:142)
	at com.android.dialer.calldetails.CallDetailsEntryViewHolder.$r8$lambda$yv_JjsacDgoUVjgxSNH4wBNiHck(PG:0)
	at com.android.dialer.calldetails.CallDetailsEntryViewHolder$$ExternalSyntheticLambda0.onClick(PG:0)
	at android.view.View.performClick(View.java:7729)
	at android.view.View.performClickInternal(View.java:7706)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30486)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8496)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1279)
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:649)
	at com.android.server.uri.UriGrantsManagerService.-$$Nest$mcheckGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:0)
	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1504)
	at com.android.server.wm.ActivityStarter$Request.resolveActivity(ActivityStarter.java:591)

GitHub | Change privacy settings
Version: crDroid edition
```

### Additional context

Wiped ROM and started from fresh, issue still exists.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Avrution** [comment]
Log taken as well
[logs-2024-04-14-04-25-23.zip](https://github.com/crdroidandroid/issue_tracker/files/14974364/logs-2024-04-14-04-25-23.zip)

**Comment by Avrution** [comment]
Error only logging - no idea if any of these help or not.

Fresh call made to test.  Can play file directly, dialer crashes if trying to play from there.

[logcat_04-15-2024_11-58-26.txt](https://github.com/crdroidandroid/issue_tracker/files/14982232/logcat_04-15-2024_11-58-26.txt)

**Comment by gwolf2u** [comment]
This should be fixed
Tested a call recording playback, all was fine

**Comment by Avrution** [comment]
Wanted to add one thing I found - if you have the .nomedia file in the call recording folder, it crashes the playback.  I have used other roms and none of them did that.
