### ISSUE TITLE
bug: unpredictable app crashes

### ISSUE THREAD

**Issue by FreePhoenix888** [crdroidandroid/issue_tracker#39]
### Issue type

Source code related

### Device

Redmi Note 8 (ginkgo)

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

This bug is not permanent its behavior is very strange and it is difficult to say when it is going to crash. Gapps: latest nikgapps

### Steps to reproduce

1. Open any app

### Relevant log (logcat/build log)

```shell
12:29:49.464  E  FATAL EXCEPTION: lowpool[2]
                 Process: com.google.android.gms.persistent, PID: 23553
                 java.lang.SecurityException: Permission Denial: recordResponseEventWhileInBackground from pid=23553, uid=10179 requires android.permission.ACCESS_BROADCAST_RESPONSE_STATS
                   at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
                   at android.os.Parcel.createException(Parcel.java:2999)
                   at android.os.Parcel.readException(Parcel.java:2982)
                   at android.os.Parcel.readException(Parcel.java:2924)
                   at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5117)
                   at android.app.ContextImpl.sendOrderedBroadcast(ContextImpl.java:1402)
                   at android.app.ContextImpl.sendOrderedBroadcast(ContextImpl.java:1362)
                   at android.content.ContextWrapper.sendOrderedBroadcast(ContextWrapper.java:575)
                   at aljs.c(:com.google.android.gms@224417044@22.44.17 (190400-488410709):36)
                   at aljs.a(:com.google.android.gms@224417044@22.44.17 (190400-488410709):17)
                   at aljg.a(:com.google.android.gms@224417044@22.44.17 (190400-488410709):0)
                   at aljs.g(:com.google.android.gms@224417044@22.44.17 (190400-488410709):2)
                   at aljs.j(:com.google.android.gms@224417044@22.44.17 (190400-488410709):0)
                   at alnq.i(:com.google.android.gms@224417044@22.44.17 (190400-488410709):15)
                   at aljs.h(:com.google.android.gms@224417044@22.44.17 (190400-488410709):0)
                   at aljf.run(:com.google.android.gms@224417044@22.44.17 (190400-488410709):0)
                   at aabe.c(:com.google.android.gms@224417044@22.44.17 (190400-488410709):6)
                   at aabe.run(:com.google.android.gms@224417044@22.44.17 (190400-488410709):7)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                   at aagj.run(:com.google.android.gms@224417044@22.44.17 (190400-488410709):0)
                   at java.lang.Thread.run(Thread.java:1012)
                   Suppressed: cvhl: 
                     at tk_trace.gcm-GcmChimeraService_onCreate(Unknown Source:0)
                 Caused by: android.os.RemoteException: Remote stack trace:
                   at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:5944)
                   at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13669)
                   at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:13548)
                   at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:14411)
                   at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2306)
```

### Solution

Reboot

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
we don't ship gapps and this is gapps package issue
