### ISSUE TITLE
bug: system ui crashes

### ISSUE THREAD

**Issue by kanishk-upadhyay** [crdroidandroid/issue_tracker#410]
### Issue type

Other

### Device

RMX3031

### crDroid version

crDroid 9

### Exact version / Build date

9.10/2023-10-14

### Bug description

Turning dark mode on and off consequently causes system ui to crash which renders the whole touchscreen useless.

### Steps to reproduce

toggle dark theme twice or more consequently 

### Relevant log (logcat/build log)

```shell
[Device Brand]: realme
[Device Model]: Realme X7 Max 5G
[Display]: TQ3A.230901.001 release-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: en_IN
[Process ID]: 4866
[User ID]: 0
[CPU ABI]: none
[Package Name]: com.android.systemui
[Version Name]: 13
[Version Code]: 33
[Target SDK]: 33
[Min SDK]: 33
[Error Type]: JVM
[Crash Time]: 2024-05-14T20:51:06.002
[Stack Trace]:
android.view.InflateException: Binary XML file line #31 in com.android.systemui:layout/qs_tile_label: Binary XML file line #31 in com.android.systemui:layout/qs_tile_label: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #31 in com.android.systemui:layout/qs_tile_label: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:863)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1135)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at com.android.systemui.qs.tileimpl.QSTileViewImpl.<init>(QSTileViewImpl.kt:321)
	at com.android.systemui.qs.tileimpl.QSFactoryImpl.createTileView(QSFactoryImpl.java:6)
	at com.android.systemui.qs.QSTileHost.createTileView(QSTileHost.java:17)
	at com.android.systemui.qs.QSPanelControllerBase.setTiles(QSPanelControllerBase.java:23)
	at com.android.systemui.qs.QSPanelControllerBase.setTiles(QSPanelControllerBase.java:2)
	at com.android.systemui.qs.QSPanelControllerBase.onTuningChanged(QSPanelControllerBase.java:83)
	at com.android.systemui.tuner.TunerServiceImpl.addTunable(TunerServiceImpl.java:319)
	at com.android.systemui.qs.QSPanelControllerBase.onViewAttached(QSPanelControllerBase.java:122)
	at com.android.systemui.qs.QSPanelController.onViewAttached(QSPanelController.java:0)
	at com.android.systemui.util.ViewController$1.onViewAttachedToWindow(ViewController.java:2)
	at com.android.systemui.util.ViewController.init(ViewController.java:21)
	at com.android.systemui.qs.QSFragment.onViewCreated(QSFragment.java:20)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1313)
	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3009)
	at android.app.FragmentController.dispatchStart(FragmentController.java:196)
	at com.android.systemui.fragments.FragmentHostManager.createFragmentHost(FragmentHostManager.java:48)
	at com.android.systemui.fragments.FragmentHostManager.reloadFragments(FragmentHostManager.java:37)
	at com.android.wm.shell.common.ExecutorUtils$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:45)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7937)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
Caused by: java.lang.IndexOutOfBoundsException
	at android.content.res.StringBlock.nativeGetString(Native Method)
	at android.content.res.StringBlock.getSequence(StringBlock.java:124)
	at android.content.res.ApkAssets.getStringFromPool(ApkAssets.java:351)
	at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:872)
	at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:1400)
	at android.content.res.TypedArray.getValueAt(TypedArray.java:1385)
	at android.content.res.TypedArray.getFont(TypedArray.java:1042)
	at android.widget.TextView.readTextAppearance(TextView.java:4154)
	at android.widget.TextView.<init>(TextView.java:1128)
	at com.android.systemui.util.SafeMarqueeTextView.<init>(SafeMarqueeTextView.kt:2)
	at com.android.systemui.util.DelayableMarqueeTextView.<init>(DelayableMarqueeTextView.kt:2)
	at com.android.systemui.util.DelayableMarqueeTextView.<init>(DelayableMarqueeTextView.kt:1)
	at com.android.systemui.util.DelayableMarqueeTextView.<init>(Unknown Source:8)
	... 38 more
```

### Solution

Only solution to get the touchscreen working is to reboot the system by pressing the power and volume up button simultaneously.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
This has been fixed on 9.x and 10.x
