### ISSUE TITLE
bug: Recents window is crashing on launcher

### ISSUE THREAD

**Issue by arunv2518p** [crdroidandroid/issue_tracker#428]
### Issue type

Source code related

### Device

Redmi 12C (Unofficial)

### crDroid version

crDroid 10

### Exact version / Build date

10.5

### Bug description

The recents window is crashing if we try to open it in any launcher other than the default (crDroid Home) and never display the recents window after crash

### Steps to reproduce

Step1. Install a custom launcher (Smart Launcher or any other)
Step2. Set it as default launcher (important)
Step3. Click 'recents' button in navbar to open the recents
Step4. Click 'home' button in navbar to close the showed recents window 
Step5. Repeat Step3 and Step 4 multiple times fastly (after 2-3 times, it will crash)

### Relevant log (logcat/build log)

```shell
Logcat doesn't display any error or fatal crash
```

### Solution

Set crDroid Home as default launcher and open recents inside that launcher, then set custom launcher as default again

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by arunv2518p** [comment]
I found the error in logcat

2024-05-30 14:28:35.778 2608 2608 com.android.launcher3 E AbsSwipeUpHandler : RecentsView destination page is invalid
java.lang.IllegalStateException
	at com.android.quickstep.AbsSwipeUpHandler.handleNormalGestureEnd(Unknown Source:208)
	at com.android.quickstep.AbsSwipeUpHandler.lambda$onGestureEnded$13(Unknown Source:1)
	at com.android.quickstep.AbsSwipeUpHandler.$r8$lambda$S5gvT_OU5trw50vDcnjp7h2UdIA(Unknown Source:0)
	at com.android.quickstep.AbsSwipeUpHandler$$ExternalSyntheticLambda57.run(Unknown Source:8)
	at com.android.launcher3.PagedView.onPageScrollsInitialized(Unknown Source:18)
	at com.android.launcher3.PagedView.runOnPageScrollsInitialized(Unknown Source:11)
	at com.android.quickstep.AbsSwipeUpHandler.onGestureEnded(Unknown Source:92)
	at com.android.quickstep.OverviewCommandHelper$1.lambda$onRecentsAnimationStart$0(Unknown Source:6)
	at com.android.quickstep.OverviewCommandHelper$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at com.android.quickstep.BaseActivityInterface.runOnInitBackgroundStateUI(Unknown Source:18)
	at com.android.quickstep.OverviewCommandHelper$1.onRecentsAnimationStart(Unknown Source:9)
	at com.android.quickstep.RecentsAnimationCallbacks.lambda$onAnimationStart$1(Unknown Source:24)
	at com.android.quickstep.RecentsAnimationCallbacks.$r8$lambda$k9NzLXuJfw4Bgk7QL-CJoea1AH8(Unknown Source:0)
	at com.android.quickstep.RecentsAnimationCallbacks$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by arunv2518p** [comment]
> No log.

I found the error in logcat

2024-05-30 14:28:35.778 2608 2608 com.android.launcher3 E AbsSwipeUpHandler : RecentsView destination page is invalid
java.lang.IllegalStateException
at com.android.quickstep.AbsSwipeUpHandler.handleNormalGestureEnd(Unknown Source:208)
at com.android.quickstep.AbsSwipeUpHandler.lambda$onGestureEnded$13(Unknown Source:1)
at com.android.quickstep.AbsSwipeUpHandler.$r8$lambda$S5gvT_OU5trw50vDcnjp7h2UdIA(Unknown Source:0)
at com.android.quickstep.AbsSwipeUpHandler$$ExternalSyntheticLambda57.run(Unknown Source:8)
at com.android.launcher3.PagedView.onPageScrollsInitialized(Unknown Source:18)
at com.android.launcher3.PagedView.runOnPageScrollsInitialized(Unknown Source:11)
at com.android.quickstep.AbsSwipeUpHandler.onGestureEnded(Unknown Source:92)
at com.android.quickstep.OverviewCommandHelper$1.lambda$onRecentsAnimationStart$0(Unknown Source:6)
at com.android.quickstep.OverviewCommandHelper$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
at com.android.quickstep.BaseActivityInterface.runOnInitBackgroundStateUI(Unknown Source:18)
at com.android.quickstep.OverviewCommandHelper$1.onRecentsAnimationStart(Unknown Source:9)
at com.android.quickstep.RecentsAnimationCallbacks.lambda$onAnimationStart$1(Unknown Source:24)
at com.android.quickstep.RecentsAnimationCallbacks.$r8$lambda$k9NzLXuJfw4Bgk7QL-CJoea1AH8(Unknown Source:0)
at com.android.quickstep.RecentsAnimationCallbacks$$ExternalSyntheticLambda4.run(Unknown Source:4)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
