### ISSUE TITLE
bug: title (wallpaper and style are crashing)

### ISSUE THREAD

**Issue by yohanvaddi** [crdroidandroid/issue_tracker#431]
### Issue type

User interface

### Device

Redmi k20 pro(Raphael)

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-05-31

### Bug description

The thing is when I open wallpaper and style setting
Its crashing constantly when I wanted to customize

### Steps to reproduce

Step1:go to settings or press on home screen to go to wallpaper and style section
Step2:customize ui color theme And wallpapers

### Relevant log (logcat/build log)

```shell
time: 1717324010328
msg: java.lang.IllegalArgumentException: No enum constant com.android.systemui.monet.Style.MUTED
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.wallpaper/com.android.wallpaper.picker.CustomizationPickerActivity}: java.lang.IllegalArgumentException: No enum constant com.android.systemui.monet.Style.MUTED
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IllegalArgumentException: No enum constant com.android.systemui.monet.Style.MUTED
	at java.lang.Enum.valueOf(Enum.java:300)
	at com.android.systemui.monet.Style.valueOf(Unknown Source:2)
	at com.android.customization.picker.color.data.repository.ColorPickerRepositoryImpl.getCurrentColorOption(ColorPickerRepositoryImpl.kt:147)
	at com.android.customization.picker.color.data.repository.ColorPickerRepositoryImpl.<init>(ColorPickerRepositoryImpl.kt:49)
	at com.android.customization.module.ThemePickerInjector.getColorPickerInteractor(ThemePickerInjector.kt:420)
	at com.android.customization.module.ThemePickerInjector.getColorPickerSnapshotRestorer(ThemePickerInjector.kt:450)
	at com.android.customization.module.ThemePickerInjector.getSnapshotRestorers(ThemePickerInjector.kt:192)
	at com.android.wallpaper.module.WallpaperPicker2Injector.getUndoInteractor(WallpaperPicker2Injector.kt:297)
	at com.android.wallpaper.picker.CustomizationPickerActivity.onCreate(CustomizationPickerActivity.java:141)
	at android.app.Activity.performCreate(Activity.java:8785)
	at android.app.Activity.performCreate(Activity.java:8763)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1525)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3928)
	... 13 more
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/145264885/78653a1b-202c-4804-83cb-a0781626a14c

### Solution

Try to fix the issur that what I mentioned In above description
And I faced Another issue when I use fingerprint setup I can't see the setup process in above screenshot
![Screenshot_20240602-195106_Settings](https://github.com/crdroidandroid/issue_tracker/assets/145264885/24129298-6ea7-44a1-80bd-0fedbe969681)

### Additional context

Just give the updates time to time an d pls try to improve because similarly lots of Apps and games I'm facing the crashing issue frequently

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by yohanvaddi** [comment]
The 10.5 new update was worse than I think
