### ISSUE TITLE
Status bar icons option in Status Bar tab is crashing

### ISSUE THREAD

**Issue by gstjee** [crdroidandroid/issue_tracker#432]
### Issue type

Feature not working as intended

### Device

Dubai

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-05-30

### Bug description

when we click on Status bar icons then it is not opening and sometime it force close and generate bug report.

### Steps to reproduce

crDroid settings > STATUS BAR > click on 'Status bar icons'
it will not open further next screen but will immediately goes to main settings screen while sometime also shows system ui not responding force close popup with bug report.

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/cHYdMA

time: 1717353065872
msg: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_ACTION_BAR and set android:windowActionBar to false in your theme to use a Toolbar instead.
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.systemui/com.android.systemui.tuner.TunerActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_ACTION_BAR and set android:windowActionBar to false in your theme to use a Toolbar instead.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_ACTION_BAR and set android:windowActionBar to false in your theme to use a Toolbar instead.
	at android.app.Activity.setActionBar(Activity.java:3649)
	at com.android.settingslib.collapsingtoolbar.CollapsingToolbarBaseActivity.access$001(CollapsingToolbarBaseActivity.java:39)
	at com.android.settingslib.collapsingtoolbar.CollapsingToolbarBaseActivity$DelegateCallback.setActionBar(CollapsingToolbarBaseActivity.java:45)
	at com.android.settingslib.collapsingtoolbar.CollapsingToolbarDelegate.onCreateView(CollapsingToolbarDelegate.java:128)
	at com.android.settingslib.collapsingtoolbar.CollapsingToolbarDelegate.onCreateView(CollapsingToolbarDelegate.java:90)
	at com.android.settingslib.collapsingtoolbar.CollapsingToolbarBaseActivity.onCreate(CollapsingToolbarBaseActivity.java:68)
	at com.android.systemui.tuner.TunerActivity.onCreate(TunerActivity.java:60)
	at android.app.Activity.performCreate(Activity.java:8785)
	at android.app.Activity.performCreate(Activity.java:8763)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1525)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3928)
	... 13 more
```

### Screenshots or videos

![Screenshot_20240603-001404_Settings](https://github.com/crdroidandroid/issue_tracker/assets/127391704/14656db4-10df-4a62-abe9-7661c89573be)
![Screenshot_20240603-001557_Settings](https://github.com/crdroidandroid/issue_tracker/assets/127391704/a09780aa-1179-4ae9-9097-dd946d4eb615)

### Additional context

This was working fine on few days older build now suddenly with latest build it is crashing.

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unofficial devices can't get proper support due to no way of checking source code
anyway, try disabling any mods you have running and retry
