### ISSUE TITLE
bug: Crash on Lockscreen

### ISSUE THREAD

**Issue by CakesTwix** [crdroidandroid/issue_tracker#440]
### Issue type

User interface

### Device

OnePlus 11R (udon)
Lenovo Z5s (jd2019)
Xiaomi Mi Pad 4 (clover)

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-06-08

### Bug description

The ROM starts successfully, but when you disconnect and turn on - cyclically wants to draw the lockscreen
This problem does not exist on two devices - jd2019/clover

This bug was on 10.4 also no problem with clear LineageOS 21

### Steps to reproduce

1. Off display
2. On display

### Relevant log (logcat/build log)

```shell
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: Asking for redact notifs setting too early
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: java.lang.Throwable
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.systemui.statusbar.NotificationLockscreenUserManagerImpl.userAllowsPrivateNotificationsInPublic(NotificationLockscreenUserManagerImpl.java:549)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.google.android.systemui.NotificationLockscreenUserManagerGoogle.updateSmartSpaceVisibilitySettings(NotificationLockscreenUserManagerGoogle.java:94)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.google.android.systemui.statusbar.phone.CentralSurfacesGoogle.start(CentralSurfacesGoogle.java:363)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.systemui.SystemUIApplication.startStartable(SystemUIApplication.java:340)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.systemui.SystemUIApplication.startStartable(SystemUIApplication.java:331)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.systemui.SystemUIApplication.lambda$startServicesIfNeeded$0(SystemUIApplication.java:246)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.systemui.SystemUIApplication.$r8$lambda$sGiK2-9UovZrcCsIc_DAH_UDKow(SystemUIApplication.java:0)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.systemui.SystemUIApplication$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.systemui.SystemUIApplication.timeInitialization(SystemUIApplication.java:293)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:244)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:193)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.systemui.keyguard.KeyguardService.onCreate(KeyguardService.java:347)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4865)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2365)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at android.os.Looper.loopOnce(Looper.java:232)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at android.os.Looper.loop(Looper.java:317)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at android.app.ActivityThread.main(ActivityThread.java:8503)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
06-07 19:35:12.908  7046  7046 I LockscreenUserManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/57946485/40680887-63ad-4257-b261-f32558f475df

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
if you are submitting report for udon (I guess), then that is not supported officially so no way to work out any possible fixes
