### ISSUE TITLE
bug: Notifications panel animations are not smooth, laggy

### ISSUE THREAD

**Issue by MarkGree** [crdroidandroid/issue_tracker#456]
### Issue type

User interface

### Device

Device Redmi Note 7 Pro

### crDroid version

crDroid 10

### Exact version / Build date

Ex: 10.4/04-27-2024

### Bug description

Animations in the notfications panel (opening/expanding/closing) are not smooth, like playing in 12 fps. Sometimes they are smooth but I can't see they are if I open the panel from the desktop (the main launcher screen)

The animations in the launcher itself are smooth. Launched apps list animations are smooth as well.

### Steps to reproduce

Open the notifications panel (swipe down from top)

### Relevant log (logcat/build log)

```shell
Recent 20 seconds. I can provide more if you ask


06-25 00:54:14.976  2104  2129 W System  : A resource failed to call release.
06-25 00:54:14.976  2104  2129 W System  : A resource failed to call release.
06-25 00:54:14.976  2104  2129 W System  : A resource failed to call release.
06-25 00:54:14.977  2104  2129 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:14.977  2104  2129 W System  : A resource failed to call release.
06-25 00:54:14.977  2104  2129 W System  : A resource failed to call release.
06-25 00:54:14.977  2104  2129 W System  : A resource failed to call release.
06-25 00:54:16.025  3067  3067 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.mdisync.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
06-25 00:54:16.035  3067  3067 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.mobstore.service.START pkg=com.google.android.gms }
06-25 00:54:18.962  3067  3067 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.pay.service.BIND dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsApiService }
06-25 00:54:18.972  3067  3067 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.auth.cryptauth.cryptauthservice.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsBoundBrokerService }
06-25 00:54:20.914  1562  1562 D LoadedApk: Receiver not registered: com.android.server.UiModeManagerService$6@3b612a3
06-25 00:54:20.914  2361  2361 D QtiCarrierConfigHelper: WARNING, no carrier configs on phone Id: 0
06-25 00:54:20.914  1562  1562 I LineageHealth: Current mChargingStopReason: 0
06-25 00:54:20.919  2104  2104 D PowerNotificationWarningsGoogleImpl: onReceive: android.intent.action.BATTERY_CHANGED
06-25 00:54:20.923  2104  2104 D BatteryInfoBroadcast: onReceive: android.intent.action.BATTERY_CHANGED isPowerSaveMode: false
06-25 00:54:20.924  2104  2104 D BatteryDefenderNotification: isPlugged: true | isOverheated: false | defenderEnabled: false | isCharged: false
06-25 00:54:23.907  2883 16782 I Nearby  : (REDACTED) Beginning attempt #%d for %s...
06-25 00:54:23.911  2883 16782 W Nearby  : Failed attempt #3 out of 3 for RestoreDeviceName [CONTEXT service_id=49 ]
06-25 00:54:23.911  2883 16782 W Nearby  : java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@8ce8d995: getName
06-25 00:54:23.911  2883 16782 W Nearby  :      at android.os.Parcel.createExceptionOrNull(Parcel.java:3186)
06-25 00:54:23.911  2883 16782 W Nearby  :      at android.os.Parcel.createException(Parcel.java:3170)
06-25 00:54:23.911  2883 16782 W Nearby  :      at android.os.Parcel.readException(Parcel.java:3153)
06-25 00:54:23.911  2883 16782 W Nearby  :      at android.os.Parcel.readException(Parcel.java:3095)
06-25 00:54:23.911  2883 16782 W Nearby  :      at android.bluetooth.IBluetoothManager$Stub$Proxy.getName(IBluetoothManager.java:642)
06-25 00:54:23.911  2883 16782 W Nearby  :      at android.bluetooth.BluetoothAdapter.getName(BluetoothAdapter.java:1669)
06-25 00:54:23.911  2883 16782 W Nearby  :      at bbnn.j(:com.google.android.gms@242213038@24.22.13 (190400-638740827):11)
06-25 00:54:23.911  2883 16782 W Nearby  :      at bzxf.f(:com.google.android.gms@242213038@24.22.13 (190400-638740827):6)
06-25 00:54:23.911  2883 16782 W Nearby  :      at bzxf.e(:com.google.android.gms@242213038@24.22.13 (190400-638740827):16)
06-25 00:54:23.911  2883 16782 W Nearby  :      at bzxd.run(:com.google.android.gms@242213038@24.22.13 (190400-638740827):5)
06-25 00:54:23.911  2883 16782 W Nearby  :      at fdac.call(:com.google.android.gms@242213038@24.22.13 (190400-638740827):3)
06-25 00:54:23.911  2883 16782 W Nearby  :      at fdag.a(:com.google.android.gms@242213038@24.22.13 (190400-638740827):31)
06-25 00:54:23.911  2883 16782 W Nearby  :      at fdag.b(:com.google.android.gms@242213038@24.22.13 (190400-638740827):6)
06-25 00:54:23.911  2883 16782 W Nearby  :      at bzxe.run(:com.google.android.gms@242213038@24.22.13 (190400-638740827):33)
06-25 00:54:23.911  2883 16782 W Nearby  :      at java.lang.Thread.run(Thread.java:1012)
06-25 00:54:23.911  2883 16782 W Nearby  :      at anda.run(:com.google.android.gms@242213038@24.22.13 (190400-638740827):29)
06-25 00:54:23.911  2883 16782 W Nearby  :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
06-25 00:54:23.911  2883 16782 W Nearby  :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
06-25 00:54:23.911  2883 16782 W Nearby  :      at anis.run(:com.google.android.gms@242213038@24.22.13 (190400-638740827):8)
06-25 00:54:23.911  2883 16782 W Nearby  :      at java.lang.Thread.run(Thread.java:1012)
06-25 00:54:23.911  2883 16782 W Nearby  : Caused by: android.os.RemoteException: Remote stack trace:
06-25 00:54:23.911  2883 16782 W Nearby  :      at com.android.server.bluetooth.BtPermissionUtils.checkConnectPermissionForDataDelivery(BtPermissionUtils.java:99)
06-25 00:54:23.911  2883 16782 W Nearby  :      at com.android.server.bluetooth.BluetoothServiceBinder.getName(BluetoothServiceBinder.java:229)
06-25 00:54:23.911  2883 16782 W Nearby  :      at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:346)
06-25 00:54:23.911  2883 16782 W Nearby  :      at android.os.Binder.execTransactInternal(Binder.java:1496)
06-25 00:54:23.911  2883 16782 W Nearby  :      at android.os.Binder.execTransact(Binder.java:1440)
06-25 00:54:23.911  2883 16782 W Nearby  :
06-25 00:54:24.319  2104  2104 E FrameTracker: force finish cuj, time out: J<NOTIFICATION_SHADE_EXPAND_COLLAPSE::Expand>
06-25 00:54:27.297  1562  1883 W BatteryExternalStatsWorker: error reading Bluetooth stats: 9
06-25 00:54:29.077  2361  2361 D QtiCarrierConfigHelper: WARNING, no carrier configs on phone Id: 0
06-25 00:54:29.079  1562  1562 D LoadedApk: Receiver not registered: com.android.server.UiModeManagerService$6@3b612a3
06-25 00:54:29.080  1562  1562 I LineageHealth: Current mChargingStopReason: 0
06-25 00:54:29.083  1562  1562 D LoadedApk: Receiver not registered: com.android.server.UiModeManagerService$6@3b612a3
06-25 00:54:29.084  1562  1562 I LineageHealth: Current mChargingStopReason: 0
06-25 00:54:29.084  2361  2361 D QtiCarrierConfigHelper: WARNING, no carrier configs on phone Id: 0
06-25 00:54:29.084  2104  2104 D PowerNotificationWarningsGoogleImpl: onReceive: android.intent.action.BATTERY_CHANGED
06-25 00:54:29.090  2104  2104 D BatteryInfoBroadcast: onReceive: android.intent.action.BATTERY_CHANGED isPowerSaveMode: false
06-25 00:54:29.090  2104  2104 D BatteryDefenderNotification: isPlugged: true | isOverheated: false | defenderEnabled: false | isCharged: false
06-25 00:54:29.091  2104  2104 D PowerNotificationWarningsGoogleImpl: onReceive: android.intent.action.BATTERY_CHANGED
06-25 00:54:29.094  2104  2104 D BatteryInfoBroadcast: onReceive: android.intent.action.BATTERY_CHANGED isPowerSaveMode: false
06-25 00:54:29.094  2104  2104 D BatteryDefenderNotification: isPlugged: true | isOverheated: false | defenderEnabled: false | isCharged: false
06-25 00:54:29.266  1562  2150 D CoreBackPreview: startBackNavigation currentTask=Task{7fcf5b7 #8 type=home I=com.android.launcher3/.uioverrides.QuickstepLauncher}, topRunningActivity=ActivityRecord{c1294b6 u0 com.android.launcher3/.uioverrides.QuickstepLauncher t8}, callbackInfo=OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@f7577d1, mPriority=0, mIsAnimationCallback=false}, currentFocus=Window{daaec74 u0 com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}
06-25 00:54:29.267  2104  2152 D ShellBackPreview: Received backNavigationInfo:BackNavigationInfo{mType=TYPE_CALLBACK (4), mOnBackNavigationDone=android.os.RemoteCallback@5ba7bb, mOnBackInvokedCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@9c394d8, mPrepareRemoteAnimation=false, mAnimationCallback=false, mCustomizeAnimationInfo=null}
06-25 00:54:29.378  2104  2152 D ShellBackPreview: Finishing gesture with event action: 3
06-25 00:54:29.378  2104  2152 D ShellBackPreview: onGestureFinished() mTriggerBack == false
06-25 00:54:29.378  2104  2152 D ShellBackPreview: Trigger back without dispatching to animator.
06-25 00:54:29.378  2104  2152 D ShellBackPreview: BackAnimationController: finishBackNavigation()
06-25 00:54:29.379  1562  2150 D CoreBackPreview: onBackNavigationDone backType=4, triggerBack=false
06-25 00:54:29.396  2104  2528 D RingtonePlayer: stopAsync()
06-25 00:54:29.422  2104  2104 D VRI[NotificationShade]: Start draw after previous draw not visible
06-25 00:54:29.457   955   955 D vendor.qti.vibrator: Vibrator on for timeoutMs: 20
06-25 00:54:29.458   955 17483 D vendor.qti.vibrator: Starting on on another thread
06-25 00:54:29.476   955   955 D vendor.qti.vibrator: QTI Vibrator off
06-25 00:54:29.478   955 17483 D vendor.qti.vibrator: Notifying on complete
06-25 00:54:29.507   955   955 D vendor.qti.vibrator: QTI Vibrator off
06-25 00:54:29.528  1562  1947 D SystemServerTiming: getUserSwitchability-0
06-25 00:54:29.528  1562  1947 D SystemServerTiming: TM.isInCall
06-25 00:54:29.528  1562  2150 D SystemServerTiming: getUserSwitchability-0
06-25 00:54:29.528  1562  2150 D SystemServerTiming: TM.isInCall
06-25 00:54:29.577  1562  1947 D SystemServerTiming: hasUserRestriction-DISALLOW_USER_SWITCH
06-25 00:54:29.577  1562  1947 D SystemServerTiming: getInt-ALLOW_USER_SWITCHING_WHEN_SYSTEM_USER_LOCKED
06-25 00:54:29.577  1562  2150 D SystemServerTiming: hasUserRestriction-DISALLOW_USER_SWITCH
06-25 00:54:29.577  1562  2150 D SystemServerTiming: getInt-ALLOW_USER_SWITCHING_WHEN_SYSTEM_USER_LOCKED
06-25 00:54:29.577  1562  1947 D SystemServerTiming: isUserUnlocked-USER_SYSTEM
06-25 00:54:29.577  1562  2150 D SystemServerTiming: isUserUnlocked-USER_SYSTEM
06-25 00:54:29.585  2104  2104 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
06-25 00:54:29.598  2104  2104 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
06-25 00:54:29.621  2104  2104 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
06-25 00:54:29.625  2104  2104 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
06-25 00:54:29.626  2104  2104 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
06-25 00:54:29.626  2104  2104 D BiometricsRepositoryImpl: currentUser authFlags changed, new value: AuthenticationFlags(userId=0, flag=0)
06-25 00:54:29.673  1562  1643 I system_server: Background young concurrent copying GC freed 94MB AllocSpace bytes, 27(912KB) LOS objects, 72% free, 36MB/132MB, paused 1.099ms,281us total 200.314ms
06-25 00:54:29.694  2104  2220 D ControlsListingControllerImpl: Subscribing callback, service count: 0
06-25 00:54:29.723  2104  2220 E QuickAccessWalletKeyguardQuickAffordanceConfig: Wallet card retrieval error, message: "null"
06-25 00:54:29.742  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.743  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.743  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.745  1562  1645 W System  : A resource failed to call release.
06-25 00:54:29.746  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.746  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.747  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.749  1562  1645 W System  : A resource failed to call release.
06-25 00:54:29.750  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.750  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.751  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.753  1562  1645 W System  : A resource failed to call release.
06-25 00:54:29.754  2104  2220 D ControlsListingControllerImpl: Subscribing callback, service count: 0
06-25 00:54:29.756  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.757  1562  1645 W System  : A resource failed to call HardwareBuffer.close.
06-25 00:54:29.757  2104  2220 D ControlsListingControllerImpl: Subscribing callback, service count: 0
06-25 00:54:29.759  2104  2220 E QuickAccessWalletKeyguardQuickAffordanceConfig: Wallet card retrieval error, message: "null"
06-25 00:54:29.759  2104  2220 E QuickAccessWalletKeyguardQuickAffordanceConfig: Wallet card retrieval error, message: "null"
06-25 00:54:30.160  1562  1867 D ActivityManager: sync unfroze 16495 com.whatsapp for 3
06-25 00:54:30.181  3067 17485 I Authzen : [DeviceStateSyncManager] The server is in sync with current state. Nothing to do
06-25 00:54:30.248 16495 16502 I com.whatsapp: Method exceeds compiler instruction limit: 18806 in java.lang.Object X.8cS.A0f(java.lang.Integer, java.lang.Object, java.lang.Object)
06-25 00:54:30.300 16495 16502 I com.whatsapp: Method exceeds compiler instruction limit: 18806 in java.lang.Object X.8cS.A0f(java.lang.Integer, java.lang.Object, java.lang.Object)
06-25 00:54:30.733  1562  3602 D ActivityManager: sync unfroze 2719 com.android.permissioncontroller for 6
06-25 00:54:30.771  1562  2203 W ActivityManager: Background start not allowed: service Intent { act=com.whatsapp.messaging.MessageService.START cmp=com.whatsapp/.messaging.MessageService } to com.whatsapp/.messaging.MessageService from pid=16495 uid=10444 pkg=com.whatsapp startFg?=false
06-25 00:54:30.943  2883  2927 I ActiveUnlock: (REDACTED) StorageMediator database state changed from %s to %s
06-25 00:54:30.943  2883  2927 I ActiveUnlock: (REDACTED) StorageMediator database state changed from %s to %s
06-25 00:54:31.435  2104  2104 D VRI[NotificationShade]: Not drawing due to not visible
06-25 00:54:31.438  2104  2104 D ZenModeController: Removed callback class com.android.systemui.qs.tiles.DndTile$3
06-25 00:54:31.445  1562  5670 I ImeTracker: com.android.launcher3:75bf4fc8: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_SAME_WINDOW_FOCUSED_WITHOUT_EDITOR
06-25 00:54:31.446  1562  5670 I ImeTracker: com.android.launcher3:75bf4fc8: onCancelled at PHASE_SERVER_SHOULD_HIDE
06-25 00:54:31.448  2104  2220 D ControlsListingControllerImpl: Unsubscribing callback
06-25 00:54:31.448  2104  2220 D ControlsListingControllerImpl: Unsubscribing callback
06-25 00:54:31.454  2104  2220 D ControlsListingControllerImpl: Unsubscribing callback
06-25 00:54:31.461  2104  2220 D ControlsListingControllerImpl: Unsubscribing callback
```

### Additional context

NikGapps is installed, but I believe I tried to use the OS a bit (to see if it's working at all) and the issue was there before I reinstalled the system with GApps.

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by MarkGree** [comment]
Fixed by switching from CrDroid 10 to LineageOS 20
Also when I installed Lineage it required CN 12 firmware upgrade, while I was on CN v11 version of the firmware initally, so I upgraded it.
