### ISSUE TITLE
bug: unstable wifi connection may cause system crash

### ISSUE THREAD

**Issue by IIlIllIlll** [crdroidandroid/issue_tracker#469]
### Issue type

Other

### Device

Redmi note 8 pro (begonia)

### crDroid version

crDroid 10

### Exact version / Build date

10.6/2024-7-16

### Bug description

connect to a wifi which switches between 2.4G and 5G frequently will cause network crash, and the relevant setting page can not be accessed. Later the “Restart” option in the power menu is no longer functioning, which will only plays a semitransparent “restarting” animation. It can only be restarted by long-pressing the power button. About 10mins later it will suddenly play boot animation in loop.

### Steps to reproduce

1. create a bad condition for 5G signal (a room with door closed for example)
2. connect to a Dual-band wifi (5G/2.4G)
3. wait a few minutes

### Relevant log (logcat/build log)

```shell
07-21 02:28:57.910 I/[BIP]   ( 1229):  [BIP NL] event newlink match dev 0, interface index 32
07-21 02:28:57.910 I/[BIP]   ( 1229):  [BIP NL] the link status of interface(index:0) changes to 1
07-21 02:28:57.910 D/IpClient/wlan0( 1850): interfaceLinkStateChanged: ifindex 32 up
07-21 02:28:57.965 I/[BIP]   ( 1229):  [BIP NL] event newlink match dev 0, interface index 32
07-21 02:28:57.965 I/[BIP]   ( 1229):  [BIP NL] the link status of interface(index:0) changes to 1
07-21 02:28:57.965 D/IpClient/wlan0( 1850): interfaceLinkStateChanged: ifindex 32 up
07-21 02:28:57.991 I/[BIP]   ( 1229):  [BIP NL] event newlink match dev 0, interface index 32
07-21 02:28:57.991 I/[BIP]   ( 1229):  [BIP NL] the link status of interface(index:0) changes to 1
07-21 02:28:57.992 I/wpa_supplicant( 7145): assoc key_mgmt 0x2 network key_mgmt 0x142
07-21 02:28:57.993 I/[BIP]   ( 1229):  [BIP NL] event newlink match dev 0, interface index 32
07-21 02:28:57.993 I/[BIP]   ( 1229):  [BIP NL] the link status of interface(index:0) changes to 1
07-21 02:28:57.993 D/IpClient/wlan0( 1850): interfaceLinkStateChanged: ifindex 32 up
07-21 02:28:57.993 I/wpa_supplicant( 7145): wlan0: Associated with 80:8f:1d:f4:dd:d6
07-21 02:28:57.994 I/wpa_supplicant( 7145): wlan0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
07-21 02:28:57.994 D/IpClient/wlan0( 1850): interfaceLinkStateChanged: ifindex 32 up
07-21 02:28:57.995 I/WifiClientModeImpl[2355474:wlan0]( 1402): Update current security type to 2
07-21 02:28:57.996 E/ConnectivityService( 1402): BUG: NetworkAgentInfo{network{103}  handle{445787328525}  ni{WIFI CONNECTED extra: } created=2024-07-20T18:28:09.228Z Score(Policies : TRANSPORT_PRIMARY&EVER_EVALUATED&IS_UNMETERED&EVER_VALIDATED&IS_VALIDATED ; KeepConnected : 0)  created 2356886 firstValidated 2357169 lastValidated 2357169  lp{{InterfaceName: wlan0 LinkAddresses: [ fe80::e837:a8ff:feb2:7391/64,192.168.1.128/16 ] DnsAddresses: [ /114.114.114.114,/8.8.8.8 ] Domains: null MTU: 0 TcpBufferSizes: 1730560,3461120,6922240,524288,1048576,4525824 Routes: [ ff00::/8 -> :: wlan0 mtu 0,fe80::/64 -> :: wlan0 mtu 0,192.168.0.0/16 -> 0.0.0.0 wlan0 mtu 0,0.0.0.0/0 -> 192.168.1.1 wlan0 mtu 0 ]}}  nc{[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=12000Kbps LinkDnBandwidth>=30000Kbps Specifier: <WifiNetworkAgentSpecifier [WifiConfiguration=, SSID="TP-LINK_DDD6", BSSID=80:8f:1d:f4:dd:d8, band=2, mMatchLocalOnlySpecifiers=false]> TransportInfo: <SSID: "TP-LINK_DDD6", BSSID: 80:8f:1d:f4:dd:d8, MAC: <none>, IP: /192.168.1.128, Security type: 2, Supplicant state: COMPLETED, Wi-Fi standard: 11ac, RSSI: -67, Link speed: 433Mbps, Tx Link speed: 433Mbps, Max Supported Tx Link speed: 433Mbps, Rx Link speed: -1Mbps, Max Supported Rx Link speed: 433Mbps, Frequency: 5745MHz, Net ID: 0, Metered hint: false, score: 60, isUsable: true, CarrierMerged: false, SubscriptionId: -1, IsPrimary: 1, Trusted: true, Restricted: false, Ephemeral: false, OEM paid: false, OEM private: false, OSU AP: false, FQDN: <none>, Provider friendly name: <none>, Requesting package name: <none>"TP-LINK_DDD6"wpa2-pskMLO Information: , Is TID-To-Link negotiation supported by the AP: false, AP MLD Address: <none>, AP MLO Link Id: <none>, AP MLO Affiliated links: <none>, Vendor Data: <none>> SignalStrength: -67 OwnerUid: 1000 AdminUids: [1000] SSID: "TP-LINK_DDD6" UnderlyingNetworks: Null]}  factorySerialNumber=7} lost immutable capabilities:specifier changed: WifiNetworkAgentSpecifier [WifiConfiguration=, SSID="TP-LINK_DDD6", BSSID=80:8f:1d:f4:dd:d8, band=2, mMatchLocalOnlySpecifiers=false] -> WifiNetworkAgentSpecifier [WifiConfiguration=, SSID="TP-LINK_DDD6", BSSID=80:8f:1d:f4:dd:d8, band=1, mMatchLocalOnlySpecifiers=false]
07-21 02:28:57.999 W/ContextImpl( 1402): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendStickyBroadcast:1627 com.android.server.wifi.ClientModeImpl.sendNetworkChangeBroadcast:3115 com.android.server.wifi.ClientModeImpl.lambda$sendNetworkChangeBroadcastWithCurrentState$14:3092 com.android.server.wifi.ClientModeImpl.$r8$lambda$mtuS9ulugUkTxNA_sDDnAioo66w:0 com.android.server.wifi.ClientModeImpl$$ExternalSyntheticLambda13.send:0 
07-21 02:28:57.999 D/ConnectivityService( 1402): NetReassign [no changes] [c 0] [a 1] [i 0]
07-21 02:28:58.001 W/AlarmManager( 1402): Unrecognized alarm listener com.android.server.wifi.WifiServiceImpl$1@4358a25
07-21 02:28:58.013 I/[epdg_wo]( 1246): [WOA] wo_msg_sensitive_print: [wowifi=0,"wlan0","","***","***","54502d4c494e4b5f44444436"](82)
07-21 02:28:58.013 I/[epdg_wo]( 1246): [WOA] wo_msg_sensitive_print: [wowifi:0,0](10)
07-21 02:28:58.186 I/wpa_supplicant( 7145): wlan0: WPA: RX message 1 of 4-Way Handshake from 80:8f:1d:f4:dd:d6 (ver=2)
07-21 02:28:58.187 I/wpa_supplicant( 7145): assoc key_mgmt 0x2 network key_mgmt 0x142
07-21 02:28:58.187 I/wpa_supplicant( 7145): wlan0: WPA: Sending EAPOL-Key 2/4
07-21 02:28:58.188 I/WifiClientModeImpl[2355474:wlan0]( 1402): Update current security type to 2
07-21 02:28:58.188 E/ConnectivityService( 1402): BUG: NetworkAgentInfo{network{103}  handle{445787328525}  ni{WIFI CONNECTED extra: } created=2024-07-20T18:28:09.228Z Score(Policies : TRANSPORT_PRIMARY&EVER_EVALUATED&IS_UNMETERED&EVER_VALIDATED&IS_VALIDATED ; KeepConnected : 0)  created 2356886 firstValidated 2357169 lastValidated 2357169  lp{{InterfaceName: wlan0 LinkAddresses: [ fe80::e837:a8ff:feb2:7391/64,192.168.1.128/16 ] DnsAddresses: [ /114.114.114.114,/8.8.8.8 ] Domains: null MTU: 0 TcpBufferSizes: 1730560,3461120,6922240,524288,1048576,4525824 Routes: [ ff00::/8 -> :: wlan0 mtu 0,fe80::/64 -> :: wlan0 mtu 0,192.168.0.0/16 -> 0.0.0.0 wlan0 mtu 0,0.0.0.0/0 -> 192.168.1.1 wlan0 mtu 0 ]}}  nc{[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=12000Kbps LinkDnBandwidth>=30000Kbps Specifier: <WifiNetworkAgentSpecifier [WifiConfiguration=, SSID="TP-LINK_DDD6", BSSID=80:8f:1d:f4:dd:d8, band=1, mMatchLocalOnlySpecifiers=false]> TransportInfo: <SSID: "TP-LINK_DDD6", BSSID: 00:00:00:00:00:00, MAC: <none>, IP: /192.168.1.128, Security type: 2, Supplicant state: ASSOCIATED, Wi-Fi standard: 11n, RSSI: -67, Link speed: 433Mbps, Tx Link speed: 433Mbps, Max Supported Tx Link speed: 150Mbps, Rx Link speed: -1Mbps, Max Supported Rx Link speed: 150Mbps, Frequency: 2462MHz, Net ID: 0, Metered hint: false, score: 59, isUsable: true, CarrierMerged: false, SubscriptionId: -1, IsPrimary: 1, Trusted: true, Restricted: false, Ephemeral: false, OEM paid: false, OEM private: false, OSU AP: false, FQDN: <none>, Provider friendly name: <none>, Requesting package name: <none>"TP-LINK_DDD6"wpa2-pskMLO Information: , Is TID-To-Link negotiation supported by the AP: false, AP MLD Address: <none>, AP MLO Link Id: <none>, AP MLO Affiliated links: <none>, Vendor Data: <none>> SignalStrength: -67 OwnerUid: 1000 AdminUids: [1000] SSID: "TP-LINK_DDD6" UnderlyingNetworks: Null]}  factorySerialNumber=7} lost immutable capabilities:specifier changed: WifiNetworkAgentSpecifier [WifiConfiguration=, SSID="TP-LINK_DDD6", BSSID=80:8f:1d:f4:dd:d8, band=1, mMatchLocalOnlySpecifiers=false] -> WifiNetworkAgentSpecifier [WifiConfiguration=, SSID="TP-LINK_DDD6", BSSID=80:8f:1d:f4:dd:d6, band=1, mMatchLocalOnlySpecifiers=false]
07-21 02:28:58.191 D/ConnectivityService( 1402): NetReassign [no changes] [c 0] [a 0] [i 1]
07-21 02:28:58.262 I/wpa_supplicant( 7145): wlan0: RSN: RX message 3 of 4-Way Handshake from 80:8f:1d:f4:dd:d6 (ver=2)
07-21 02:28:58.262 I/wpa_supplicant( 7145): wlan0: WPA: Sending EAPOL-Key 4/4
07-21 02:28:58.263 I/wpa_supplicant( 7145): assoc key_mgmt 0x2 network key_mgmt 0x142
07-21 02:28:58.264 I/wpa_supplicant( 7145): wlan0: WPA: Key negotiation completed with 80:8f:1d:f4:dd:d6 [PTK=CCMP GTK=CCMP]
07-21 02:28:58.264 I/wpa_supplicant( 7145): wlan0: CTRL-EVENT-CONNECTED - Connection to 80:8f:1d:f4:dd:d6 completed [id=0 id_str=%7B%22configKey%22%3A%22%5C%22TP-LINK_DDD6%5C%22WPA_PSK%22%2C%22creatorUid%22%3A%221000%22%7D]
07-21 02:28:58.264 I/wpa_supplicant( 7145): assoc key_mgmt 0x2 network key_mgmt 0x142
07-21 02:28:58.264 D/IpClient/wlan0( 1850): interfaceLinkStateChanged: ifindex 32 up
07-21 02:28:58.264 I/[BIP]   ( 1229):  [BIP NL] event newlink match dev 0, interface index 32
07-21 02:28:58.264 I/[BIP]   ( 1229):  [BIP NL] the link status of interface(index:0) changes to 1
07-21 02:28:58.264 I/WifiClientModeImpl[2355474:wlan0]( 1402): Update current security type to 2
07-21 02:28:58.267 I/WifiClientModeImpl[2355474:wlan0]( 1402): Update current security type to 2 from network connection event.
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): ISupplicantStaIface.getMacAddress failed with service specific exception: 
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): android.os.ServiceSpecificException:  (code 1)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3201)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at android.os.Parcel.createException(Parcel.java:3171)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at android.os.Parcel.readException(Parcel.java:3154)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at android.os.Parcel.readException(Parcel.java:3096)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at com.android.wifi.x.android.hardware.wifi.supplicant.ISupplicantStaIface$Stub$Proxy.getMacAddress(ISupplicantStaIface.java:1154)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at com.android.server.wifi.SupplicantStaIfaceHalAidlImpl.getMacAddress(SupplicantStaIfaceHalAidlImpl.java:1755)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at com.android.server.wifi.SupplicantStaIfaceHal.getMacAddress(SupplicantStaIfaceHal.java:1598)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at com.android.server.wifi.WifiNative.getMacAddress(WifiNative.java:2509)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at com.android.server.wifi.ClientModeImpl$L2ConnectedState.processMessageImpl(ClientModeImpl.java:6622)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at com.android.server.wifi.RunnerState.processMessage(RunnerState.java:67)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at com.android.wifi.x.com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:1001)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at com.android.wifi.x.com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:819)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at android.os.Looper.loopOnce(Looper.java:232)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at android.os.Looper.loop(Looper.java:317)
07-21 02:28:58.267 E/SupplicantStaIfaceHalAidlImpl( 1402): 	at android.os.HandlerThread.run(HandlerThread.java:85)
07-21 02:28:58.268 I/ApplicationQosPolicyRequestHandler( 1402): Queueing all policies on iface=wlan0. numPolicies=0
```

### Solution

reboot

### Additional context

i have encountered this problem since crd9.7
crd9.6 works fine but all newer version have the same issue

i really dont know if the relevant log i submitted is helpful, so full log below
[2024-07-21-02-28-27.txt](https://github.com/user-attachments/files/16322437/2024-07-21-02-28-27.txt)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
dropped device
