### ISSUE TITLE
bug: android auto permissions crash

### ISSUE THREAD

**Issue by aliaksei135** [crdroidandroid/issue_tracker#47]
### Issue type

Feature not working as intended

### Device

POCO X3 NFC (Surya)

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

Android auto splash screen comes up on connection to car then disappears back to previous activity. 
Multiple gapps packages tried with same results.

### Steps to reproduce

Connect to car with approved cable

### Relevant log (logcat/build log)

```shell
Error during IPC
java.lang.SecurityException: Application must hold android.permission.REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION to associate with a device with android.app.role.SYSTEM_AUTOMOTIVE_PROJECTION profile.
	at com.android.server.companion.PermissionsUtils.enforceRequestDeviceProfilePermissions(PermissionsUtils.java:93)
	at com.android.server.companion.PermissionsUtils.enforcePermissionsForAssociation(PermissionsUtils.java:74)
	at com.android.server.companion.AssociationRequestsProcessor.processNewAssociationRequest(AssociationRequestsProcessor.java:167)
	at com.android.server.companion.CompanionDeviceManagerService$CompanionDeviceManagerImpl.associate(CompanionDeviceManagerService.java:459)
	at android.companion.ICompanionDeviceManager$Stub.onTransact(ICompanionDeviceManager.java:220)
	at com.android.server.companion.CompanionDeviceManagerService$CompanionDeviceManagerImpl.onTransact(CompanionDeviceManagerService.java:443)
	at android.os.Binder.execTransactInternal(Binder.java:1283)
	at android.os.Binder.execTransact(Binder.java:1227)
```

### Solution

It appears that `android.permission.REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION` is a newly added permission for API level 33 [per here](https://developer.android.com/reference/android/Manifest.permission?hl=en#REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION) .

### Additional context

 I have tried to force this onto the package manually using TeMeFi, but cannot find the permission available in the list of available permissions to apply. 

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
This issue is part of gapps and not of our source
