### ISSUE TITLE
bug: garnet xiaomi parts and phone service crash

### ISSUE THREAD

**Issue by BlackLotus** [crdroidandroid/issue_tracker#487]
### Issue type

Feature not working as intended

### Device

Redmi note 13 Pro 5g (garnet)

### crDroid version

crDroid 10

### Exact version / Build date

AP2A.240805.005
Build date 2024-08-15

### Bug description

com.qti.phone crashes and xiaomi parts crashes
Can initiate calls but neither side can hear each other.
Xiaomi Parts started crashing in the release 5 days or so earlier

### Steps to reproduce

Update
Start your phone

### Relevant log (logcat/build log)

```shell
FATAL EXCEPTION: main
Process: com.qti.phone, PID: 31312
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qti/extphone/IExtPhone$Stub;
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:74)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4884)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2407)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.ClassNotFoundException: com.qti.extphone.IExtPhone$Stub
	... 13 more
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by BlackLotus** [comment]
I reflashed stock global 1.0.6.0
Reflashed also the newest crDroid image 20240816 and now only xiaomi parts crashes
`whenI
FATAL EXCEPTION: main
Process: org.lineageos.settings, PID: 3069
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.SCREEN_ON flg=0x50200010 } in org.lineageos.settings.thermal.ThermalService$1@8a8e062
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1817)
	at android.app.LoadedApk$ReceiverDispatcher$Args.$r8$lambda$mcNAAl1SQ4MyJPyDg8TJ2x2h0Rk(Unknown Source:0)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=6; index=6
	at org.lineageos.settings.thermal.ThermalUtils.setThermalProfile(ThermalUtils.java:187)
	at org.lineageos.settings.thermal.ThermalService.setThermalProfile(ThermalService.java:90)
	at org.lineageos.settings.thermal.ThermalService.-$$Nest$msetThermalProfile(ThermalService.java:0)
	at org.lineageos.settings.thermal.ThermalService$1.onReceive(ThermalService.java:51)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1809)
	... 10 more
```
It crashes when I put the phone in "standby" and it crashes before I unlock it

**Comment by JYRRC** [comment]
True, I apologize for the problems caused, there is a new update from August 16 with the error solved, I had a problem with the sound, thank you an d sorry again,thanks for install crdroid
