### ISSUE TITLE
Error granting/upgrading runtime permissions for user 0

### ISSUE THREAD

**Issue by EAZYBLACK** [crdroidandroid/issue_tracker#491]
### Issue type

Source code related

### Device

gtaxllte (unofficial)

### crDroid version

crDroid 9

### Exact version / Build date

9.19 20/8/24

### Bug description

stuck at boot animation

### Steps to reproduce

build crdroid 9 and boot it

### Relevant log (logcat/build log)

```shell
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: Error granting or upgrading runtime permissions
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: java.util.concurrent.CancellationException
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2372)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at com.android.internal.infra.AndroidFuture.cancel(AndroidFuture.java:153)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at com.android.internal.infra.ServiceConnector$Impl$CompletionAwareJob.cancel(ServiceConnector.java:775)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at com.android.internal.infra.ServiceConnector$Impl.cancelPendingJobs(ServiceConnector.java:608)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at com.android.internal.infra.ServiceConnector$Impl.unbindJobThread(ServiceConnector.java:593)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at com.android.internal.infra.ServiceConnector$Impl$$ExternalSyntheticLambda1.run(Unknown Source:2)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at android.os.Handler.handleCallback(Handler.java:942)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at android.os.Looper.loopOnce(Looper.java:201)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at android.os.Looper.loop(Looper.java:288)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-20 14:35:53.413  2785  2809 E PermissionControllerManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
08-20 14:35:53.413  2785  2809 E PermissionPolicyService: Error granting/upgrading runtime permissions for user 0
08-20 14:35:53.414  2785  2785 E System  : ******************************************
08-20 14:35:53.414  2785  2785 E System  : ************ Failure starting system services
08-20 14:35:53.414  2785  2785 E System  : java.lang.RuntimeException: Failed to boot service com.android.server.policy.PermissionPolicyService: onBootPhase threw an exception during phase 550
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:297)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.SystemServer.lambda$startOtherServices$5(SystemServer.java:2869)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.SystemServer.$r8$lambda$cHpru_0zTEigJU4rvGBr8u7hU4w(Unknown Source:0)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.SystemServer$$ExternalSyntheticLambda5.run(Unknown Source:28)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.am.ActivityManagerService.systemReady(ActivityManagerService.java:8216)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:2866)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:955)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:665)
08-20 14:35:53.414  2785  2785 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:551)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
08-20 14:35:53.414  2785  2785 E System  : Caused by: java.lang.IllegalStateException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Error granting/upgrading runtime permissions for user 0
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.policy.PermissionPolicyService.grantOrUpgradeDefaultRuntimePermissionsIfNeeded(PermissionPolicyService.java:607)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.policy.PermissionPolicyService.onStartUser(PermissionPolicyService.java:537)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.policy.PermissionPolicyService.onBootPhase(PermissionPolicyService.java:407)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.SystemServiceManager.startBootPhase(SystemServiceManager.java:294)
08-20 14:35:53.414  2785  2785 E System  : 	... 10 more
08-20 14:35:53.414  2785  2785 E System  : Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Error granting/upgrading runtime permissions for user 0
08-20 14:35:53.414  2785  2785 E System  : 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:371)
08-20 14:35:53.414  2785  2785 E System  : 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1975)
08-20 14:35:53.414  2785  2785 E System  : 	at com.android.server.policy.PermissionPolicyService.grantOrUpgradeDefaultRuntimePermissionsIfNeeded(PermissionPolicyService.java:605)
08-20 14:35:53.414  2785  2785 E System  : 	... 13 more
```

### Additional context

same trees work on lineage but not on crdroid

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by EAZYBLACK** [comment]
sorry for making this issue, crdroid builds and works in my other device so thats likely device issue
