### ISSUE TITLE
"Always" button greyed out when choosing which app to open a file with

### ISSUE THREAD

**Issue by quickishfm** [crdroidandroid/issue_tracker#498]
### Issue type

User interface

### Device

Oneplus 7 Pro

### crDroid version

crDroid 10

### Exact version / Build date

10.7 (2024-08-24)

### Bug description

The "Always" option is greyed out when opening a file that has multiple suitable apps that can open it.

### Steps to reproduce

1) Open any file such as an image or video, e.g. from a file manager
2) The dialog that comes up listing apps that can be used has only the "Just once" option available. "Always" button is visible but greyed out.

### Relevant log (logcat/build log)

```shell
Logcat of when I press a file to open the dialog


08-25 18:50:54.268  1604  5528 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=content://com.android.externalstorage.documents/... typ=image/jpeg flg=0x20000003 cmp=android/com.android.internal.app.ResolverActivity} with LAUNCH_MULTIPLE from uid 10335 (BAL_ALLOW_VISIBLE_WINDOW) result code=0
08-25 18:50:54.268  2798  2845 V WindowManagerShell: Transition requested (#423): android.os.BinderProxy@70664d0 TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=10295 displayId=0 isRunning=true baseIntent=Intent { dat= flg=0x10280000 cmp=com.android.documentsui/.files.FilesActivity } baseActivity=ComponentInfo{com.android.documentsui/com.android.documentsui.files.FilesActivity} topActivity=ComponentInfo{android/com.android.internal.app.ResolverActivity} origActivity=null realActivity=ComponentInfo{com.android.documentsui/com.android.documentsui.files.FilesActivity} numActivities=2 lastActiveTime=18098392 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@9507cc9} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=null topActivityInfo=ActivityInfo{9c08fce com.android.internal.app.ResolverActivity} launchCookies=[] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=true appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1440 topActivityLetterboxHeight=3120 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 423 }
08-25 18:50:54.287  1604  5528 D IntervalStats: Unable to parse usage stats packages: [968]


08-25 18:50:54.340 26683 27938 D AbstractResolverComp: Setting watchdog timer for 500ms
08-25 18:50:54.356  1604  5528 D CoreBackPreview: Window{be0bfbc u0 android/com.android.internal.app.ResolverActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@359d29a, mPriority=0, mIsAnimationCallback=false}
08-25 18:50:54.363 26683 26698 I AdrenoGLES-0: QUALCOMM build                   : eaa701cd06, I183f6321f0
08-25 18:50:54.363 26683 26698 I AdrenoGLES-0: Build Date                       : 10/27/22
08-25 18:50:54.363 26683 26698 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.35.01.12
08-25 18:50:54.363 26683 26698 I AdrenoGLES-0: Local Branch                     : 
08-25 18:50:54.363 26683 26698 I AdrenoGLES-0: Remote Branch                    : 
08-25 18:50:54.363 26683 26698 I AdrenoGLES-0: Remote Branch                    : 
08-25 18:50:54.363 26683 26698 I AdrenoGLES-0: Reconstruct Branch               : 
08-25 18:50:54.363 26683 26698 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
08-25 18:50:54.363 26683 26698 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
08-25 18:50:54.368 26683 26698 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
08-25 18:50:54.386 26683 26683 D AbstractResolverComp: RANKER_SERVICE_RESULT
08-25 18:50:54.389  2798  2845 V WindowManagerShell: onTransitionReady (#423) android.os.BinderProxy@70664d0: {id=423 t=OPEN f=0x0 trk=0 opt={t=FROM_STYLE} r=[0@Point(0, 0)] c=[{null m=OPEN f=TRANSLUCENT|FILLS_TASK leash=Surface(name=ActivityRecord{2936b92 u0 android/com.android.internal.app.ResolverActivity t10295})/@0xa222eef sb=Rect(0, 0 - 0, 0) eb=Rect(0, 0 - 1440, 3120) d=-1->0 r=-1->0:-1 component=android/com.android.internal.app.ResolverActivity}]}
08-25 18:50:54.389  2798  2845 V WindowManagerShell: Playing animation for (#423) android.os.BinderProxy@70664d0@0
08-25 18:50:54.389  2798  2845 V WindowManagerShell:  try handler com.android.wm.shell.transition.DefaultMixedHandler@4b84e66
08-25 18:50:54.389  2798  2845 V WindowManagerShell:  try handler com.android.wm.shell.keyguard.KeyguardTransitionHandler@340a5a7
08-25 18:50:54.389  2798  2845 V WindowManagerShell:  try handler com.android.wm.shell.pip.PipTransition@f038ab2
08-25 18:50:54.389  2798  2845 V WindowManagerShell:  try handler com.android.wm.shell.activityembedding.ActivityEmbeddingController@707a03
08-25 18:50:54.389  2798  2845 V WindowManagerShell:  try handler com.android.wm.shell.recents.RecentsTransitionHandler@6630d80
08-25 18:50:54.389  2798  2845 V ShellRecents: RecentsTransitionHandler.startAnimation: no controller found
08-25 18:50:54.389  2798  2845 V WindowManagerShell:  try handler com.android.wm.shell.splitscreen.StageCoordinator@65bda72
08-25 18:50:54.389  2798  2845 V WindowManagerShell:  try handler com.android.wm.shell.transition.RemoteTransitionHandler@749efb9
08-25 18:50:54.389  2798  2845 V WindowManagerShell: Transition doesn't have explicit remote, search filters for match for {id=423 t=OPEN f=0x0 trk=0 opt={t=FROM_STYLE} r=[0@Point(0, 0)] c=[{null m=OPEN f=TRANSLUCENT|FILLS_TASK leash=Surface(name=ActivityRecord{2936b92 u0 android/com.android.internal.app.ResolverActivity t10295})/@0xa222eef sb=Rect(0, 0 - 0, 0) eb=Rect(0, 0 - 1440, 3120) d=-1->0 r=-1->0:-1 component=android/com.android.internal.app.ResolverActivity}]}
08-25 18:50:54.389  2798  2845 V WindowManagerShell:  Checking filter Pair{{types=[] flags=0x0] notFlags=0x100 checks=[{atype=home independent=true modes=[OPEN,TO_FRONT] flags=NONE mustBeTask=false order=TOP topActivity=ComponentInfo{com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}},{atype=standard independent=true modes=[CLOSE,TO_BACK] flags=NONE mustBeTask=false order=ANY topActivity=null}]} RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@c2ffda2, appThread = android.app.IApplicationThread$Stub$Proxy@d028a33, debugName = QuickstepLaunchHome }}
08-25 18:50:54.389  2798  2845 V WindowManagerShell:  Delegate animation for (#423) to null
08-25 18:50:54.389  2798  2845 V WindowManagerShell:  try handler com.android.wm.shell.transition.DefaultTransitionHandler@39b9ffe
08-25 18:50:54.389  2798  2845 V WindowManagerShell: start default transition animation, info = {id=423 t=OPEN f=0x0 trk=0 opt={t=FROM_STYLE} r=[0@Point(0, 0)] c=[{null m=OPEN f=TRANSLUCENT|FILLS_TASK leash=Surface(name=ActivityRecord{2936b92 u0 android/com.android.internal.app.ResolverActivity t10295})/@0xa222eef sb=Rect(0, 0 - 0, 0) eb=Rect(0, 0 - 1440, 3120) d=-1->0 r=-1->0:-1 component=android/com.android.internal.app.ResolverActivity}]}
08-25 18:50:54.390  2798  2845 V WindowManagerShell: loadAnimation: anim=android.view.animation.AnimationSet@38ccb0b animAttr=0x4 type=OPEN isEntrance=true
08-25 18:50:54.391  2798  2845 V WindowManagerShell:  animated by com.android.wm.shell.transition.DefaultTransitionHandler@39b9ffe
08-25 18:50:54.391  1604  1806 I ActivityTaskManager: Displayed android/com.android.internal.app.ResolverActivity for user 0: +130ms
08-25 18:50:54.391  1604  1806 V WindowManager: Sent Transition (#423) createdAt=08-25 18:50:54.262 via request=TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=10295 displayId=0 isRunning=true baseIntent=Intent { dat= flg=0x10280000 cmp=com.android.documentsui/.files.FilesActivity } baseActivity=ComponentInfo{com.android.documentsui/com.android.documentsui.files.FilesActivity} topActivity=ComponentInfo{android/com.android.internal.app.ResolverActivity} origActivity=null realActivity=ComponentInfo{com.android.documentsui/com.android.documentsui.files.FilesActivity} numActivities=2 lastActiveTime=18098392 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{c1a9def Task{8b28b34 #10295 type=standard A=10335:com.android.documentsui}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=null topActivityInfo=ActivityInfo{62f129f com.android.internal.app.ResolverActivity} launchCookies=[] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=true appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1440 topActivityLetterboxHeight=3120 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 423 }
08-25 18:50:54.391  1604  1806 V WindowManager:     startWCT=WindowContainerTransaction { changes = {} hops = [] errorCallbackToken=null taskFragmentOrganizer=null }
08-25 18:50:54.392  1604  1806 V WindowManager:     info={id=423 t=OPEN f=0x0 trk=0 opt={t=FROM_STYLE} r=[0@Point(0, 0)] c=[
08-25 18:50:54.392  1604  1806 V WindowManager:         {null m=OPEN f=TRANSLUCENT|FILLS_TASK leash=Surface(name=ActivityRecord{2936b92 u0 android/com.android.internal.app.ResolverActivity t10295})/@0xea56543 sb=Rect(0, 0 - 0, 0) eb=Rect(0, 0 - 1440, 3120) d=-1->0 r=-1->0:-1 component=android/com.android.internal.app.ResolverActivity}
08-25 18:50:54.392  1604  1806 V WindowManager:     ]}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{org.fossify.gallery/org.fossify.gallery.activities.PhotoActivity}, intent component: ComponentInfo{org.fossify.gallery/org.fossify.gallery.activities.PhotoActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.rcreations.WebCamViewerPaid/com.rcreations.WebCamViewerPaid.EditCameraActivity}, intent component: ComponentInfo{com.rcreations.WebCamViewerPaid/com.rcreations.WebCamViewerPaid.EditCameraActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.mixplorer/com.mixplorer.activities.CopyActivity}, intent component: ComponentInfo{com.mixplorer/com.mixplorer.activities.CopyActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.mixplorer/com.mixplorer.activities.ImageViewerActivity}, intent component: ComponentInfo{com.mixplorer/com.mixplorer.activities.ImageViewerActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{org.lineageos.glimpse/org.lineageos.glimpse.ViewActivity}, intent component: ComponentInfo{org.lineageos.glimpse/org.lineageos.glimpse.ViewActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.camerasideas.instashot/com.camerasideas.instashot.ShareImageActivity}, intent component: ComponentInfo{com.camerasideas.instashot/com.camerasideas.instashot.ShareImageActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.camerasideas.trimmer/com.camerasideas.instashot.ShareEntryActivity}, intent component: ComponentInfo{com.camerasideas.trimmer/com.camerasideas.instashot.ShareEntryActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.viewer.comicscreen/com.viewer.comicscreen.ImgActivity}, intent component: ComponentInfo{com.viewer.comicscreen/com.viewer.comicscreen.ImgActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.simplemobiletools.draw.pro/com.simplemobiletools.draw.pro.activities.MainActivity}, intent component: ComponentInfo{com.simplemobiletools.draw.pro/com.simplemobiletools.draw.pro.activities.MainActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{nextapp.fx/nextapp.fx.ui.viewer.image.ImageViewerActivity}, intent component: ComponentInfo{nextapp.fx/nextapp.fx.ui.viewer.image.ImageViewerActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.intercept.ActivityInterceptor}, intent component: ComponentInfo{io.github.muntashirakon.AppManager/io.github.muntashirakon.AppManager.intercept.ActivityInterceptor}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.xiaomi.smarthome/com.xiaomi.smarthome.printer.SendPrintActivity}, intent component: ComponentInfo{com.xiaomi.smarthome/com.xiaomi.smarthome.printer.SendPrintActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{universe.constellation.orion.viewer/universe.constellation.orion.viewer.OrionViewerActivity}, intent component: ComponentInfo{universe.constellation.orion.viewer/universe.constellation.orion.viewer.OrionViewerActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.pixlr.express/com.pixlr.express.ui.editor.EditorActivity}, intent component: ComponentInfo{com.pixlr.express/com.pixlr.express.ui.editor.EditorActivity}
08-25 18:50:54.392 26683 26683 I ResolverListAdapter: Add DisplayResolveInfo component: ComponentInfo{com.termux/com.termux.filepicker.TermuxFileReceiverActivity}, intent component: ComponentInfo{com.termux/com.termux.filepicker.TermuxFileReceiverActivity}
08-25 18:50:54.393  1604 10716 W UserManagerService: Requested status bar icon for non-badged user 0
08-25 18:50:54.394  1604 10716 D ConnectivityService: requestNetwork for uid/pid:10404/2798 asUid: 1000 activeRequest: null callbackRequest: 1688 [NetworkRequest [ REQUEST id=1689, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 1000 RequestorUid: 10404 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
08-25 18:50:54.399  1604  2687 D WifiNetworkFactory: got request NetworkRequest [ REQUEST id=1689, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 1000 RequestorUid: 10404 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]
08-25 18:50:54.399  1604  2687 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1689, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 1000 RequestorUid: 10404 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]
08-25 18:50:54.399  1604  2687 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1689, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 1000 RequestorUid: 10404 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]
08-25 18:50:54.400  1604  2687 D MultiInternetWifiNetworkFactory: got request NetworkRequest [ REQUEST id=1689, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 1000 RequestorUid: 10404 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]
08-25 18:50:54.400  1604  2696 D ConnectivityService: NetReassign [1689 : null → 102] [c 1] [a 1] [i 3]
08-25 18:50:54.416  1604 10716 I ImeTracker: android:e573fa69: onRequestHide at ORIGIN_SERVER reason HIDE_UNSPECIFIED_WINDOW fromUser false
08-25 18:50:54.416  1604 10716 I ImeTracker: android:e573fa69: onCancelled at PHASE_SERVER_SHOULD_HIDE
08-25 18:50:54.440  3767  3767 W C       : onStartInput event aborted
08-25 18:50:54.440  3767  3767 W C       : Al.w: could not obtain extracted text
08-25 18:50:54.440  3767  3767 W C       : 	at Al.S.H(SourceFile:341)
08-25 18:50:54.440  3767  3767 W C       : 	at Al.C.b0(SourceFile:127)
08-25 18:50:54.440  3767  3767 W C       : 	at si.x.s(SourceFile:216)
08-25 18:50:54.440  3767  3767 W C       : 	at si.y0.s(SourceFile:5)
08-25 18:50:54.440  3767  3767 W C       : 	at com.touchtype.KeyboardService.onStartInput(SourceFile:7)
08-25 18:50:54.440  3767  3767 W C       : 	at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:3364)
08-25 18:50:54.440  3767  3767 W C       : 	at android.inputmethodservice.InputMethodService$InputMethodImpl.startInput(InputMethodService.java:862)
08-25 18:50:54.440  3767  3767 W C       : 	at android.inputmethodservice.InputMethodService$InputMethodImpl.dispatchStartInput(InputMethodService.java:891)
08-25 18:50:54.440  3767  3767 W C       : 	at android.inputmethodservice.IInputMethodWrapper.executeMessage(IInputMethodWrapper.java:201)
08-25 18:50:54.440  3767  3767 W C       : 	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
08-25 18:50:54.440  3767  3767 W C       : 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-25 18:50:54.440  3767  3767 W C       : 	at android.os.Looper.loopOnce(Looper.java:232)
08-25 18:50:54.440  3767  3767 W C       : 	at android.os.Looper.loop(Looper.java:317)
08-25 18:50:54.440  3767  3767 W C       : 	at android.app.ActivityThread.main(ActivityThread.java:8594)
08-25 18:50:54.440  3767  3767 W C       : 	at java.lang.reflect.Method.invoke(Native Method)
08-25 18:50:54.440  3767  3767 W C       : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
08-25 18:50:54.440  3767  3767 W C       : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
08-25 18:50:54.445  3191  3191 W FeatureConnection: getRegistrationTech: ImsRegistration is null
08-25 18:50:54.445  3191  3191 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ REQUEST id=1689, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 1000 RequestorUid: 10404 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]
08-25 18:50:54.496  3191  3191 W FeatureConnection: getRegistrationTech: ImsRegistration is null
08-25 18:50:54.650  1294  2774 I WifiHAL : event received NL80211_CMD_VENDOR, vendor_id = 0x1374, subcmd = 0xd
08-25 18:50:54.727  1604  2596 D ActivityManager: freezing 2671 com.whatsapp
08-25 18:50:54.730  1604  2596 D ActivityManager: freezing 17722 com.sd.widget.memory
08-25 18:50:54.891  2798  2845 V WindowManagerShell: Transition animation finished (aborted=false), notifying core (#423) android.os.BinderProxy@70664d0@0
08-25 18:50:54.892  1604  1806 V WindowManager: Finish Transition (#423): created at 08-25 18:50:54.262 collect-started=0.049ms request-sent=5.052ms started=5.824ms ready=8.585ms sent=126.09ms finished=629.966ms
08-25 18:50:54.894  2798  2845 V WindowManagerShell: Track 0 became idle
08-25 18:50:54.894  2798  2845 V WindowManagerShell: All active transition animations finished
08-25 18:50:54.894  1604  5528 W UserManagerService: Requested status bar icon for non-badged user 0
```

### Screenshots or videos

![Screenshot_20240825-184733_Android System](https://github.com/user-attachments/assets/0383b75c-b4bd-4388-bc64-1ea93a783245)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by misi444** [comment]
Same problem on the same device. This used to work in crDroid 9, even with parallel apps (I think this is what cloned apps used to be called). It might even have worked in earlier crDroid 10 builds, but I can't really remember for sure. I'm using the stock launcher since Lawnchair 2 which I was using didn't support cloned apps.

**Comment by gwolf2u** [comment]
can't confirm this (todays build)
issue may be related to some specific setting you use, however that is not visible in logcat
![Screenshot_20240906-193726_Android System](https://github.com/user-attachments/assets/4c13c51e-b8f0-49f8-b915-035cf8251300)

**Comment by raystef66** [comment]
No issues on lmi, alioth nor cepheus - 06.09 builds

**Comment by quickishfm** [comment]
I think it may be related to work profiles or cloned apps. See the following screenshots.

![Screenshot_20240908-225458_Android System](https://github.com/user-attachments/assets/a75afb68-10d2-4c97-aaab-24976b905a67)
![Screenshot_20240908-225711_Android System](https://github.com/user-attachments/assets/b7478b4b-8439-4384-a2fc-9a151a9e92d9)

@gwolf2u Sorry if the logcat I posted wasn't helpful. What can I do to further help with logs?

**Comment by gwolf2u** [comment]
for now there's no actual way to debug this further
clone apps may be the issue, yet that feature can always cause weird issues

**Comment by Kryxzort** [comment]
can confirm, cloned apps is the cause
had this on crdroid, switched to another rom
had the issue again, deleted cloned apps, fixed.

**Comment by eepymeowers** [comment]
can also confirm cloned apps is the issue
