### ISSUE TITLE
bug: Java based apps crash upon opening the,

### ISSUE THREAD

**Issue by El-Nice** [crdroidandroid/issue_tracker#514]
### Issue type

User interface

### Device

Redmi 9 Lancelot

### crDroid version

crDroid 10

### Exact version / Build date

2024/01/20

### Bug description

Some java based apps arent working they crash upon opening them like Redotpay visa app

### Steps to reproduce

open any java based app

### Relevant log (logcat/build log)

```shell
time: 1726154480579
msg: java.lang.VerifyError: Verifier rejected class com.example.imagegallerysaver.a: android.net.Uri com.example.imagegallerysaver.a.a(java.lang.String, java.lang.String) failed to verify: android.net.Uri com.example.imagegallerysaver.a.a(java.lang.String, java.lang.String): [0x9A] Execution can walk off end of code area
 java.lang.String com.example.imagegallerysaver.a.b(java.lang.String) failed to verify: java.lang.String com.example.imagegallerysaver.a.b(java.lang.String): [0x16] Execution can walk off end of code area
 java.util.HashMap com.example.imagegallerysaver.a.c(java.lang.String, java.lang.String) failed to verify: java.util.HashMap com.example.imagegallerysaver.a.c(java.lang.String, java.lang.String): [0xF7] Execution can walk off end of code area
 java.util.HashMap com.example.imagegallerysaver.a.d(android.graphics.Bitmap, java.lang.Integer, java.lang.String) failed to verify: java.util.HashMap com.example.imagegallerysaver.a.d(android.graphics.Bitmap, java.lang.Integer, java.lang.String): [0xBC] Execution can walk off end of code area
 void com.example.imagegallerysaver.a.e(android.content.Context, android.net.Uri) failed to verify: void com.example.imagegallerysaver.a.e(android.content.Context, android.net.Uri): [0x13] Execution can walk off end of code area
 void com.example.imagegallerysaver.a.onAttachedToEngine(io.flutter.embedding.engine.plugins.a$b) failed to verify: void com.example.imagegallerysaver.a.onAttachedToEngine(io.flutter.embedding.engine.plugins.a$b): [0x16] Execution can walk off end of code area
 void com.example.imagegallerysaver.a.onDetachedFromEngine(io.flutter.embedding.engine.plugins.a$b) failed to verify: void com.example.imagegallerysaver.a.onDetachedFromEngine(io.flutter.embedding.engine.plugins.a$b): [0xB] Execution can walk off end of code area
 void com.example.imagegallerysaver.a.onMethodCall(io.flutter.plugin.common.j, io.flutter.plugin.common.k$d) failed to verify: void com.example.imagegallerysaver.a.onMethodCall(io.flutter.plugin.common.j, io.flutter.plugin.common.k$d): [0x5B] Execution can walk off end of code area (declaration of 'com.example.imagegallerysaver.a' appears in /data/user/0/com.redotpay/.cache/classes.dex)
stacktrace: java.lang.VerifyError: Verifier rejected class com.example.imagegallerysaver.a: android.net.Uri com.example.imagegallerysaver.a.a(java.lang.String, java.lang.String) failed to verify: android.net.Uri com.example.imagegallerysaver.a.a(java.lang.String, java.lang.String): [0x9A] Execution can walk off end of code area
 java.lang.String com.example.imagegallerysaver.a.b(java.lang.String) failed to verify: java.lang.String com.example.imagegallerysaver.a.b(java.lang.String): [0x16] Execution can walk off end of code area
 java.util.HashMap com.example.imagegallerysaver.a.c(java.lang.String, java.lang.String) failed to verify: java.util.HashMap com.example.imagegallerysaver.a.c(java.lang.String, java.lang.String): [0xF7] Execution can walk off end of code area
 java.util.HashMap com.example.imagegallerysaver.a.d(android.graphics.Bitmap, java.lang.Integer, java.lang.String) failed to verify: java.util.HashMap com.example.imagegallerysaver.a.d(android.graphics.Bitmap, java.lang.Integer, java.lang.String): [0xBC] Execution can walk off end of code area
 void com.example.imagegallerysaver.a.e(android.content.Context, android.net.Uri) failed to verify: void com.example.imagegallerysaver.a.e(android.content.Context, android.net.Uri): [0x13] Execution can walk off end of code area
 void com.example.imagegallerysaver.a.onAttachedToEngine(io.flutter.embedding.engine.plugins.a$b) failed to verify: void com.example.imagegallerysaver.a.onAttachedToEngine(io.flutter.embedding.engine.plugins.a$b): [0x16] Execution can walk off end of code area
 void com.example.imagegallerysaver.a.onDetachedFromEngine(io.flutter.embedding.engine.plugins.a$b) failed to verify: void com.example.imagegallerysaver.a.onDetachedFromEngine(io.flutter.embedding.engine.plugins.a$b): [0xB] Execution can walk off end of code area
 void com.example.imagegallerysaver.a.onMethodCall(io.flutter.plugin.common.j, io.flutter.plugin.common.k$d) failed to verify: void com.example.imagegallerysaver.a.onMethodCall(io.flutter.plugin.common.j, io.flutter.plugin.common.k$d): [0x5B] Execution can walk off end of code area (declaration of 'com.example.imagegallerysaver.a' appears in /data/user/0/com.redotpay/.cache/classes.dex)
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:37)
	at com.redotpay.MainActivity.o0(MainActivity.kt:13)
	at io.flutter.embedding.android.i.o0(FlutterFragment.java:11)
	at io.flutter.embedding.android.e.o(FlutterActivityAndFragmentDelegate.java:59)
	at io.flutter.embedding.android.i.onAttach(FlutterFragment.java:12)
	at androidx.fragment.app.p.performAttach(Fragment.java:50)
	at androidx.fragment.app.p0.c(FragmentStateManager.java:178)
	at androidx.fragment.app.p0.m(FragmentStateManager.java:138)
	at androidx.fragment.app.FragmentManager.j0(FragmentManager.java:350)
	at androidx.fragment.app.FragmentManager.t1(FragmentManager.java:82)
	at androidx.fragment.app.FragmentManager.g0(FragmentManager.java:22)
	at androidx.fragment.app.FragmentManager.Y(FragmentManager.java:41)
	at androidx.fragment.app.FragmentManager.D(FragmentManager.java:12)
	at androidx.fragment.app.x.c(FragmentController.java:7)
	at androidx.fragment.app.u.onStart(FragmentActivity.java:21)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1588)
	at android.app.Activity.performStart(Activity.java:8672)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3847)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2468)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this device is no longer maintained official
https://crdroid.net/lancelot/10
