### ISSUE TITLE
Lmi randomly switches to 77Hz in telegram 

### ISSUE THREAD

**Issue by Wirtos** [crdroidandroid/issue_tracker#517]
### Issue type

User interface

### Device

Poco F2 Pro Zoom (lmipro) 

### crDroid version

crDroid 9

### Exact version / Build date

10.8/2024-09-14

### Bug description

When using telegram, display sometimes switches to 77Hz, when opening pop-up menu it reverts back to expected 60.

### Steps to reproduce

Step 1. Open telegram
Step 2. Use until the issue reproduces 

### Relevant log (logcat/build log)

```shell
09-15 16:16:43.609 D/CoreBackPreview(1839): Window{1d62678 u0 PopupWindow:6c00742}: Setting back callback null
09-15 16:16:43.613 W/InputManager-JNI(1839): Input channel object '1d62678 PopupWindow:6c00742 (client)' was disposed without first being removed with the input manager!
09-15 16:16:43.613 V/WindowManager(1839): Loading animations: layout params pkg=org.telegram.messenger.web resId=0x0
09-15 16:16:43.616 E/WindowManager(1839): Unknown window type: 1000
09-15 16:16:43.634 V/WindowManager(1839): Unknown focus tokens, dropping reportFocusChanged
09-15 16:16:44.679 D/DisplayDevice(642): setDesiredMode 4630946829234430593 {mode=77.00 Hz (77.00 Hz(77.00 Hz)), emitEvent=true, force=false}
09-15 16:16:44.694 I/SDM     (1257): HWDeviceDRM::UpdateMixerAttributes: Mixer WxH 1080x2400-0 for Peripheral
09-15 16:16:44.695 I/SDM     (1257): HWCDisplay::SubmitDisplayConfig: Active configuration changed to: 1
09-15 16:16:44.697 D/audio_hw_primary(1187): adev_set_parameters: enter: screen_state=on
09-15 16:16:44.697 V/msm8974_platform(1187): platform_set_parameters: enter: screen_state=on
09-15 16:16:44.697 D/audio_hw_hfp(1187): hfp_set_parameters: enter
09-15 16:16:44.697 D/audio_hw_hfp(1187): hfp_set_parameters: enter
09-15 16:16:44.697 V/a2dp_offload(1187): end of a2dp setparam
09-15 16:16:44.697 D/audio_hw_extn(1187): audio_extn_fm_set_parameters: Enter
09-15 16:16:44.697 D/audio_hw_hfp(1187): hfp_set_parameters: enter
09-15 16:16:44.697 V/a2dp_offload(1187): end of a2dp setparam
09-15 16:16:44.697 D/audio_hw_primary(1187): adev_set_parameters: exit with code(0)
09-15 16:16:44.703 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10470/4259
09-15 16:16:44.703 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10507/8417
09-15 16:16:44.703 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10559/10625
09-15 16:16:44.703 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10474/10741
09-15 16:16:44.703 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10590/10826
09-15 16:16:44.703 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10592/11308
09-15 16:16:44.704 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10561/11583
09-15 16:16:44.704 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10439/16260
09-15 16:16:44.711 D/DisplayRepository(2664): combining enabled=[0], connectedExternalDisplayIds=[], ignored=[]
09-15 16:16:45.139 D/DisplayDevice(642): setDesiredMode 4630946829234430593 {mode=60.00 Hz (60.00 Hz(60.00 Hz)), emitEvent=true, force=false}
09-15 16:16:45.140 I/SDM     (1257): HWDeviceDRM::UpdateMixerAttributes: Mixer WxH 1080x2400-0 for Peripheral
09-15 16:16:45.140 I/SDM     (1257): HWCDisplay::SubmitDisplayConfig: Active configuration changed to: 0
09-15 16:16:45.158 D/audio_hw_primary(1187): adev_set_parameters: enter: screen_state=on
09-15 16:16:45.158 V/msm8974_platform(1187): platform_set_parameters: enter: screen_state=on
09-15 16:16:45.158 D/audio_hw_hfp(1187): hfp_set_parameters: enter
09-15 16:16:45.158 D/audio_hw_hfp(1187): hfp_set_parameters: enter
09-15 16:16:45.159 V/a2dp_offload(1187): end of a2dp setparam
09-15 16:16:45.159 D/audio_hw_extn(1187): audio_extn_fm_set_parameters: Enter
09-15 16:16:45.159 D/audio_hw_hfp(1187): hfp_set_parameters: enter
09-15 16:16:45.159 V/a2dp_offload(1187): end of a2dp setparam
09-15 16:16:45.159 D/audio_hw_primary(1187): adev_set_parameters: exit with code(0)
09-15 16:16:45.160 D/DisplayRepository(2664): combining enabled=[0], connectedExternalDisplayIds=[], ignored=[]
09-15 16:16:45.161 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10470/4259
09-15 16:16:45.161 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10507/8417
09-15 16:16:45.161 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10559/10625
09-15 16:16:45.161 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10474/10741
09-15 16:16:45.161 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10590/10826
09-15 16:16:45.161 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10592/11308
09-15 16:16:45.161 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10561/11583
09-15 16:16:45.161 D/DisplayManagerService(1839): Ignore redundant display event 0/2 to 10439/16260
09-15 16:16:45.362 D/CoreBackPreview(1839): Window{cfc484a u0 PopupWindow:d00bc64}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@ea6a097, mPriority=0, mIsAnimationCallback=false}
09-15 16:16:45.384 V/WindowManager(1839): Loading animations: layout params pkg=org.telegram.messenger.web resId=0x0
09-15 16:16:45.415 W/Choreographer(1839): Frame time is 0.213403 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
09-15 16:16:45.415 W/Choreographer(4326): Frame time is 0.199601 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
09-15 16:16:46.487 I/m.messenger.web(4326): Method exceeds compiler instruction limit: 17127 in void org.telegram.ui.ChatActivity.didReceivedNotification(int, int, java.lang.Object[])
09-15 16:16:47.255 W/WindowOnBackDispatcher(4326): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@a21d8eb
09-15 16:16:47.256 D/CoreBackPreview(1839): Window{cfc484a u0 PopupWindow:d00bc64}: Setting back callback null
09-15 16:16:47.262 W/InputManager-JNI(1839): Input channel object 'cfc484a PopupWindow:d00bc64 (client)' was disposed without first being removed with the input manager!
09-15 16:16:47.262 V/WindowManager(1839): Loading animations: layout params pkg=org.telegram.messenger.web resId=0x0
09-15 16:16:47.263 E/WindowManager(1839): Unknown window type: 1000
09-15 16:16:47.281 V/WindowManager(1839): Unknown focus tokens, dropping reportFocusChanged
09-15 16:16:48.025 I/m.messenger.web(4326): Method exceeds compiler instruction limit: 17127 in void org.telegram.ui.ChatActivity.didReceivedNotification(int, int, java.lang.Object[])
09-15 16:16:48.030 I/m.messenger.web(4326): Method exceeds compiler instruction limit: 17127 in void org.telegram.ui.ChatActivity.didReceivedNotification(int, int, java.lang.Object[])
09-15 16:16:48.090 I/Finsky  (8460): [31] lwg.run(200): Stats for Executor: BlockingExecutor qez@d98a969[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 176]
09-15 16:16:48.091 I/Finsky  (8460): [31] lwg.run(200): Stats for Executor: LightweightExecutor qez@dd44fee[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 195]
09-15 16:16:48.120 I/Finsky  (8460): [31] lwg.run(200): Stats for Executor: bgExecutor qez@3d4bc8f[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 1768]
09-15 16:16:48.261 D/CoreBackPreview(1839): Window{d1af3a1 u0 com.fb.fluid}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@b99a4b4, mPriority=0, mIsAnimationCallback=false}
09-15 16:16:48.270 V/WindowManager(1839): Loading animations: layout params pkg=com.fb.fluid resId=0x0
09-15 16:16:48.335 D/vendor.qti.vibrator.xiaomi_lmi(1346): Vibrator perform effect 0
09-15 16:16:48.335 D/vendor.qti.vibrator.xiaomi_lmi(1346): Starting perform on another thread
09-15 16:16:48.355 D/vendor.qti.vibrator.xiaomi_lmi(1346): Notifying perform complete
09-15 16:16:48.356 D/vendor.qti.vibrator.xiaomi_lmi(1346): QTI Vibrator off
09-15 16:16:48.509 D/b/321291049(2856): updateSplitButtonHiddenFlags called with flag: 1 enabled: true shouldBeVisible: false partial trace: 
09-15 16:16:48.509 D/b/321291049(2856): 	at com.android.quickstep.views.OverviewActionsView.updateSplitButtonHiddenFlags(OverviewActionsView.java:318)
09-15 16:16:48.509 D/b/321291049(2856): 	at com.android.quickstep.views.RecentsView.updateCurrentTaskActionsVisibility(RecentsView.java:3989)
09-15 16:16:48.509 D/b/321291049(2856): 	at com.android.quickstep.views.RecentsView.notifyPageSwitchListener(RecentsView.java:5231)
09-15 16:16:48.509 D/b/321291049(2856): 	at com.android.launcher3.PagedView.setCurrentPage(PagedView.java:450)
09-15 16:16:48.519 V/ShellRecents(2664): RecentsTransitionHandler.startRecentsTransition
09-15 16:16:48.520 V/WindowManagerShell(2664): Directly starting a new transition type=3 wct=WindowContainerTransaction { changes = {} hops = [{PendingIntent: options=Bundle[mParcelledData.dataSize=412]}] errorCallbackToken=null taskFragmentOrganizer=null } handler=com.android.wm.shell.recents.RecentsTransitionHandler@b914d66
09-15 16:16:48.520 D/b/321291049(2856): updateSplitButtonHiddenFlags called with flag: 1 enabled: true shouldBeVisible: false partial trace: 
09-15 16:16:48.520 D/b/321291049(2856): 	at com.android.quickstep.views.OverviewActionsView.updateSplitButtonHiddenFlags(OverviewActionsView.java:318)
09-15 16:16:48.520 D/b/321291049(2856): 	at com.android.quickstep.views.RecentsView.updateCurrentTaskActionsVisibility(RecentsView.java:3989)
09-15 16:16:48.520 D/b/321291049(2856): 	at com.android.quickstep.views.RecentsView.notifyPageSwitchListener(RecentsView.java:5231)
09-15 16:16:48.520 D/b/321291049(2856): 	at com.android.launcher3.PagedView.setCurrentPage(PagedView.java:450)
09-15 16:16:48.521 I/android.hardware.power-service-qti(1239): Power setMode: 5 to: 1
09-15 16:16:48.522 E/ANDR-PERF-OPTSHANDLER(1321): Min bounds check failed
09-15 16:16:48.522 E/ANDR-PERF-OPTSHANDLER(1321): Error! Perflock failed, invalid request value 255
09-15 16:16:48.522 E/ANDR-PERF-RESOURCEQS(1321): Failed to apply optimization [6, 6]
09-15 16:16:48.523 E/ANDR-PERF-UTIL(1321): Failed to read /sys/class/mmc_host/mmc0/clk_scaling/enable
09-15 16:16:48.523 E/ANDR-PERF-OPTSHANDLER(1321): Failed to read /sys/class/mmc_host/mmc0/clk_scaling/enable
09-15 16:16:48.523 E/ANDR-PERF-RESOURCEQS(1321): Failed to apply optimization [11, 4]
09-15 16:16:48.523 D/b/321291049(2856): updateSplitButtonHiddenFlags called with flag: 1 enabled: true shouldBeVisible: false partial trace: 
09-15 16:16:48.523 D/b/321291049(2856): 	at com.android.quickstep.views.OverviewActionsView.updateSplitButtonHiddenFlags(OverviewActionsView.java:318)
09-15 16:16:48.523 D/b/321291049(2856): 	at com.android.quickstep.views.RecentsView.updateCurrentTaskActionsVisibility(RecentsView.java:3989)
09-15 16:16:48.523 D/b/321291049(2856): 	at com.android.quickstep.views.RecentsView.notifyPageSwitchListener(RecentsView.java:5231)
09-15 16:16:48.523 D/b/321291049(2856): 	at com.android.launcher3.PagedView.setCurrentPage(PagedView.java:450)
09-15 16:16:48.524 D/ForegroundUtils(3964): Foreground UID status:
09-15 16:16:48.524 D/ForegroundUtils(3964): UID: 10428 is in foreground: true
09-15 16:16:48.524 D/ForegroundUtils(3964): UID: 10429 is in foreground: true
09-15 16:16:48.524 D/ForegroundUtils(3964): UID: 10439 is in foreground: false
09-15 16:16:48.524 D/ForegroundUtils(3964): UID: 10461 is in foreground: true
09-15 16:16:48.524 D/ForegroundUtils(3964): UID: 10470 is in foreground: false
09-15 16:16:48.524 D/ForegroundUtils(3964): UID: 10498 is in foreground: false
09-15 16:16:48.524 D/ForegroundUtils(3964): UID: 10507 is in foreground: false
09-15 16:16:48.524 D/ForegroundUtils(3964): UID: 10550 is in foreground: true
09-15 16:16:48.524 D/ForegroundUtils(3964): UID: 10559 is in foreground: false
09-15 16:16:48.524 D/ForegroundUtils(3964): UID: 10634 is in foreground: true
09-15 16:16:48.528 D/StateManager(2856): goToState - fromState: Ordinal-4, toState: Ordinal-2, partial trace:
09-15 16:16:48.528 D/StateManager(2856): 	at com.android.quickstep.BaseActivityInterface$DefaultAnimationFactory.initBackgroundStateUI(BaseActivityInterface.java:528)
09-15 16:16:48.528 D/StateManager(2856): 	at com.android.quickstep.FallbackActivityInterface.prepareRecentsUI(FallbackActivityInterface.java:86)
09-15 16:16:48.528 D/StateManager(2856): onStateTransitionStart - state: Ordinal-2
09-15 16:16:48.528 V/ShellRecents(2664): [47643506] RecentsController.setTransition: id=android.os.BinderProxy@251fbc3
09-15 16:16:48.528 D/StateManager(2856): onStateTransitionEnd - state: Ordinal-2
09-15 16:16:48.545 I/sensors-hal(1242): batch:180, android.sensor.accelerometer/66, period=20000000, max_latency=66667000
09-15 16:16:48.546 I/sensors-hal(1242): batch:189, android.sensor.accelerometer/66, period=20000000, max_latency=66667000 request completed
09-15 16:16:48.546 I/sensors-hal(1242): flush:209, android.sensor.accelerometer/66
09-15 16:16:48.548 I/sensors-hal(1242): flush:215, android.sensor.accelerometer/66 completed
09-15 16:16:48.557 V/WindowManagerShell(2664): onTransitionReady (#53) android.os.BinderProxy@251fbc3: {id=53 t=TO_FRONT f=0x80 trk=0 r=[0@Point(0, 0)] c=[{WCT{android.window.IWindowContainerToken$Stub$Proxy@a56c6c} m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=1516)/@0x36fcc40 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{WCT{android.window.IWindowContainerToken$Stub$Proxy@5004235} m=TO_BACK f=NONE leash=Surface(name=Task=1511)/@0x55a779 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0},{null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{35c0ed token=android.os.Binder@b0b5304})/@0xe155cbe sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
09-15 16:16:48.557 V/WindowManagerShell(2664): Playing animation for (#53) android.os.BinderProxy@251fbc3@0
09-15 16:16:48.557 V/WindowManagerShell(2664):  try firstHandler com.android.wm.shell.recents.RecentsTransitionHandler@b914d66
09-15 16:16:48.557 V/ShellRecents(2664): [47643506] RecentsController.start
09-15 16:16:48.557 W/UserManagerService(1839): Requested status bar icon for non-badged user 0
09-15 16:16:48.557 V/ShellRecents(2664):   setting recents activity layer=6
09-15 16:16:48.558 V/ShellRecents(2664):   adding pausing leaf taskId=1511 at layer=8
09-15 16:16:48.558 V/ShellRecents(2664): [47643506] RecentsController.start: calling onAnimationStart
09-15 16:16:48.559 V/WindowManagerShell(2664):  animated by firstHandler
09-15 16:16:48.559 D/ConnectivityService(1839): requestNetwork for uid/pid:10429/2664 asUid: 10428 activeRequest: null callbackRequest: 585 [NetworkRequest [ REQUEST id=586, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10428 RequestorUid: 10429 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
09-15 16:16:48.559 D/RemoteTargetGluer(2856): appCount: 1 handleLength: 4
09-15 16:16:48.559 D/RemoteTargetGluer(2856): resizing
```

### Screenshots or videos

https://github.com/user-attachments/assets/2c56d2dd-895b-4f58-a393-7b7c8c82c0ee

### Solution

Killing the app solves the issue temporarily until it reproduces again 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is not an actual bug
screen refresh rate can adapt based on the content to display
