### ISSUE TITLE
bug: Lag and FPS drop in YouTube videos and when using the application interface 

### ISSUE THREAD

**Issue by MARCOS752wh** [crdroidandroid/issue_tracker#52]
### Issue type

Feature not working as intended

### Device

Poco X3 Pro 
/ Vayu /

M2102J20SI

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

When establishing a video quality, lag is appreciated at times in the videos and the use of the interface with obstacles and it is difficult for the video to be played in full screen 

### Steps to reproduce

1-enter YouTube 2-select video and set quality 

3-YouTube interface browser 

### Relevant log (logcat/build log)

```shell
11-29 00:05:42.119 E/YouTubeAndroidPlayerAPI(13831): Media progress reported outside media playback: PLAYBACK_PENDING

11-29 00:05:42.042 E/YT.mlplayer(13831): MedialibPlayer.stopVideo(), STOPPAGE_REASON_UNKNOWN

11-29 00:05:42.119 E/YouTubeAndroidPlayerAPI(13831): Media progress reported outside media playback: PLAYBACK_PENDING

11-29 00:05:42.155 E/android.youtube(13831): Resource 7f040947 is a complex map type.

11-29 00:05:42.229 E/OMX-VDEC-1080P(1202): Unsupported output color format for c2d (2141391876)

11-29 00:05:42.229 E/OMX-VDEC-1080P(1202): Setting color format failed
11-29 00:05:42.235 E/OMX-VDEC-1080P(1202): set_parameter: Error: 0x80001019, setting param 0x7f00005d

11-29 00:05:42.235 E/OMXNodeInstance(1202): setParameter(0xe9b20034:qcom.decoder.vp9, OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)

11-29 00:05:42.237 E/OMX-VDEC-1080P(1202): Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented

11-29 00:05:42.237 E/OMX-VDEC-1080P(1202): Extension: OMX.google.android.index.configureVideoTunnelMode not implemented

11-29 00:05:42.237 E/OMX-VDEC-1080P(1202): Extension: OMX.google.android.index.useAndroidNativeBuffer is supported

11-29 00:05:42.237 E/OMX-VDEC-1080P(1202): get_parameter: unknown param 6f600007

11-29 00:05:42.237 E/OMXNodeInstance(1202): getParameter(0xe9b20034:qcom.decoder.vp9, ParamVideoAndroidVp8Encoder(0x6f600007)) ERROR: UnsupportedIndex(0x8000101a)

11-29 00:05:42.238 E/OMXNodeInstance(1202): getConfig(0xe9b20034:qcom.decoder.vp9, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)

11-29 00:05:42.245 E/YT.qoe  (13831): Pinging https://s.youtube.com/api/stats/qoe?cl=490317732&event=streamingstats&ns=yt&cpn=Ax5HmfkUYixlfWh0&cplatform=mobile&cbr=com.google.android.youtube&cff=SMALL_FORM_FACTOR&c=android&cmodel=M2102J20SI&cos=Android&csdk=33&cbrver=17.46.37&cver=17.46.37&cosver=13&cbrand=Xiaomi&vis=0.000:5&sur=0.008:1,0.070:3&conn=0.004:3&cplayer=ANDROID_EXOPLAYER_V2&bat=0.002:0.500:0,0.200:0.500:0&vps=0.000:N&ctmp=du:used.0.268435456;avail.110688071680.115020361728&vc=1532882368&seq=1

11-29 00:05:42.279 E/OMXNodeInstance(1202): getConfig(0xe9b20034:qcom.decoder.vp9, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)
11-29 00:05:42.968 E/WifiHAL (847): get_wifi_interface_info: QCA_WLAN_VENDOR_ATTR_LL_STATS_IFACE_INFO_TS_DUTY_CYCLE not found
11-29 00:05:42.969 E/WifiHAL (847): nl80211: requestResponse->nl_recvmsgs failed: -5
11-29 00:05:42.970 E/WifiVendorHal(1665): getWifiLinkLayerStats_1_6_Internal(l.1199) failed {.code = ERROR_INVALID_ARGS, .description = }

11-29 00:05:43.630 E/YT.onesie(13831): 	at kcy.c(PG:8)
11-29 00:05:43.630 E/YT.onesie(13831): 	at com.google.android.apps.youtube.app.ui.inline.InlinePlaybackController.A(PG:3)
11-29 00:05:43.630 E/YT.onesie(13831): 	at com.google.android.apps.youtube.app.ui.inline.InlinePlaybackController.m(PG:8)
11-29 00:05:43.630 E/YT.onesie(13831): 	at com.google.android.apps.youtube.app.common.ui.inline.InlinePlaybackLifecycleController.x(PG:7)
11-29 00:05:43.630 E/YT.onesie(13831): 	at com.google.android.apps.youtube.app.common.ui.inline.InlinePlaybackLifecycleController.s(PG:12)
11-29 00:05:43.630 E/YT.onesie(13831): 	at qp.run(PG:34)
11-29 00:05:43.630 E/YT.onesie(13831): 	at android.os.Handler.handleCallback(Handler.java:942)
11-29 00:05:43.630 E/YT.onesie(13831): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-29 00:05:43.630 E/YT.onesie(13831): 	at android.os.Looper.loopOnce(Looper.java:201)
11-29 00:05:43.630 E/YT.onesie(13831): 	at android.os.Looper.loop(Looper.java:288)
11-29 00:05:43.630 E/YT.onesie(13831): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
11-29 00:05:43.630 E/YT.onesie(13831): 	at java.lang.reflect.Method.invoke(Native Method)
11-29 00:05:43.630 E/YT.onesie(13831): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-29 00:05:43.630 E/YT.onesie(13831): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
11-29 00:05:43.637 E/OMX-VDEC-1080P(1202): Extension: OMX.google.android.index.AndroidNativeBufferConsumerUsage not implemented
```

### Screenshots or videos

[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/10110346/logcat.txt)

### Solution

Don't know

### Additional context

I hope you can really solve it and I hope there can be more optimization than up to now how is this ROM going it is doing the best but always improve and improve, oh and a lot, good day or night, thank you

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
still happening on newer revision?
