### ISSUE TITLE
Bluetooth Crashing

### ISSUE THREAD

**Issue by Cosmic117** [crdroidandroid/issue_tracker#548]
### Issue type

Feature not working as intended

### Device

Pixel 9 Pro

### crDroid version

crDroid 11

### Exact version / Build date

2024-11-02

### Bug description

When i try to connect my Google Pixel Bud Pro 2, it does not work and an error that Bluetooth has stopped working. I cannot connect my headphones.  

### Steps to reproduce

Step 1: turn on Bluetooth on pixel 9 pro
Step 2: open the lid of the pixel bud pro 2
step 3: click connect when the connection wizard appears on pixel
step 4: it starts to connect but never does and the Bluetooth stopped working dialog box appears and it fails

### Relevant log (logcat/build log)

```shell
time: 1731214168224
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
	at com.android.bluetooth.btservice.BondStateMachine.isSkipConfirmationAccessory(BondStateMachine.java:505)
	at com.android.bluetooth.btservice.BondStateMachine.sendDisplayPinIntent(BondStateMachine.java:517)
	at com.android.bluetooth.btservice.BondStateMachine.-$$Nest$msendDisplayPinIntent(BondStateMachine.java:0)
	at com.android.bluetooth.btservice.BondStateMachine$PendingCommandState.processMessage(BondStateMachine.java:314)
	at com.android.bluetooth.jarjar.com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:1001)
	at com.android.bluetooth.jarjar.com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:819)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:85)
```

### Solution

please fix bluetooth or disclose solution

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
full logcat needed
`adb logcat > log.txt`
attach log here

**Comment by Cosmic117** [comment]
[log.txt](https://github.com/user-attachments/files/17690582/log.txt)

first time back in android in a bit so i think i got the right logcat attached here. Let me know if anything

**Comment by Cosmic117** [comment]
Just some extra info. I grabbed my airpod pro's from my previous iphone and set them to pairing and hooked them up normal via bluetooth and they are working fine. This did not work with the bus pro 2's tho. The bud pro 2's worked fine before the flash and laso work fine on my samsung tab tablet. Seems to be something with the built in google setup system (i barely know what im talking about so apologies if this is not helpful)
