### ISSUE TITLE
bug: video and audio system are broken

### ISSUE THREAD

**Issue by serakyel** [crdroidandroid/issue_tracker#573]
### Issue type

Source code related

### Device

Enchilada

### crDroid version

crDroid 10

### Exact version / Build date

10.10/2024-11-25

### Bug description

Video on social media app and audio like Whatsapp audio, telegram audio, screen recording audio + system like keyboard, lock unlock are broken. It's like they're constantly buffering, skipping, going silent, and then replaying everything in a split second. The phone is pretty much unusable with media. My maintainer says he hasn't changed anything about it and that it might be a source issue 

### Steps to reproduce

Trying to lock and unlock, the sound can be delayed
Typing on keyboard, the audio can be delayed or nullified 
Trying to watch video on any social media app, video and audio buffering even with good connection 
Whatsapp audio are broken: I literally can't use them. Audio skip from the start to sec 3 then to sec 6 lol

### Relevant log (logcat/build log)

```shell
11-27 12:34:38.870 V/WindowManagerShell(26950): Transition requested (#1110): android.os.BinderProxy@977a6a2 TransitionRequestInfo { type = CLOSE, triggerTask = TaskInfo{userId=0 taskId=132 displayId=0 isRunning=false baseIntent=Intent { act=com.pluscubed.logcat.action.RECORD_OR_STOP flg=0x18800000 cmp=org.omnirom.logcat/com.pluscubed.logcat.ui.RecordLogDialogActivity } baseActivity=null topActivity=null origActivity=null realActivity=ComponentInfo{org.omnirom.logcat/com.pluscubed.logcat.ui.RecordLogDialogActivity} numActivities=0 lastActiveTime=8894543 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@37f33} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 79 - 0, 0) topActivityInfo=null launchCookies=[android.os.BinderProxy@fe0d9af] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 1110 }
11-27 12:34:38.883 I/ActivityManager( 1529): Background started FGS: Allowed [callingPackage: org.omnirom.logcat; callingUid: 10438; uidState: TOP ; uidBFSL: [BFSL]; intent: Intent { cmp=org.omnirom.logcat/com.pluscubed.logcat.LogcatRecordingService (has extras) }; code:PROC_STATE_TOP; tempAllowListReason:<null>; targetSdkVersion:32; callerTargetSdkVersion:32; startForegroundCount:0; bindFromPackage:null: isBindService:false]
11-27 12:34:38.884 W/ForegroundServiceTypeLoggerModule( 1529): Foreground service start for UID: 10438 does not have any types
11-27 12:34:38.890 D/VRI[0 fl=}](14429): visibilityChanged oldVisibility=false newVisibility=true
11-27 12:34:38.909 D/ForegroundUtils( 4223): Foreground UID status:
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 1002 is in foreground: true
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 1027 is in foreground: true
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10345 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10349 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10372 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10384 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10386 is in foreground: true
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10396 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10397 is in foreground: true
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10426 is in foreground: true
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10434 is in foreground: true
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10438 is in foreground: true
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10451 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10469 is in foreground: true
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10472 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10473 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10476 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10479 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10480 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10485 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10491 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10496 is in foreground: false
11-27 12:34:38.909 D/ForegroundUtils( 4223): UID: 10505 is in foreground: false
11-27 12:34:38.910 D/ForegroundUtils( 4223): UID: 10561 is in foreground: false
11-27 12:34:38.912 D/WindowManagerShell(26950): setLauncherKeepClearAreaHeight: visible=true, height=439
11-27 12:34:38.913 D/ForegroundUtils( 4223): Foreground UID status:
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 1002 is in foreground: true
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 1027 is in foreground: true
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10345 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10349 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10372 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10384 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10386 is in foreground: true
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10396 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10397 is in foreground: true
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10426 is in foreground: true
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10434 is in foreground: true
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10438 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10451 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10469 is in foreground: true
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10472 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10473 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10476 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10479 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10480 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10485 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10491 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10496 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10505 is in foreground: false
11-27 12:34:38.913 D/ForegroundUtils( 4223): UID: 10561 is in foreground: false
11-27 12:34:38.919 I/cmle    (14429): onStart
11-27 12:34:38.923 I/cmle    (14429): onResume
11-27 12:34:38.929 D/BaseDepthController( 5917): setSurface:
11-27 12:34:38.929 D/BaseDepthController( 5917): 	mWaitingOnSurfaceValidity: false
11-27 12:34:38.929 D/BaseDepthController( 5917): 	mSurface: Surface(name=com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher)/@0x34756e8
11-27 12:34:38.937 D/StatsLog( 5917): LAUNCHER_ONRESUME
11-27 12:34:38.942 D/QuickstepModelDelegate( 5917): notifyAppTargetEvent action=1 launchLocation=workspace/1/[-1,-1]/[1,1]
11-27 12:34:38.943 V/WindowManager( 1529): Loading animations: layout params pkg=com.android.launcher3 resId=0x10302fc
11-27 12:34:38.943 V/WindowManager( 1529): Loading animations: picked package=android
11-27 12:34:38.948 V/WindowManagerShell(26950): onTransitionReady (#1110) android.os.BinderProxy@977a6a2: {id=1110 t=CLOSE f=0x0 trk=0 r=[0@Point(0, 0)] c=[{WCT{android.window.IWindowContainerToken$Stub$Proxy@5f64268} m=TO_FRONT f=SHOW_WALLPAPER leash=Surface(name=Task=11)/@0x105fa7c sb=Rect(0, 0 - 1080, 2280) eb=Rect(0, 0 - 1080, 2280) d=0},{WCT{android.window.IWindowContainerToken$Stub$Proxy@6862681} m=CLOSE f=NONE leash=Surface(name=Task=132)/@0x9c59f05 sb=Rect(0, 0 - 1080, 2280) eb=Rect(0, 0 - 1080, 2280) d=0},{null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{a44d42c token=android.os.Binder@42fbfdf})/@0x2766b5a sb=Rect(0, 0 - 1080, 2280) eb=Rect(0, 0 - 1080, 2280) d=0}]}
11-27 12:34:38.949 V/WindowManagerShell(26950): Playing animation for (#1110) android.os.BinderProxy@977a6a2@0
11-27 12:34:38.949 V/WindowManagerShell(26950):  try handler com.android.wm.shell.transition.DefaultMixedHandler@26b6ad2
11-27 12:34:38.949 V/WindowManagerShell(26950):  try handler com.android.wm.shell.keyguard.KeyguardTransitionHandler@2b4a7a3
11-27 12:34:38.949 V/WindowManagerShell(26950):  try handler com.android.wm.shell.pip.PipTransition@d113aa0
11-27 12:34:38.949 V/WindowManagerShell(26950):  try handler com.android.wm.shell.activityembedding.ActivityEmbeddingController@7f2e659
11-27 12:34:38.949 V/WindowManagerShell(26950):  try handler com.android.wm.shell.recents.RecentsTransitionHandler@671621e
11-27 12:34:38.949 V/ShellRecents(26950): RecentsTransitionHandler.startAnimation: no controller found
11-27 12:34:38.949 V/WindowManagerShell(26950):  try handler com.android.wm.shell.splitscreen.StageCoordinator@56c0297
11-27 12:34:38.949 V/WindowManagerShell(26950):  try handler com.android.wm.shell.transition.RemoteTransitionHandler@b601aff
11-27 12:34:38.949 V/WindowManagerShell(26950): Transition doesn't have explicit remote, search filters for match for {id=1110 t=CLOSE f=0x0 trk=0 r=[0@Point(0, 0)] c=[{WCT{android.window.IWindowContainerToken$Stub$Proxy@5f64268} m=TO_FRONT f=SHOW_WALLPAPER leash=Surface(name=Task=11)/@0x105fa7c sb=Rect(0, 0 - 1080, 2280) eb=Rect(0, 0 - 1080, 2280) d=0},{WCT{android.window.IWindowContainerToken$Stub$Proxy@6862681} m=CLOSE f=NONE leash=Surface(name=Task=132)/@0x9c59f05 sb=Rect(0, 0 - 1080, 2280) eb=Rect(0, 0 - 1080, 2280) d=0},{null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{a44d42c token=android.os.Binder@42fbfdf})/@0x2766b5a sb=Rect(0, 0 - 1080, 2280) eb=Rect(0, 0 - 1080, 2280) d=0}]}
11-27 12:34:38.949 V/WindowManagerShell(26950):  Checking filter Pair{{types=[] flags=0x0] notFlags=0x100 checks=[{atype=home independent=true modes=[OPEN,TO_FRONT] flags=NONE mustBeTask=false order=TOP topActivity=ComponentInfo{com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}},{atype=standard independent=true modes=[CLOSE,TO_BACK] flags=NONE mustBeTask=false order=ANY topActivity=null}]} RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@172eb60, appThread = android.app.IApplicationThread$Stub$Proxy@de5a819, debugName = QuickstepLaunchHome }}
11-27 12:34:38.949 D/RemoteTransitionHandler(26950): Found filterPair{{types=[] flags=0x0] notFlags=0x100 checks=[{atype=home independent=true modes=[OPEN,TO_FRONT] flags=NONE mustBeTask=false order=TOP topActivity=ComponentInfo{com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}},{atype=standard independent=true modes=[CLOSE,TO_BACK] flags=NONE mustBeTask=false order=ANY topActivity=null}]} RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@172eb60, appThread = android.app.IApplicationThread$Stub$Proxy@de5a819, debugName = QuickstepLaunchHome }}
11-27 12:34:38.949 V/WindowManagerShell(26950):  Delegate animation for (#1110) to RemoteTransition { remoteTransition = android.window.IRemoteTransition$Stub$Proxy@172eb60, appThread = android.app.IApplicationThread$Stub$Proxy@de5a819, debugName = QuickstepLaunchHome }
11-27 12:34:38.957 I/WindowManager( 1529): Queue is too deep! Purged item with index=115
11-27 12:34:38.958 V/WindowManager( 1529): Sent Transition (#1110) createdAt=11-27 12:34:38.869 via request=TransitionRequestInfo { type = CLOSE, triggerTask = TaskInfo{userId=0 taskId=132 displayId=0 isRunning=false baseIntent=Intent { act=com.pluscubed.logcat.action.RECORD_OR_STOP flg=0x18800000 cmp=org.omnirom.logcat/com.pluscubed.logcat.ui.RecordLogDialogActivity } baseActivity=null topActivity=null origActivity=null realActivity=ComponentInfo{org.omnirom.logcat/com.pluscubed.logcat.ui.RecordLogDialogActivity} numActivities=0 lastActiveTime=8894543 supportsMultiWindow=true resizeMode=1 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{9590f3d Task{7232ff7 #132 type=standard A=10438:org.omnirom.logcat}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 79 - 0, 0) topActivityInfo=null launchCookies=[android.os.BinderProxy@b280883] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 1110 }
11-27 12:34:38.958 V/WindowManager( 1529):     startWCT=WindowContainerTransaction { changes = {} hops = [] errorCallbackToken=null taskFragmentOrganizer=null }
11-27 12:34:38.958 V/WindowManager( 1529):     info={id=1110 t=CLOSE f=0x0 trk=0 r=[0@Point(0, 0)] c=[
11-27 12:34:38.958 V/WindowManager( 1529):         {WCT{RemoteToken{bd5073e Task{72afd4b #11 type=undefined}}} m=TO_FRONT f=SHOW_WALLPAPER leash=Surface(name=Task=11)/@0xc5e30d sb=Rect(0, 0 - 1080, 2280) eb=Rect(0, 0 - 1080, 2280) d=0},
11-27 12:34:38.958 V/WindowManager( 1529):         {WCT{RemoteToken{9590f3d Task{7232ff7 #132 type=standard A=10438:org.omnirom.logcat}}} m=CLOSE f=NONE leash=Surface(name=Task=132)/@0x84a04e7 sb=Rect(0, 0 - 1080, 2280) eb=Rect(0, 0 - 1080, 2280) d=0},
11-27 12:34:38.958 V/WindowManager( 1529):         {null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{a44d42c token=android.os.Binder@42fbfdf})/@0xcd00c43 sb=Rect(0, 0 - 1080, 2280) eb=Rect(0, 0 - 1080, 2280) d=0}
11-27 12:34:38.958 V/WindowManager( 1529):     ]}
11-27 12:34:38.960 D/StateManager( 5917): createAtomicAnimation - fromState: Background, toState: Normal, partial trace:
11-27 12:34:38.960 D/StateManager( 5917): 	at com.android.quickstep.util.StaggeredWorkspaceAnim.prepareToAnimate(StaggeredWorkspaceAnim.java:217)
11-27 12:34:38.960 D/StateManager( 5917): 	at com.android.quickstep.util.StaggeredWorkspaceAnim.<init>(StaggeredWorkspaceAnim.java:85)
11-27 12:34:38.960 D/StateManager( 5917): 	at com.android.quickstep.util.StaggeredWorkspaceAnim.<init>(StaggeredWorkspaceAnim.java:80)
11-27 12:34:38.961 V/WindowManagerShell(26950):  animated by com.android.wm.shell.transition.RemoteTransitionHandler@b601aff
11-27 12:34:38.965 W/UserManagerService( 1529): Requested status bar icon for non-badged user 0
11-27 12:34:38.969 D/ConnectivityService( 1529): requestNetwork for uid/pid:10434/26950 asUid: 10426 activeRequest: null callbackRequest: 2995 [NetworkRequest [ REQUEST id=2996, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10426 RequestorUid: 10434 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]] callback flags: 0 order: 2147483647
11-27 12:34:38.973 D/WifiNetworkFactory( 1529): got request NetworkRequest [ REQUEST id=2996, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10426 RequestorUid: 10434 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]
11-27 12:34:38.973 D/UntrustedWifiNetworkFactory( 1529): got request NetworkRequest [ REQUEST id=2996, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10426 RequestorUid: 10434 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]
11-27 12:34:38.973 D/OemPaidWifiNetworkFactory( 1529): got request NetworkRequest [ REQUEST id=2996, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10426 RequestorUid: 10434 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]
11-27 12:34:38.974 D/ConnectivityService( 1529): NetReassign [2996 : null → 100] [c 1] [a 1] [i 3]
11-27 12:34:38.975 D/MultiInternetWifiNetworkFactory( 1529): got request NetworkRequest [ REQUEST id=2996, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10426 RequestorUid: 10434 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]
11-27 12:34:38.988 I/ImeTracker( 1529): com.android.launcher3:4c64454a: onRequestHide at ORIGIN_SERVER reason HIDE_UNSPECIFIED_WINDOW fromUser false
11-27 12:34:38.988 I/ImeTracker( 1529): com.android.launcher3:4c64454a: onCancelled at PHASE_SERVER_SHOULD_HIDE
11-27 12:34:38.990 I/GoogleInputMethodService(20505): GoogleInputMethodService.onFinishInput():3095 
11-27 12:34:38.991 I/GoogleInputMethodService(20505): GoogleInputMethodService.updateDeviceLockedStatus():2167 repeatCheckTimes = 0, locked = false
11-27 12:34:38.991 I/GoogleInputMethodService(20505): GoogleInputMethodService.onStartInput():1911 onStartInput(EditorInfo{EditorInfo{packageName=com.android.launcher3, inputType=0, inputTypeString=NULL, enableLearning=false, autoCorrection=false, autoComplete=false, imeOptions=0, privateImeOptions=null, actionName=UNSPECIFIED, actionLabel=null, initialSelStart=-1, initialSelEnd=-1, initialCapsMode=0, label=null, fieldId=0, fieldName=null, extras=null, hintText=null, hintLocales=[]}}, false)
11-27 12:34:38.991 D/QuickstepLauncher( 5917): Bind extra container items. ContainerId = -111
11-27 12:34:38.991 I/GoogleInputMethodService(20505): GoogleInputMethodService.updateDeviceLockedStatus():2167 repeatCheckTimes = 1, locked = false
11-27 12:34:38.991 I/AndroidIME(20505): InputBundleManager.loadActiveInputBundleId():450 loadActiveInputBundleId: und-Latn-x-password, password
11-27 12:34:38.993 W/PackageConfigPersister( 1529): App-specific configuration not found for packageName: com.android.launcher3 and userId: 0
11-27 12:34:39.019 W/FeatureConnection( 3486): getRegistrationTech: ImsRegistration is null
11-27 12:34:39.019 D/PhoneSwitcherNetworkRequstListener( 3486): got request NetworkRequest [ REQUEST id=2996, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10426 RequestorUid: 10434 RequestorPkg: com.android.systemui UnderlyingNetworks: Null] ]
11-27 12:34:39.053 I/CaptureStateNotifier(  934): Registering a listener
11-27 12:34:39.054 I/SoundTriggerMiddlewareLogging( 1529): RESOURCES_AVAILABLE ()
11-27 12:34:39.057 W/APM::AudioPolicyEngine/Base(  934): setPhoneState() setting same state 0
11-27 12:34:39.057 W/APM_AudioPolicyManager(  934): setPhoneState() invalid or same state 0
11-27 12:34:39.062 D/CoreBackPreview( 1529): Window{9bf4e6f u0 Toast}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@53e1f81, mPriority=0, mIsAnimationCallback=false}
11-27 12:34:39.069 W/FeatureConnection( 3486): getRegistrationTech: ImsRegistration is null
11-27 12:34:39.077 V/WindowManager( 1529): Loading animations: layout params pkg=com.android.systemui resId=0x0
11-27 12:34:39.106 W/AS.AudioService( 1529): setLeAudioVolumeOnModeUpdate ignoring invalid device=2, mode=0, index=110 maxIndex=250 streamType=3
11-27 12:34:39.107 D/audio_hw_primary(  935): adev_set_parameters: enter: BT_SCO=off
11-27 12:34:39.110 D/audio_hw_primary(  935): adev_set_parameters: enter: A2dpSuspended=false
11-27 12:34:39.112 D/audio_hw_primary(  935): adev_set_parameters: enter: LeAudioSuspended=false
11-27 12:34:39.113 D/PermissionCache(  934): checking android.permission.MODIFY_AUDIO_ROUTING for uid=1000 => granted (307 us)
11-27 12:34:39.153 I/AS.AudioService( 1529): after audioserver restart: initStreamVolume succeeded
11-27 12:34:39.195 I/AS.SpatializerHelper( 1529): Resetting featureEnabled=false
11-27 12:34:39.195 I/AS.SpatializerHelper( 1529): init effectExpected=true
11-27 12:34:39.195 I/AS.SpatializerHelper( 1529): init(): No Spatializer found
11-27 12:34:39.195 D
```

### Screenshots or videos

https://github.com/user-attachments/assets/70e834cc-b6fe-44de-8332-9a5a9cb88ee0

### Additional context

I did clean flash
Wifi is perfect
Data is great
Looks like is a cpu problem to load the media, but I don't know: I'm not a coder ;)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by serakyel** [comment]
I don't want to say it out loud, but it seems to have resolved itself. I literally did nothing. 🤔
