### ISSUE TITLE
bug: launcher crash in safe mode

### ISSUE THREAD

**Issue by bphd** [crdroidandroid/issue_tracker#58]
### Issue type

User interface

### Device

moon

### crDroid version

crDroid 8

### Exact version

8.10

### Bug description

No launcher

### Steps to reproduce

Boot to safe mode

### Relevant log (logcat/build log)

```shell
$ adb logcat | grep -F "`adb shell ps | grep com.android.launcher3  | tr -s \[:space:\] ' ' | cut -d' ' -f2`" | cut -c 34-

Zygote  : Forked child process 12633
ActivityManager: Start proc 12633:com.android.launcher3/u0a211 for top-activity {com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}
droid.launcher: Not starting debugger since process cannot load the jdwp agent.
ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10211; state: ENABLED
GraphicsEnvironment: ANGLE Developer option for 'com.android.launcher3' set to: 'default'
GraphicsEnvironment: ANGLE GameManagerService for com.android.launcher3: false
GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
NetworkSecurityConfig: No Network Security Config specified, using platform default
NetworkSecurityConfig: No Network Security Config specified, using platform default
hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
OpenGLRenderer: Device claims wide gamut support, cannot find matching config, error = EGL_SUCCESS
OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
Gralloc4: Adding additional valid usage bits: 0x0
ion     : ioctl c0044901 failed with code -1: Invalid argument
FrameEvents: updateAcquireFence: Did not find frame.
FrameEvents: updateAcquireFence: Did not find frame.
Launcher: LauncherAppState initiated
CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10211; state: ENABLED
AndroidRuntime: Shutting down VM
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.android.launcher3, PID: 12633
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher}: android.view.InflateException: Binary XML file line #48 in com.android.launcher3:layout/launcher: Binary XML file line #16 in com.android.launcher3:layout/hotseat: Error inflating class com.android.launcher3.Hotseat
AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3662)
AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3819)
AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7833)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #48 in com.android.launcher3:layout/launcher: Binary XML file line #16 in com.android.launcher3:layout/hotseat: Error inflating class com.android.launcher3.Hotseat
AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #16 in com.android.launcher3:layout/hotseat: Error inflating class com.android.launcher3.Hotseat
AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:863)
AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
AndroidRuntime:        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1245)
AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
AndroidRuntime:        at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(StatefulActivity.java:70)
AndroidRuntime:        at com.android.launcher3.Launcher.onCreate(Launcher.java:475)
AndroidRuntime:        at com.android.launcher3.BaseQuickstepLauncher.onCreate(BaseQuickstepLauncher.java:131)
AndroidRuntime:        at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:130)
AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8057)
AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8037)
AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3643)
AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3819)
AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7833)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #2 in com.android.launcher3:layout/search_container_hotseat: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.addFlags(int)' on a null object reference
AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.addFlags(int)' on a null object reference
AndroidRuntime:        at com.android.launcher3.qsb.QsbLayout.setupGIcon(QsbLayout.java:121)
AndroidRuntime:        at com.android.launcher3.qsb.QsbLayout.onFinishInflate(QsbLayout.java:64)
AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
AndroidRuntime:        at com.android.launcher3.Hotseat.<init>(Hotseat.java:64)
AndroidRuntime:        at com.android.launcher3.Hotseat.<init>(Hotseat.java:57)
AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java:863)
AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
AndroidRuntime:        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1245)
AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
AndroidRuntime:        at com.android.launcher3.statemanager.StatefulActivity.inflateRootView(StatefulActivity.java:70)
AndroidRuntime:        at com.android.launcher3.Launcher.onCreate(Launcher.java:475)
AndroidRuntime:        at com.android.launcher3.BaseQuickstepLauncher.onCreate(BaseQuickstepLauncher.java:131)
AndroidRuntime:        at com.android.launcher3.uioverrides.QuickstepLauncher.onCreate(QuickstepLauncher.java:130)
AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8057)
AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8037)
AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3643)
AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3819)
AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7833)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Process : Sending signal. PID: 12633 SIG: 9
ActivityManager: Process com.android.launcher3 (pid 12633) has died: fg  TOP 
Zygote  : Process 12633 exited due to signal 9 (Killed)
libprocessgroup: Successfully killed process cgroup uid 10211 pid 12633 in 0ms
libprocessgroup: Successfully killed process cgroup uid 10211 pid 12633 in 0ms
```

### Additional context

Which lead to not being able to

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this issue has been fixed in code on newer releases

**Comment by bphd** [comment]
Could you relate to the duplicate that have been resolved? And explain in what you think problems are related to mine?

**Comment by gwolf2u** [comment]
was launcher hotseat issue
been fixed in code as stated
you'll need to get a new build up from maintainer in order to see fix applied

**Comment by bphd** [comment]
It was solved in intern, or it has an issue link?
