### ISSUE TITLE
bug: No GPS/GMS/Location/Whatever

### ISSUE THREAD

**Issue by bphd** [crdroidandroid/issue_tracker#59]
### Issue type

Feature not working as intended

### Device

moon

### crDroid version

crDroid 8

### Exact version

8.10

### Bug description

No location

### Steps to reproduce

Try getting location

### Relevant log (logcat/build log)

```shell
time: 1670946989723
msg: java.lang.ArrayIndexOutOfBoundsException: length=29; index=29
stacktrace: java.lang.ArrayIndexOutOfBoundsException: length=29; index=29
	at com.gps.status.views.GpsSkyView.setSats(GpsSkyView.java:166)
	at com.gps.status.pager.GpsSkyFragment.onGpsStatusChanged(GpsSkyFragment.java:142)
	at com.gps.status.MainActivity$1.onGpsStatusChanged(MainActivity.java:109)
	at android.location.LocationManager$GpsAdapter.onSatelliteStatusChanged(LocationManager.java:3241)
	at android.location.LocationManager$GnssStatusTransport.lambda$onSvStatusChanged$1(LocationManager.java:3299)
	at android.location.LocationManager$GnssStatusTransport$$ExternalSyntheticLambda1.accept(Unknown Source:4)
	at com.android.internal.listeners.ListenerTransport.lambda$execute$0(ListenerTransport.java:60)
	at com.android.internal.listeners.ListenerTransport$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
install gapps before rom boot

**Comment by bphd** [comment]
It happens with microG revived. Ask before closing

The ROM will not get better by elaging the number of issues that way

You know, people takes times to report problems here. It's useless if you close them because they bore you

**Comment by gwolf2u** [comment]
even if we added support for microG, is not a thing we manage 
we don't even manage gapps also
gapps need to be flashed before first boot and GPS will work as intended
also, microG is known to be tricky to manage regarding GPS

**Comment by bphd** [comment]
Okay so this problem should be solved with packager of gApps for custom ROM, not here?

**Comment by gwolf2u** [comment]
No am not saying is gapps package issue
Am saying that the way user installed it can cause the issue

**Comment by bphd** [comment]
I'm using an automated way provided by that revived team
