### ISSUE TITLE
bug: Random crash prompt

### ISSUE THREAD

**Issue by bphd** [crdroidandroid/issue_tracker#60]
### Issue type

User interface

### Device

moon

### crDroid version

crDroid 8

### Exact version

8.10

### Bug description

Random crash prompt

### Steps to reproduce

Install CrDroid

### Relevant log (logcat/build log)

```java
time: 1670952651826
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:281)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6618)
	at android.app.ActivityThread.access$1500(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2080)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

time: 1671030597042
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
	at android.app.ConfigurationController.updateLocaleListFromAppContext(ConfigurationController.java:281)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6618)
	at android.app.ActivityThread.access$1500(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2080)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
invalid issue
even if log is there, is not specific enough 
full log needed or steps to reproduce

**Comment by bphd** [comment]
It's your own ROM who gives automatically link to these logs. You're telling that the report method of the ROM is not enough? Okay but then it's not my fault. And even with that, it doesn't mean the problem is gone and solved

Full logs, you mean Android logs? The thing spitting 100 lines per seconds? For real? And you could ask for details before closing

And good luck at reproducing random crashes

**Comment by gwolf2u** [comment]
you may as well attach the file
and yes, full log is needed

**Comment by bphd** [comment]
> you may as well attach the file and yes, full log is needed

I don't think GitHub (nor my phone) has the ability to handle full logs produced
