### ISSUE TITLE
bug: Dolby Atmos Crash

### ISSUE THREAD

**Issue by kirbyloco** [crdroidandroid/issue_tracker#69]
### Issue type

Feature not working as intended

### Device

Oneplus 7 Pro (guacamole)

### crDroid version

crDroid 9

### Exact version

9.0 20221226

### Bug description

Use Plex play video with AAC 5.1 track, cant change Dolby Atmos effects,
But AAC 2.0 track is normal.

### Steps to reproduce

Step .1 Use Plex play video with AAC 5.1 track,
Step .2 Go to setting -> Dolby Atmos

### Relevant log (logcat/build log)

```shell
time: 1672197966447
msg: java.lang.RuntimeException: Cannot initialize effect engine for type: ec7178ec-e5e1-4432-a3f4-4657e6795210 Error: -3
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dolby.daxappui/com.dolby.daxappui.MainActivity}: java.lang.RuntimeException: Cannot initialize effect engine for type: ec7178ec-e5e1-4432-a3f4-4657e6795210 Error: -3
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
Caused by: java.lang.RuntimeException: Cannot initialize effect engine for type: ec7178ec-e5e1-4432-a3f4-4657e6795210 Error: -3
	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:543)
	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:501)
	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:475)
	at com.dolby.dax.DolbyAudioEffect.<init>(DolbyAudioEffect.java:107)
	at com.dolby.daxappui.MainActivity.onCreate(MainActivity.java:369)
	at android.app.Activity.performCreate(Activity.java:8305)
	at android.app.Activity.performCreate(Activity.java:8284)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
	... 12 more
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
please provide full log

**Comment by kirbyloco** [comment]
@gwolf2u 
Here`s log
[2022-12-29-08-19-11.txt](https://github.com/crdroidandroid/issue_tracker/files/10317009/2022-12-29-08-19-11.txt)

**Comment by kirbyloco** [comment]
On 9.1 20230113 fixed
