### ISSUE TITLE
bug: camera not working on crDroid 8.11 (merlinx)

### ISSUE THREAD

**Issue by arseru** [crdroidandroid/issue_tracker#78]
### Issue type

Feature not working as intended

### Device

Redmi Note 9 (merlinx)

### crDroid version

crDroid 8

### Exact version / Build date

8.11/2022-11-26 (Android 12)

### Bug description

The stock camera app does not open at all; upon clicking on it, it shows the camera icon screen but at some point it crashes, sometimes showing the 'Report bug' menu, sometimes only returning to the app drawer.

### Steps to reproduce

1. Open stock camera app with the phone unlocked.

Or

1. Double-click power button to open stock camera app from lockscreen.

### Relevant log (logcat/build log)

```shell
time: 1672615036519
msg: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.camera2/com.android.camera.CameraActivity}: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3662)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3819)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:102)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at android.util.ArrayMap.valueAt(ArrayMap.java:524)
	at android.hardware.camera2.CameraManager$CameraManagerGlobal.extractCameraIdListLocked(CameraManager.java:1530)
	at android.hardware.camera2.CameraManager$CameraManagerGlobal.getCameraIdList(CameraManager.java:1699)
	at android.hardware.camera2.CameraManager.getCameraIdList(CameraManager.java:211)
	at com.android.camera.one.v2.Camera2OneCameraManagerImpl.findFirstCameraIdFacing(Camera2OneCameraManagerImpl.java:186)
	at com.android.camera.one.v2.Camera2OneCameraManagerImpl.findFirstBackCameraId(Camera2OneCameraManagerImpl.java:157)
	at com.android.camera.one.v2.Camera2OneCameraManagerImpl.findCameraId(Camera2OneCameraManagerImpl.java:145)
	at com.android.camera.one.v2.Camera2OneCameraManagerImpl.findFirstCameraFacing(Camera2OneCameraManagerImpl.java:114)
	at com.android.camera.one.v2.Camera2OneCameraManagerImpl.<init>(Camera2OneCameraManagerImpl.java:77)
	at com.android.camera.one.v2.Camera2OneCameraManagerImpl.create(Camera2OneCameraManagerImpl.java:61)
	at com.android.camera.one.OneCameraModule.provideOneCameraManager(OneCameraModule.java:68)
	at com.android.camera.CaptureModule.init(CaptureModule.java:410)
	at com.android.camera.CameraActivity.onCreateTasks(CameraActivity.java:1642)
	at com.android.camera.util.QuickActivity.onCreate(QuickActivity.java:114)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1347)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3643)
	... 12 more
```

### Screenshots or videos

See additional logcat messages [here](https://gist.github.com/arseru/c4ae81f0f907d4e4a2d0023c8b418da1).

### Additional context

It's a fresh install of https://crdroid.net/merlinx/8, the steps performed to flash it were:

```
# Flash TWRP
adb reboot bootloader
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
fastboot flash recovery twrp_3.62_12_merlin_merlinx_vanilla_by_@shas45558.img
# Reboot to recovery
fastboot reboot recovery
# In TWRP, go to Wipe / Format Data, type 'yes'

# Transfer and install Firmware file from TWRP
adb push fw_merlin_miui_MERLINGlobal_V13.0.2.0.SJOMIXM_ab1497c451_12.0.zip /sdcard
# Transfer and install crDroid from TWRP
adb push crDroidAndroid-12.1-20221126-merlinx-v8.11.zip /sdcard
# Transfer and install Gapps from TWRP
adb push MindTheGapps-12.1.0-arm64-20220605_112439.zip /sdcard
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
merlinx is EoL
