### ISSUE TITLE
bug: instagram playback error on crDroid 8.11 (merlinx) - BufferQueue has no connected producer

### ISSUE THREAD

**Issue by arseru** [crdroidandroid/issue_tracker#79]
### Issue type

Feature not working as intended

### Device

Redmi Note 9 (merlinx)

### crDroid version

crDroid 8

### Exact version / Build date

8.11/2022-11-26 (Android 12)

### Bug description

Playback video from instagram stories does not work; upon clicking on a story, a loading icon is being shown in the upper-right side, and it stays like this forever, never playing the video in the story.

### Steps to reproduce

1. Install and open Instagram app from Play Store.
2. Click on a story containing a video.

### Relevant log (logcat/build log)

```shell
2023-01-02 11:11:06.956  9002-10127 BufferQueueProducer     com.instagram.android                E  [SurfaceTexture-0-9002-6](id:232a0000000e,api:0,p:-1,c:9002) dequeueBuffer: BufferQueue has no connected producer
2023-01-02 11:11:06.958  9002-10604 ReflectedParamUpdater   com.instagram.android                D  extent() != 1 for single value type: algo.buffers.max-count.values
2023-01-02 11:11:06.958  9002-10575 ExoPlayerImplInternal   com.instagram.android                E  Stop failed.
                                                                                                    java.lang.IllegalStateException
                                                                                                        at android.media.MediaCodec.native_stop(Native Method)
                                                                                                        at android.media.MediaCodec.stop(MediaCodec.java:2297)
                                                                                                        at X.3G9.stop(:2)
                                                                                                        at X.3G6.A02(:438)
                                                                                                        at X.3BQ.A0J(:71)
                                                                                                        at X.3EY.A0J(:2)
                                                                                                        at X.3BQ.A0D(:5)
                                                                                                        at X.3EY.A0D(:66)
                                                                                                        at X.3CZ.A0F(:50)
                                                                                                        at X.3CZ.A0J(:39)
                                                                                                        at X.3CZ.A0I(:1)
                                                                                                        at X.3CZ.handleMessage(:3476)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                        at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                        at android.os.Looper.loop(Looper.java:288)
                                                                                                        at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Screenshots or videos

See additional logcat messages [here](https://gist.github.com/arseru/5dc46a747da33c1c2cce1b8068044f8b).

### Additional context

It's a fresh install of https://crdroid.net/merlinx/8, the steps performed to flash it were:

```
# Flash TWRP
adb reboot bootloader
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
fastboot flash recovery twrp_3.62_12_merlin_merlinx_vanilla_by_@shas45558.img
# Reboot to recovery
fastboot reboot recovery
# In TWRP, go to Wipe / Format Data, type 'yes'

# Transfer and install Firmware file from TWRP
adb push fw_merlin_miui_MERLINGlobal_V13.0.2.0.SJOMIXM_ab1497c451_12.0.zip /sdcard
# Transfer and install crDroid from TWRP
adb push crDroidAndroid-12.1-20221126-merlinx-v8.11.zip /sdcard
# Transfer and install Gapps from TWRP
adb push MindTheGapps-12.1.0-arm64-20220605_112439.zip /sdcard
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
merlinx is EoL

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
