### ISSUE TITLE
bug: Smart charging not working

### ISSUE THREAD

**Issue by austinalex23** [crdroidandroid/issue_tracker#88]
### Issue type

Feature not working as intended

### Device

Oneplus 7 Pro (guacamole)

### crDroid version

crDroid 9

### Exact version / Build date

crDroid 9.0/2023-01-08

### Bug description

Enabling Smart Charging does not have any effect. The device will accept a charge regardless of the percentages set. 

### Steps to reproduce

Step 1. Settings->Smart Charging
Step 2. Enable smart charging
Step 3. Set trigger levels
Step 4. Plug-in device
Step 5. Watch the device continue to charge above the trigger level

### Relevant log (logcat/build log)

```shell
01-09 17:26:37.513 I/hwservicemanager(656): getTransport: Cannot find entry vendor.lineage.fastcharge@1.0::IFastCharge/default in either framework or device VINTF manifest.
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): Failed to get IFastCharge interface
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): java.util.NoSuchElementException
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at android.os.HwBinder.getService(Native Method)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at android.os.HwBinder.getService(HwBinder.java:81)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at vendor.lineage.fastcharge.V1_0.IFastCharge.getService(IFastCharge.java:74)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at vendor.lineage.fastcharge.V1_0.IFastCharge.getService(IFastCharge.java:84)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at com.android.settings.fuelgauge.FastChargingPreferenceController.<init>(FastChargingPreferenceController.java:46)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at com.android.settings.core.BasePreferenceController.createInstance(BasePreferenceController.java:161)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at com.android.settings.core.PreferenceControllerListHelper.getPreferenceControllersFromXml(PreferenceControllerListHelper.java:72)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at com.android.settings.search.BaseSearchIndexProvider.getPreferenceControllers(BaseSearchIndexProvider.java:149)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at com.android.settings.search.BaseSearchIndexProvider.getNonIndexableKeys(BaseSearchIndexProvider.java:114)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at com.android.settings.fuelgauge.batteryusage.PowerUsageSummary$4.getNonIndexableKeys(PowerUsageSummary.java:412)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at com.android.settings.search.SettingsSearchIndexablesProvider.getNonIndexableKeysFromProvider(SettingsSearchIndexablesProvider.java:284)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at com.android.settings.search.SettingsSearchIndexablesProvider.queryNonIndexableKeys(SettingsSearchIndexablesProvider.java:157)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at android.provider.SearchIndexablesProvider.query(SearchIndexablesProvider.java:127)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at android.content.ContentProvider.query(ContentProvider.java:1455)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at android.content.ContentProvider.query(ContentProvider.java:1551)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:285)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at android.os.Binder.execTransactInternal(Binder.java:1283)
01-09 17:26:37.513 E/FastChargingPreferenceController(29923): 	at android.os.Binder.execTransact(Binder.java:1227)
01-09 17:26:52.233 I/hwservicemanager(656): getTransport: Cannot find entry vendor.lineage.fastcharge@1.0::IFastCharge/default in either framework or device VINTF manifest.
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): Failed to get IFastCharge interface
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): java.util.NoSuchElementException
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.os.HwBinder.getService(Native Method)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.os.HwBinder.getService(HwBinder.java:81)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at vendor.lineage.fastcharge.V1_0.IFastCharge.getService(IFastCharge.java:74)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at vendor.lineage.fastcharge.V1_0.IFastCharge.getService(IFastCharge.java:84)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.settings.fuelgauge.FastChargingPreferenceController.<init>(FastChargingPreferenceController.java:46)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.settings.core.BasePreferenceController.createInstance(BasePreferenceController.java:161)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.settings.core.PreferenceControllerListHelper.getPreferenceControllersFromXml(PreferenceControllerListHelper.java:72)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.settings.dashboard.DashboardFragment.onAttach(DashboardFragment.java:97)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.settings.fuelgauge.batteryusage.PowerUsageSummary.onAttach(PowerUsageSummary.java:172)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2981)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:463)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:254)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1780)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:586)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:772)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:554)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.settings.SettingsActivity.createUiFromIntent(SettingsActivity.java:310)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:269)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.app.Activity.performCreate(Activity.java:8305)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.app.Activity.performCreate(Activity.java:8284)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1423)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.os.Looper.loopOnce(Looper.java:201)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.os.Looper.loop(Looper.java:288)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at java.lang.reflect.Method.invoke(Native Method)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-09 17:26:52.235 E/FastChargingPreferenceController(29923): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
01-09 17:26:59.278 I/hwservicemanager(656): getTransport: Cannot find entry vendor.lineage.fastcharge@1.0::IFastCharge/default in either framework or device VINTF manifest.
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): Failed to get IFastCharge interface
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): java.util.NoSuchElementException
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at android.os.HwBinder.getService(Native Method)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at android.os.HwBinder.getService(HwBinder.java:81)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at vendor.lineage.fastcharge.V1_0.IFastCharge.getService(IFastCharge.java:74)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at vendor.lineage.fastcharge.V1_0.IFastCharge.getService(IFastCharge.java:84)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at com.android.settings.fuelgauge.FastChargingPreferenceController.<init>(FastChargingPreferenceController.java:46)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at com.android.settings.core.BasePreferenceController.createInstance(BasePreferenceController.java:161)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at com.android.settings.core.PreferenceControllerListHelper.getPreferenceControllersFromXml(PreferenceControllerListHelper.java:72)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at com.android.settings.search.BaseSearchIndexProvider.getPreferenceControllers(BaseSearchIndexProvider.java:149)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at com.android.settings.search.BaseSearchIndexProvider.getNonIndexableKeys(BaseSearchIndexProvider.java:114)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at com.android.settings.fuelgauge.batteryusage.PowerUsageSummary$4.getNonIndexableKeys(PowerUsageSummary.java:412)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at com.android.settings.search.SettingsSearchIndexablesProvider.getNonIndexableKeysFromProvider(SettingsSearchIndexablesProvider.java:284)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at com.android.settings.search.SettingsSearchIndexablesProvider.queryNonIndexableKeys(SettingsSearchIndexablesProvider.java:157)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at android.provider.SearchIndexablesProvider.query(SearchIndexablesProvider.java:127)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at android.content.ContentProvider.query(ContentProvider.java:1455)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at android.content.ContentProvider.query(ContentProvider.java:1551)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:285)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at android.os.Binder.execTransactInternal(Binder.java:1283)
01-09 17:26:59.279 E/FastChargingPreferenceController(29923): 	at android.os.Binder.execTransact(Binder.java:1227)
01-09 17:27:03.958 D/SettingsActivity(29923): Switching to fragment com.crdroid.settings.fragments.misc.SmartCharging
01-09 17:27:03.958 D/SubSettings(29923): Launching fragment com.crdroid.settings.fragments.misc.SmartCharging
01-09 17:27:03.962 D/ConstraintsHelper(29923): construct key=smart_charging available=true
01-09 17:27:03.963 D/ConstraintsHelper(29923): construct key=smart_charging_reset_stats available=true
01-09 17:28:04.358 E/BatteryService(1744): Failed to read oem fast charger status path: /sys/devices/platform/soc/soc:oplus,chg_intf/oplus_chg/usb/fastchg_status /sys/devices/platform/soc/soc:oplus,chg_intf/soc:oplus,chg_intf:oplus,wireless-charge/oplus_chg/wireless/fastchg_status
01-09 17:28:04.358 E/BatteryService(1744): Failed to read oem fast charger status path: /sys/devices/platform/soc/soc:oplus,chg_intf/oplus_chg/usb/fastchg_status /sys/devices/platform/soc/soc:oplus,chg_intf/soc:oplus,chg_intf:oplus,wireless-charge/oplus_chg/wireless/fastchg_status
01-09 17:28:25.610 E/BatteryService(1744): Failed to read oem fast charger status path: /sys/devices/platform/soc/soc:oplus,chg_intf/oplus_chg/usb/fastchg_status /sys/devices/platform/soc/soc:oplus,chg_intf/soc:oplus,chg_intf:oplus,wireless-charge/oplus_chg/wireless/fastchg_status
01-09 17:28:25.610 E/BatteryService(1744): Failed to read oem fast charger status path: /sys/devices/platform/soc/soc:oplus,chg_intf/oplus_chg/usb/fastchg_status /sys/devices/platform/soc/soc:oplus,chg_intf/soc:oplus,chg_intf:oplus,wireless-charge/oplus_chg/wireless/fastchg_status
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
aware of this, yet no fix yet
