### ISSUE TITLE
bug: Google assistant crash using HW assistant button

### ISSUE THREAD

**Issue by Howarddj** [crdroidandroid/issue_tracker#98]
### Issue type

Source code related

### Device

Sony Xperia 5ii (pdx206)

### crDroid version

crDroid 9

### Exact version / Build date

9.1/Unofficial - 2023-01-16

### Bug description

Pressing Physical assistant hardware button on the side of the device causes systemUI to crash and soft reboot to crDroid boot animation.
Google assistant is installled and works when long pressing home button

### Steps to reproduce

install google assistant > press assistant button on side of device

### Relevant log (logcat/build log)

```shell
--------- beginning of crash
01-17 11:14:19.344  1545  1567 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.ui
01-17 11:14:19.344  1545  1567 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
01-17 11:14:19.344  1545  1567 E AndroidRuntime: 	at com.android.server.policy.PhoneWindowManager$PolicyHandler.handleMessage(PhoneWindowManager.java:819)
01-17 11:14:19.344  1545  1567 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-17 11:14:19.344  1545  1567 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-17 11:14:19.344  1545  1567 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-17 11:14:19.344  1545  1567 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-17 11:14:19.344  1545  1567 E AndroidRuntime: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
01-17 11:14:19.344  1545  1567 E AndroidRuntime: 	at com.android.server.UiThread.run(UiThread.java:45)
01-17 11:14:19.668  2654  2654 E AndroidRuntime: FATAL EXCEPTION: main
01-17 11:14:19.668  2654  2654 E AndroidRuntime: Process: com.android.phone, PID: 2654
01-17 11:14:19.668  2654  2654 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
01-17 11:14:19.703 14529 14529 E AndroidRuntime: FATAL EXCEPTION: main
01-17 11:14:19.703 14529 14529 E AndroidRuntime: Process: com.android.launcher3, PID: 14529
01-17 11:14:19.703 14529 14529 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
01-17 11:14:19.720  2908  2908 E AndroidRuntime: FATAL EXCEPTION: main
01-17 11:14:19.720  2908  2908 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 2908
01-17 11:14:19.720  2908  2908 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
01-17 19:15:14.304  9392  9423 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.ui
01-17 19:15:14.304  9392  9423 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
01-17 19:15:14.304  9392  9423 E AndroidRuntime: 	at com.android.server.policy.PhoneWindowManager$PolicyHandler.handleMessage(PhoneWindowManager.java:819)
01-17 19:15:14.304  9392  9423 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-17 19:15:14.304  9392  9423 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-17 19:15:14.304  9392  9423 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-17 19:15:14.304  9392  9423 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-17 19:15:14.304  9392  9423 E AndroidRuntime: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
01-17 19:15:14.304  9392  9423 E AndroidRuntime: 	at com.android.server.UiThread.run(UiThread.java:45)
01-17 19:15:14.703 11003 11003 E AndroidRuntime: FATAL EXCEPTION: main
01-17 19:15:14.703 11003 11003 E AndroidRuntime: Process: com.google.android.googlequicksearchbox:interactor, PID: 11003
01-17 19:15:14.703 11003 11003 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
01-17 19:15:14.704 11003 11200 E AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
01-17 19:15:14.704 11003 11200 E AndroidRuntime: Process: com.google.android.googlequicksearchbox:interactor, PID: 11003
01-17 19:15:14.704 11003 11200 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Howarddj** [comment]
Update:

changing the function of the assistant button doesnt have any effect, no matter what it is set to to when you press the button it crashes the system UI. 

any help would be appreciated .

**Comment by SirRGB** [comment]
Can confirm, crashes on 9.2 without gapps as well

**Comment by gwolf2u** [comment]
what's the status of this on cr9.3 ?

**Comment by SirRGB** [comment]
Didnt work for me
I just removed all fuctionality of that button so it doesnt crash

**Comment by neobuddy89** [comment]
Added a fix. Please test in next build.

**Comment by SirRGB** [comment]
Was reported that it didnt work, cant test myself anymore as it is my daily driver now.
